Patch 3
Cog-Creators/Red-DiscordBot pull request #1076
Opened 2017-11-03 19:11 UTC by aikaterna

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
Move the cogs command from downloader to CogManager

2017-11-03 22:52 UTC, tekulvw requested changes

2017-11-03 22:52 UTC, tekulvw commented on redbot/core/cog_manager.py
> +        loaded = set(self.bot.extensions.keys())
Need to change to `ctx.bot`

2017-11-05 14:32 UTC, Twentysix26 commented
I haven't tested it but I doubt it worked without that import 😛  
Looks good to go now

2017-11-05 14:32 UTC, Twentysix26 approved these changes

2017-11-05 18:05 UTC, tekulvw approved these changes

2017-11-05 18:05 UTC, merged