[V3 Help] Convert help command to support embeds
Cog-Creators/Red-DiscordBot pull request #1106
Opened 2017-11-19 22:35 UTC by tekulvw

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

2017-11-21 23:50 UTC, Twentysix26 submitted a review, later dismissed

2017-11-23 06:31 UTC, palmtree5 approved these changes

2017-11-23 07:03 UTC, palmtree5 requested changes
Doesn't handle the case where the bot doesn't have permissions to embed links in a given channel

2017-11-25 00:42 UTC, palmtree5 approved these changes

2017-11-27 01:04 UTC, merged