Add prompt if message deletion > 100
Cog-Creators/Red-DiscordBot pull request #1304
Opened 2018-02-13 01:47 UTC by Bakersbakebread

As per issue #1295. 

Add's the prompt "Are you sure you want to delete {number} messages? (y/n)"

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

add's a prompt to user if messages to be deleted > 100.

prompt is:
Are you sure you want to delete {number} messages? (y/n)

2018-02-15 01:28 UTC, palmtree5 approved these changes

2018-02-15 01:29 UTC, mikeshardmind commented
This needs a check inside the wait for message that they author is the person the bot got the message for, channel should probably be included in that check as well

2018-02-15 01:29 UTC, palmtree5 requested changes
Needs a check to only accept answers from the user running the command

2018-02-16 21:54 UTC, Bakersbakebread commented
Checks added, also deleted the "Continuing" message for maximum deletion.

Deleteception.

2018-02-16 22:02 UTC, palmtree5 requested changes

2018-02-16 22:02 UTC, palmtree5 commented on redbot/cogs/cleanup/cleanup.py
> +        await tmp.delete()
Unneeded?

2018-02-16 23:44 UTC, Bakersbakebread commented on redbot/cogs/cleanup/cleanup.py
> +        await tmp.delete()
Definitely.

2018-02-19 02:41 UTC, palmtree5 approved these changes

2018-02-19 02:44 UTC, merged