[V3 Utils] Menu system
Cog-Creators/Red-DiscordBot pull request #1566
Opened 2018-04-24 06:08 UTC by palmtree5

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
This is a possible implementation for a menu system. Basically, cog devs can pass in context, a list of either strings or embeds and a dict mapping of emoji to functions and the user will get a menu controlled by emoji. An example:

```py
from redbot.core.utils.menus import menu, DEFAULT_CONTROLS
import discord

class MyCog:
    @commands.command()
    async def mycom(self, ctx):
        pages = [discord.Embed(title="blah"), discord.Embed(title="blah 2")]
        await menu(ctx, pages, DEFAULT_CONTROLS)
```
will yield a menu where users can change pages and close the menu

`DEFAULT_CONTROLS` is basically a quick way to use the menu system if cog devs are fine using some default functions to handle menu controls (basically, these are a function to move to the next page, a function to move to the previous page, and a function to close the menu (deleting the message that is the menu))

2018-04-24 19:25 UTC, bobloy commented on redbot/core/utils/menus.py
> +        next_page = 0  # Loop around to the first item
Use `next_page` as variable and `next_page` and function

2018-04-27 18:36 UTC, bobloy commented
It appears multiple instances of a menu will trigger each other's button presses. 
i.e ❌ will close all menus

2018-05-01 18:20 UTC, Bakersbakebread commented
Upvote

2018-05-01 18:29 UTC, bobloy requested changes

2018-05-01 18:29 UTC, bobloy commented on redbot/core/utils/menus.py
> +        return u == ctx.author and str(r.emoji) in controls.keys()
add `and r.message==message`

2018-05-01 18:29 UTC, bobloy commented on redbot/core/utils/menus.py
> +    "⬅": prev_page,
Swap order of `next_page` and `prev_page` for clearer buttons

2018-05-04 03:50 UTC, Kowlin approved these changes

2018-05-04 03:54 UTC, merged