[V3 Info] Don't rely on redirect
Cog-Creators/Red-DiscordBot pull request #1581
Opened 2018-05-01 05:01 UTC by Wyn10

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Fix following trace:

```
Exception in command 'info'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/redbot/core/core_commands.py", line 76, in info
    data = await r.json()
  File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 730, in json
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'
```

2018-05-01 05:06 UTC, Redjumpman commented
Just started experiencing this problem myself. The above changes fixes it for me.

2018-05-01 11:27 UTC, Bakersbakebread commented
`Starting alfred...
Connected to Discord. Getting ready...
Loading packages...
[01/05/2018 12:26] ERROR events on_error 174: Exception in on_ready
Traceback (most recent call last):
  File "d:\alfred\venv\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "d:\alfred\venv\lib\site-packages\redbot\core\events.py", line 114, in on_ready
    data = await r.json()
  File "d:\alfred\venv\lib\site-packages\aiohttp\client_reqrep.py", line 730, in json
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'`

Getting the same error, above fixes for me.

2018-05-01 13:18 UTC, bobloy commented
Bread, your error is not the same error. Your error is in events.py, not core_commands.py

2018-05-01 13:39 UTC, bobloy requested changes
`core/events.py` has the same problem and should be updated as well.

2018-05-01 13:39 UTC, bobloy commented on redbot/core/core_commands.py
> +            async with session.get("https://pypi.python.org/pypi/red-discordbot/json") as r:
Replace this with `red_pypi` defined above

2018-05-02 08:35 UTC, Kowlin approved these changes

2018-05-02 08:35 UTC, merged