[V3] User Facing Responses
Cog-Creators/Red-DiscordBot pull request #1624
Opened 2018-05-09 21:42 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
This is a WIP PR addressing updating all core cogs not currently respecting `embed_requested` and the positional/keyword formats as discussed in #1436 and #1526

Because of the scope of potential conflicts during merge, I'll be keeping this updated as we get closer to releases. 

This only handles some of mod.py as of now, I'll be adding more as I have time.

2018-05-12 20:38 UTC, mikeshardmind commented
Not ready for b14

2018-05-21 11:59 UTC, mikeshardmind commented
I modified the scope of this PR to just the mod cog, I'm also opening an issue to track which cogs will still need similar PRs

2018-05-23 02:50 UTC, Tobotimus submitted a review, later dismissed

2018-05-24 21:31 UTC, palmtree5 requested changes
Not that I particularly support embedding everything the bot sends, but if this is to be merged, the one comment here needs to be fixed because it will cause errors

2018-05-24 21:31 UTC, palmtree5 commented on redbot/cogs/mod/mod.py
> +                    await user.send(embed=discord.Embed(msg))
Won't work

2018-05-25 03:32 UTC, mikeshardmind commented
This shouldn't be merged until the discussion about embeds in #advanced-coding discord channel is resolved and any needed changes after it are made.

2018-05-25 07:34 UTC, closed without merging