[V3 Warnings] Send DM option
Cog-Creators/Red-DiscordBot pull request #1664
Opened 2018-05-15 18:32 UTC by retke

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

This option will make the bot send a DM with the warn reason when the command is used. I know you guys don't like the DMed reasons but this is something a lot of servers are using, so I though this would be cool to add.

2018-05-15 18:38 UTC, tekulvw requested changes

2018-05-15 18:38 UTC, tekulvw commented on redbot/cogs/warnings/warnings.py
> -                )
You need to add this back...your code as-is won't even compile.

2018-05-15 18:43 UTC, laggron42 commented on redbot/cogs/warnings/warnings.py
> -                )
Don't see why it got removed, I'll add it back

2018-05-25 10:16 UTC, laggron42 commented
Actually I have better plans. I'll close this and make something better. May be ready for next beta.

2018-05-25 10:16 UTC, closed without merging