[V3/QoL] Fixes for missing punctuation, spelling, doc string formatting and grammar mistakes.
Cog-Creators/Red-DiscordBot pull request #1733
Opened 2018-05-28 07:53 UTC by Redjumpman

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Multiple fixes for punctuation, spelling docstring formatting,, and grammar mistakes.

2018-05-28 23:07 UTC, tekulvw requested changes

2018-05-28 23:07 UTC, tekulvw commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Invalid?

2018-05-28 23:07 UTC, tekulvw commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Invalid?

2018-05-28 23:07 UTC, tekulvw commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Invalid?

2018-05-28 23:07 UTC, tekulvw commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Invalid?

2018-05-28 23:07 UTC, tekulvw commented on redbot/cogs/streams/streams.py
> +                _("{} will no longer be mentioned " "for a stream alert.").format(
Can you remove the `" "`?

2018-05-29 21:47 UTC, Redjumpman commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Done.

2018-05-29 21:47 UTC, Redjumpman commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Done.

2018-05-29 21:47 UTC, Redjumpman commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Done.

2018-05-29 21:47 UTC, Redjumpman commented on redbot/cogs/permissions/permissions.py
> +            return await ctx.send(_("Inalid syntax."))
Done.

2018-05-29 21:47 UTC, Redjumpman commented on redbot/cogs/streams/streams.py
> +                _("{} will no longer be mentioned " "for a stream alert.").format(
Fixed a bunch of these.

2018-05-29 21:48 UTC, Redjumpman commented
@tekulvw Fixed all the stuff you pointed out. Found a bunch of those `" "` in streams. All fixed.

2018-05-30 06:21 UTC, Redjumpman commented
having trouble rebasing. Closing this to reopen in a bit.

2018-05-30 06:21 UTC, closed without merging