Changed urban dictionary for my embed version
Cog-Creators/Red-DiscordBot pull request #1871
Opened 2018-06-15 21:32 UTC by lionirdeadman

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Replaced the old urban dictionary command to an embed version I made which adds:
- The author name 
- Thumbs ups
- Thumbs downs
- Reaction menu to see the different definitions

2018-06-26 03:48 UTC, lionirdeadman commented
I'll update my branch (to include the changes made to V3/develop) after the code is reviewed if you don't mind. 

I don't really want to update this branch all the time while I wait for review, hope you understand.

2018-06-28 13:17 UTC, Tobotimus requested changes
Hi, thanks for your contribution! :tada:

I like the new menu interface, much better than the old one! However there are a couple things which need to be changed in your code before we'll accept this :smiley:
 
Once you've made the changes, please post a comment to let us know.

2018-06-28 13:17 UTC, Tobotimus commented on redbot/cogs/general/general.py
> +        """Searches for urban dictionary entries using the unofficial urbandictionary api"""
This help string is a bit long. Try to make the first line shorter than 72 characters, but the user should still know exactly what the command does from that line. Any further detail should be expanded after two line-breaks.

2018-06-28 13:17 UTC, Tobotimus commented on redbot/cogs/general/general.py
> +        data = None
Early declaration of variable here is unnecessary

2018-06-28 13:17 UTC, Tobotimus commented on redbot/cogs/general/general.py
> +            await ctx.send("No Urban dictionary were found or there was an error in the process")
You'll want to return here

2018-06-28 13:17 UTC, Tobotimus commented on redbot/cogs/general/general.py
> +                )
Please use `"".format()` where instead of concatenating strings, and also add back in the i18n call (which is surrounding the string with `_()`.

2018-06-28 13:17 UTC, Tobotimus commented on redbot/cogs/general/general.py
> +            await ctx.send("No Urban dictionary were found or there was an error in the process")
Also, this sentence isn't quite grammatically correct, and needs to be wrapped in `_()`

2018-06-28 13:17 UTC, Tobotimus commented on redbot/cogs/general/general.py
> +                )
Please use `"".format()` here too

2018-06-28 19:49 UTC, lionirdeadman commented
I think I've changed everything you asked for. Thanks for the review. :)

2018-06-28 20:41 UTC, lionirdeadman commented
Had to come up with a fix for the 2048 character limit of descriptions, I hadn't thought of it.

2018-07-22 20:39 UTC, lionirdeadman commented
Just commenting again since this is supposed to be for B18 according to the tag so I'd like a review again. Thank you.

2018-07-25 00:48 UTC, Kowlin commented
I'm going to place this on hold to review with other core developers. See what they think.

2018-07-25 04:55 UTC, mikeshardmind commented
This is sleek, and I like it a lot. The only problem I have with it is that it does not respect the core embed requested setting. It might be better to break this out into 2 separate functions, (old code and new) and have the appropriate one based on that setting called when the command is invoked.

2018-07-27 16:51 UTC, lionirdeadman commented
I don't know how to respect the embed setting, if you could give me pointers, I'd be glad to do it, @mikeshardmind. 

Feel free to PM me in Discord instead of commenting here so we can do this faster! :smile:

2018-07-27 22:52 UTC, mikeshardmind commented
There's a helper method in [context ](https://github.com/Cog-Creators/Red-DiscordBot/blob/e3bff7e87cfca23dd36bf92507a99636d7033171/redbot/core/commands/context.py#L160)for this since this particular command always should respond in the same location it was called from.

```py
if await ctx.embed_requested():
    #  output version using an embed
else:
    #  output version without an embed
```

2018-07-30 00:35 UTC, lionirdeadman commented
I think I did it properly so this should be done now!

2018-07-30 01:57 UTC, mikeshardmind commented
Looks solid. :+1:

2018-08-07 05:52 UTC, Tobotimus approved these changes
Alright, thanks @lionirdeadman for the PR and thanks @mikeshardmind for reviewing. This has really jazzed up the urban command.

A small word of advice @lionirdeadman for any future PR's, try not to change *too much* code unnecessarily. This command has essentially been rewritten from the ground up when looking at the diff - but in retrospect it only aimed to change the output format (not any HTTP request / backend stuff). Changing more than necessary gives the reviewers more work than necessary, hence why this has taken almost 2 months to be merged! However I'll let it slide and I hope you're glad this has finally had its green button pressed :)

2018-08-07 06:33 UTC, merged

2018-08-10 03:24 UTC, lionirdeadman commented
I had already made that code in a cog, I simply modified it slightly for this PR. I'll try not to do that again though if that makes things harder for you guys.

And yeah, I'm pretty happy it got merged. ^^