[V3] --token and --no-instance flags
Cog-Creators/Red-DiscordBot pull request #1872
Opened 2018-06-16 08:30 UTC by retke

### Type

- [ ] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes

This PR brings two new flags to `redbot`:

- The `--token` flag that will run Red with the given token instead of the saved one.
- The `--no-instance` flag that will run Red without any instance. The data will be saved under a `tmp` dir and removed on next restart.

These flags can be combined for testing on Travis CI for example : 

```
python3 -m redbot --no-instance --prefix ! --token $MY_PREFIX
```
That command will run Red without any setup, useful for online automated testing !

2018-06-23 04:28 UTC, Tobotimus requested changes

2018-06-23 04:28 UTC, Tobotimus commented on redbot/core/data_manager.py
> +def save_default_config():
I think this should be named `create_temp_config`, to be clearer about what it does.

2018-06-23 04:28 UTC, Tobotimus commented on redbot/core/cli.py
> +            "and deleted on next restart."
"deleted on next restart" could be interpreted as the next bot restart. I would specify "system restart" to be clearer.

2018-06-23 04:28 UTC, Tobotimus commented on redbot/__main__.py
> +            "Warning: The data will be placed in a temporary folder and removed on next reboot."
Specify "system reboot" here too

2018-06-25 02:39 UTC, Tobotimus requested changes

2018-06-25 02:39 UTC, Tobotimus commented on redbot/__main__.py
> +        save_default_config()
`save_default_config` call needs to be updated

2018-06-25 07:14 UTC, retke commented
Fixed, sorry for that dumb error.

2018-06-25 09:19 UTC, Tobotimus approved these changes

2018-06-25 09:25 UTC, merged