[V3] enforce commands as ours
Cog-Creators/Red-DiscordBot pull request #1971
Opened 2018-08-01 23:30 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Prevents cogs not using our command module from being added (#1880)

### Why in cog load
Rather than do this at the command level, it makes more sense to do at the cog level to prevent the cog from even being partially added.

2018-08-02 08:20 UTC, Jamesp1989SL commented
Forgive me but why is it important to use your system and not the built in ?

2018-08-02 12:05 UTC, Tobotimus commented
@useruser3 It's true that this change (especially being a breaking one) deserves some more explanation. I've opened #1972 to shed some light here and perhaps open up some discussion if necessary.

2018-08-02 12:52 UTC, Tobotimus submitted a review, later dismissed

2018-08-02 12:52 UTC, Tobotimus commented on redbot/core/bot.py
> +            ):
This is just iterating over names of attributes, not the attributes themselves

2018-08-03 16:12 UTC, Redjumpman commented
I think this is a good change. If anything, it helps curb the muscle memory of always using discord.ext. My recommendation is to include a blurb in the docs the reasoning behind why we subclassed `commands.Command`. While on this topic, it might be beneficial to have a section of all Red specific utilities that should be used over standard d.py.

2018-08-03 19:55 UTC, mikeshardmind commented
More on the last point by @redjumpman we have a cog cookiecutter repo which will be documented soon to help alleviate any adjustments like this for new cog creators as well

2018-08-07 20:14 UTC, Redjumpman requested changes
Running this currently results in a `TypeError`

`TypeError: isinstance() arg 2 must be a type or tuple of types.` 

I tried calling `type()` on attr and the return of `getattr` and was able to get it to move past *that* error. I think because when iterating over dir, not everything is returned as a type. 

However, this does get the runtime error to raise, but I think unexpectedly for the one time we need it.

`RuntimeError: redbot.core.core_commands is not using Red's command module, and cannot be added.`

2018-08-08 13:28 UTC, mikeshardmind commented
This should be working all the time now, rather than only in the small toy test case I was using for it before.

2018-08-08 22:59 UTC, Redjumpman commented on redbot/core/bot.py
> +                    f"{cog.__class__.__name} from {cog.__module__},"
`cog.__class__.__name` should be `cog.__class__.__name__` otherwise it raises an attribute error.

2018-08-08 23:03 UTC, Redjumpman requested changes
After the change I marked is fixed, the message reports as `RuntimeError: RussianRoulette from russianroulette.russianroulette, is not using Red's command module, and cannot be add
ed.` I think this could be written a little more clearly as "The RussianRoulette cog in the russianroulette.russianroulette package must use from redbot.core import commands, instead of from discord.ext import commands." Something along those lines.

2018-08-09 01:31 UTC, mikeshardmind commented
@Redjumpman Sorry, I feel like an idiot after that last minute change to give more detailed errors. That's been fixed, and I've added a documentation link to the error, along with a slight tweak to the documentation making it clear that we have additional methods there for red specific things.

2018-08-09 05:41 UTC, Redjumpman commented
Awesome. Everything works great. This is now ready for the next release.

2018-08-09 05:41 UTC, Redjumpman approved these changes

2018-08-09 06:33 UTC, Tobotimus commented
Thanks for reviewing @Redjumpman, but considering this is a breaking change we haven't announced for yet, and beta 19 being due this Sunday August 12, I'm going to block this until after beta 19.

2018-08-13 01:10 UTC, merged