[V3] cleanup after fixes
Cog-Creators/Red-DiscordBot pull request #1980
Opened 2018-08-05 00:53 UTC by mikeshardmind

discord.py's  `HistoryIterator` will make `reverse=True` if it was unset and passed a value for after, this breaks our cleanup logic, and has been changed here to always be `reverse=False`

See #1947

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

2018-08-09 17:10 UTC, aikaterna commented
I've tried this change on a couple bots with no change in the bot's response, cleanup after still returns 0 messages deleted.

2018-08-09 17:46 UTC, mikeshardmind commented
This has been further changed to not break early, and filter the resultant list:

From the discord.py documentation:

```py
reverse: bool
        If set to true, return messages in oldest->newest order. Recommended
        when using with "after" queries with limit over 100, otherwise messages
        will be out of order.
```
This also (potentially) explains the previously inconsistent behavior (though I'm not sure). We couldn't use `reverse=True` with the previous loop strategy and an early break, and `reverse=False` breaking on a message date isn't safe due to this either.

2018-08-11 04:14 UTC, Tobotimus requested changes
This fixes `[p]cleanup after` but breaks all other cleanup commands.

You've also refactored `get_messages_for_deletion` which changes a lot of the behaviour unexpectedly. For example, the idea is to delete `number` of messages, whereas `limit` is the amount of messages to be collected at a time (confusing but we're just fixing one command here, we're not rewriting a cog)

2018-08-11 04:16 UTC, Tobotimus commented
Why not just not use `get_messages_for_deletion` in this command? Just get all messages after the given message (as long as the message is less than 14 days ago), remove pinned ones, and `delete_messages`. Otherwise this helper method is just getting too messy and complicated

2018-08-11 13:38 UTC, mikeshardmind commented
This shouldn't break any other cleanup command and the fact that it did was a fault of me not handling a specific issue with it. This should be fixed in this method, as it was made a static method specifically so that other things can use it too, we don't need to make a special casing for this, just need to handle it correctly.

2018-08-13 06:16 UTC, Tobotimus commented on redbot/cogs/cleanup/cleanup.py
> +        two_weeks_ago = datetime.utcnow() - timedelta(days=14)
I'd rather use `ctx.message.created_at` and do slightly less than 14 days (like 13 days, 23 hours and 55 minutes), since the system time could be out of sync with discord's, `created_at` should be correct since it uses the snowflake to calculate the time.

2018-08-13 10:11 UTC, mikeshardmind commented
Because it's a timedelta, being out of sync on the base time isnt a
concern, and I'd prefer removing ctx as we don't need it, so it opens up
for event based usage without mocking an object.

I agree making it slightly under 14 days makes sense.

On Mon, Aug 13, 2018, 2:16 AM Toby Harradine <notifications@github.com>
wrote:

> *@Tobotimus* commented on this pull request.
> ------------------------------
>
> In redbot/cogs/cleanup/cleanup.py
> <https://github.com/Cog-Creators/Red-DiscordBot/pull/1980#discussion_r209474725>
> :
>
> > -
> -        while not too_old and len(to_delete) < number:
> -            message = None
> -            async for message in channel.history(limit=limit, before=before, after=after):
> -                if (
> -                    (not number or len(to_delete) < number)
> -                    and check(message)
> -                    and (ctx.message.created_at - message.created_at).days < 14
> -                    and (delete_pinned or not message.pinned)
> -                ):
> -                    to_delete.append(message)
> -                elif (ctx.message.created_at - message.created_at).days >= 14:
> -                    too_old = True
> -                    break
> -                elif number and len(to_delete) >= number:
> +        two_weeks_ago = datetime.utcnow() - timedelta(days=14)
>
> I'd rather use ctx.message.created_at and do slightly less than 14 days
> (like 13 days, 23 hours and 55 minutes), since the system time could be out
> of sync with discord's, created_at should be correct since it uses the
> snowflake to calculate the time.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Cog-Creators/Red-DiscordBot/pull/1980#pullrequestreview-145494377>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVA9pLoW7Fpi1u4_Tk0SMepYg8_qkhA0ks5uQRmogaJpZM4VvMOA>
> .
>

2018-08-13 11:35 UTC, mikeshardmind commented
Closing favoring #2013

2018-08-13 11:35 UTC, closed without merging