[v3 cog manager, utils] handle missing cogs correctly, add some helpful algorithms
Cog-Creators/Red-DiscordBot pull request #1989
Opened 2018-08-07 02:10 UTC by calebj

### Type

- [x] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes
For cog loading, only show "cog not found" if the module in question was the one that failed to import. `ImportErrors` within cogs will now show an error as they should.

Also:
- Add a chain deduplicator, benchmarked to be the fastest method
- Add a semaphore-bounded variant of `asyncio.gather` and an async `as_completed`
- And of course, tests for all additions

2018-08-18 06:44 UTC, calebj commented
@Tobotimus rebased.

2018-08-19 09:16 UTC, Tobotimus requested changes
@calebj This PR adds a lot of really nice things, thank you. Just a few little things that can be fixed up and then I think it's good to go.

2018-08-19 09:16 UTC, Tobotimus commented on redbot/core/utils/__init__.py
> +        if type(limit) != int or limit <= 0:
Please use `not isinstance` instead of `type() !=`

2018-08-19 09:16 UTC, Tobotimus commented on redbot/core/utils/__init__.py
> +                []
Not sure what's going on with this `[]` statement, would prefer the use of `pass` or `contextlib.supress`

2018-08-19 09:16 UTC, Tobotimus commented on redbot/core/utils/__init__.py
> +            return await task
Since this `sem_wrapper` is common to the one in `bounded_gather_iter`, it can be moved to the module-level and made private

2018-08-19 09:16 UTC, Tobotimus commented on redbot/core/utils/__init__.py
> +        if type(limit) != int or limit <= 0:
`isinstance` here too

2018-08-19 09:16 UTC, Tobotimus commented on redbot/core/core_commands.py
> +from redbot.core.cog_manager import NoSuchCog
Unused import

2018-08-19 09:16 UTC, Tobotimus commented on redbot/core/cog_manager.py
> +        resolved_paths = deduplicate_iterables(await self.paths())
`paths()` already deduplicates the paths before it returns, so you can remove the call to deduplicate here

2018-08-19 20:43 UTC, calebj commented on redbot/core/utils/__init__.py
> +                []
I think I had logic here for cancelling pending tasks, but I found something better (see the push)

2018-08-20 15:06 UTC, mikeshardmind approved these changes
I'm not seeing any issues with this after the changes made. I'm giving it a :+1:

2018-08-21 01:25 UTC, Tobotimus approved these changes
Awesome. Thanks @calebj and thanks @mikeshardmind for reviewing

2018-08-21 01:26 UTC, merged