[V3 Clanup] refactor internals
Cog-Creators/Red-DiscordBot pull request #2013
Opened 2018-08-13 11:33 UTC by mikeshardmind

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Per discussion with @Tobotimus in discord, an alt to #1980 , #2006 , #2007 since deprecating the current usage shouldn't be necessary. 

This reverts the hotfix #2004 , and refactors `get_messages_for_deletion`. This also adds a note in the doc string about the unsafe usage case no core code uses, and how to handle that case should we care about it in the future, rather than apply any special casing here.

2018-08-19 07:59 UTC, Tobotimus commented
On #1980 you stated this:

> Because it's a timedelta, being out of sync on the base time isnt a concern, and I'd prefer removing ctx as we don't need it, so it opens up for event based usage without mocking an object.

I agree we should remove ctx and I like that change. However discord's time being out of sync with the system time can still cause problems, see this example, simply achieved by changing my PC's system time:
![image](https://user-images.githubusercontent.com/7438501/44306794-365b8b80-a3d9-11e8-969b-b69b3137ea65.png)

To be honest I'm not *too* concerned about it, but it could be resolved by adding an optional `now` parameter to `get_messages_for_deletion` for callers to pass in `ctx.message.created_at`, but falls back to `datetime.utcnow()` if not provided.

2018-08-19 14:59 UTC, mikeshardmind commented
You're right, the timedelta still gets compared to a snowflake, which isn't isolated, I think a better solution is if the first message the bot receives seems more than 2 minutes out of sync (`discord.utils.snowflake_time`, compared to `datetime.utcnow()`) to raise a warning. It shouldn't be a burden for each time sensitive piece of code to handle, but we can still take steps to alert users to that issue.

2018-08-20 18:56 UTC, mikeshardmind commented
@Tobotimus I still don't believe that handling bad system clock times should be handled here, and have opened up #2036 to handle this instead.

2018-08-21 01:31 UTC, Tobotimus requested changes
Will give the tick of approval after this change

2018-08-21 01:31 UTC, Tobotimus commented on redbot/cogs/cleanup/cleanup.py
> +        after = await channel.get_message(message_id)
This still needs to be in a try/except

2018-08-21 02:30 UTC, Tobotimus approved these changes

2018-08-21 02:31 UTC, merged