[V3 Audio] Local playback
Cog-Creators/Red-DiscordBot pull request #2097
Opened 2018-09-04 04:04 UTC by aikaterna

### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes
This builds on top of #2077 and could be used in favor of it.

Filetype support: .mp3, .flac, .ogg

Local tracks can be queued a few ways:

- `[p]play localtracks/foldername/song_to_play.mp3`
- `[p]local play` (interactive)
- `[p]local folder` (interactive, queues entire localtracks folder)
- `[p]local search` (interactive, queues the user-picked track via menu)

If you're looking to test this as an existing user:

- Tracks should go in a localtracks folder under the audio data directory. Place tracks inside an additional subfolder. You can have as many subfolders under localtracks as you want, however audio only looks one folder deep for tracks.

For example:

data_directory/cogs/Audio/localtracks/Album Folder Name/Artist - Track.mp3

data_directory/cogs/Audio/localtracks/Another Great Album/Another Artist - Another Track.mp3

are both valid paths for tracks.

- Replace the lavalink.jar in your audio data directory with build no. 584 (https://ci.fredboat.com/repository/download/Lavalink_Build/4825:id/Lavalink.jar?guest=1)
- Change `local: false` in the application.yml file in audio's data path to `true`.
- If your files return "Nothing found.", check your error.log or the lavalink.log in the data directory to see if it was an encoding error.

General error reporting in Discord is disabled for local tracks. Lavalink is not best-suited for local track playback and can complain at the end of every mp3 file but play the entire thing, for example.

Something to be considered before merging: There should be a way to determine if someone has an existing lavalink.jar and application.yml and be able to overwrite them both, or set them to download & overwrite by default on the release this is included in.

2018-09-06 15:20 UTC, Tobotimus commented on redbot/cogs/audio/audio.py
> +        Use [p]queue search <search terms> to search the queue."""
Literally my only qualm with this PR right now, could you add a linebreak in this help message? :D

2018-09-07 19:47 UTC, mikeshardmind requested changes
Seems to work fine for the features added. Ran into a small issue at first testing since this was missing bugfixes added since work started, but just merged those locally and was fine.

I did notice something that appears to be by design(especially with comments in the PR description), but I think changing it is preferable.

While I understand not traversing directories infinitely in an interactive menu, It would be nice to be able to specify a specific path contained in local tracks to play from, or a specific file and have it work correctly in any amount of nesting. I have audio files in my music directory as 
```
Music Folder/Artist Name/Album Name/track number - Trackname.extension
```
I can't just symlink this folder to where localtracks is expected due to this limitation on directory traversal.

2018-09-07 20:15 UTC, aikaterna commented
That's planned/intended. Just not in this PR yet.

2018-09-07 20:40 UTC, mikeshardmind submitted a review, later dismissed
Modifying prior review to approving since the changes requested are planned improvement in future PR instead, and the changes requested do not necessarily need to happen for the rest of this PR to be valid.

2018-09-07 20:42 UTC, mikeshardmind commented
I'm not saying it should support infinite folder depth, but I do think it should support more than just 1 if passed the path directly, and not using the interactive menu.

2018-09-09 13:02 UTC, Tobotimus approved these changes

2018-09-09 13:02 UTC, merged