Permissions redesign
Cog-Creators/Red-DiscordBot pull request #2149
Opened 2018-09-25 13:47 UTC by Tobotimus

This isn't really ready for review yet but I thought people might be interested in seeing it. I plan on going over what's changed (and what removals will need to be factored back in), doing more testing and adding some unit tests.

2018-09-26 16:47 UTC, mikeshardmind commented on redbot/core/utils/chat_formatting.py
> +        >>>humanized_list(["One", "Two", "Three"])
This doctest looks like it isn't right....

`humanize` != `humanized`

2018-09-27 06:01 UTC, Tobotimus commented
This PR should now be ready for the first round of reviews! I've updated the header with the details. Sorry if I've missed some stuff.

2018-09-27 10:22 UTC, mikeshardmind commented
I'll note on the removal of `__permissions_check_before` and `__permissions_check_after`, that I don't think getting rid of them in entirety is a good thing. Getting rid of the after should be mostly fine, but the before did serve an important purpose. 

Neither the previous iteration or permissions, nor this one can properly support a negative condition. (i.e. deny to anyone _not_ is a specific group, without modifying the rule for that specific group to do it ). An example of where this can be problematic actually shows up in how the docs are being modified to hedge the actual intent behind locking audio, and how using this method will actually prevent a discord server owner (not bot owner) from further restricting those commands. These extra hooks allowed for quick extra rules to be added for people with such cases, without needing to design an entire permission model to make that possible.

2018-09-30 08:01 UTC, mikeshardmind requested changes
Setting via ACL appears to be working as intended. I've not found any major issues. I have found an inability to set rules via non-acl methods, (cause: converter, see comment).

This is a much more sustainable solution than before and seems to be performing well. With a fix for the converters that are problematic, this should be ready to go.

2018-09-30 08:01 UTC, mikeshardmind commented on redbot/core/commands/requires.py
> +GlobalPermissionModel = Union[
This is being used as a union converter in a couple places, which isn't safe. There's no such converter for guild, breaking every attempt to add a rule not via acl, and also the error from this is not user facing (traceback in console, but silent bot response).

I'd suggest adding a guild converter in our subclassed commands to accommodate this.

2018-09-30 23:49 UTC, mikeshardmind approved these changes
All changes needed have been made.

2018-10-01 03:19 UTC, merged