[V3 Mod] Remove tempban from data after unbanning
Cog-Creators/Red-DiscordBot pull request #2161
Opened 2018-09-30 01:20 UTC by zephyrkul

### Type

- [X] Bugfix

### Description of the changes
Resolves #2160 
Also resolves another issue I found where the bot will error out when getting the guild's invites when it doesn't have the Manage Server permission.

2018-09-30 05:09 UTC, Tobotimus requested changes
Thanks for this PR. Right idea, just one thing needs to be fixed.

2018-09-30 05:09 UTC, Tobotimus commented on redbot/cogs/mod/mod.py
> +                                guild_tempbans.pop(i)
If two tempbans are finished in this same `for` loop, the 2nd one will pop the wrong one off the list. After the first one is removed, elements in `guild_tempbans` are shifted meaning `i, uid` becomes misaligned with it. Best to use `.remove(uid)`, no need to enumerate (tempting I know due to extra performance of `.pop(i)`)

2018-09-30 14:44 UTC, zephyrkul commented
Changes addressed, thanks for the sharp eye.

2018-10-01 04:15 UTC, Tobotimus approved these changes
Thanks for this PR @zephyrkul :heart:

2018-10-01 04:15 UTC, merged