[CustomCom] Better display for [p]cc list
Cog-Creators/Red-DiscordBot pull request #2215
Opened 2018-10-09 10:54 UTC by Tobotimus

Uses an menu, optionally embedded with respect to the embed settings, for scrolling through the custom command list, each cc with a ~50 character preview. Format is purposefully similar to the help menu.

Resolves #2104.

2018-10-14 23:35 UTC, mikeshardmind requested changes
I don't think these changes are of the quality we should push for. It may make the list cleaner, but significantly less functional. If we need an RC3 to accomplish this, so be it in my mind.

2018-10-14 23:35 UTC, mikeshardmind commented on redbot/cogs/customcom/customcom.py
> +                result = result[:49] + "..."
I don't like this pagification method with embed. I think this is a good case for field based pagination to allow new lines in previews. While this method is certainly cleaner looking than the previous one, It's also less functional for many purposes.

As an example, I have many CCs in a codiing discord utilizing code blocks. The only thing I get is the language specifier and escaped backticks for those.

2018-10-15 20:50 UTC, Twentysix26 commented
I like it, certainly leagues better than the previous form.  
Maybe the issue with the code blocks could be resolved by replacing the new lines characters in the previews with a space.
Minor nitpick and maybe up to personal preference: I think it may look better displayed on two lines for each command
```
cmd1
preview
cmd2
preview
(...)
```

2018-10-15 20:53 UTC, mikeshardmind approved these changes
After discussion in discord, I'm modifying my review to approval.

If nobody else does, I'll eventually be looking to add an additional way to browse CCs myself later with more detail, but this shouldn't block unbreaking the current behavior for.

2018-10-15 21:03 UTC, Tobotimus commented
@Twentysix26 I actually hadn't thought of replacing newlines with spaces, I will actually give that a go. For displaying the preview on the next line, I think I personally prefer the current method for similarity with the help menu, but I will do it and post some screenshots FTR.

2018-10-15 21:33 UTC, Tobotimus commented
### Screenshots
<h4>
<details>
  <summary>Original PR style embed (click me)</summary>
  <img src=https://user-images.githubusercontent.com/7438501/46979408-44016900-d11d-11e8-9453-8bfd4c4c45af.png />
</details>
</h4>

<h4>
<details>
  <summary>With newlines replaced with spaces</summary>
  <img src=https://user-images.githubusercontent.com/7438501/46979638-d43fae00-d11d-11e8-8a9e-0e3f5a08280a.png />
</details>
</h4>

<h4>
<details>
  <summary>With preview on following line</summary>
  <img src=https://user-images.githubusercontent.com/7438501/46979669-e6b9e780-d11d-11e8-86d3-5a21b16ca9e4.png />
</details>
</h4>

I prefer the 2nd one, so I'm gonna go with it :smiley:

2018-10-15 21:39 UTC, merged