[V3 Audio] Restrict toggle for commercial sites
Cog-Creators/Red-DiscordBot pull request #2245
Opened 2018-10-16 03:05 UTC by aikaterna

### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes
Added [p]audioset restrict. This command will be True by default, and will restrict audio usage to main commercial sites like YouTube, Soundcloud, Vimeo, Mixer, Bandcamp and Twitch. It's an owner-only command, so if the bot owner wishes to allow http links, http streams, or other valid links to play that are not commercially-based, they will need to switch this toggle to False. Resolves #2244.

2018-10-17 02:00 UTC, mikeshardmind requested changes
Outside of how the urls are being matched here, this is working and fine. Some changes are needed (direction was already briefly discussed in discord)

2018-10-17 02:00 UTC, mikeshardmind commented on redbot/cogs/audio/audio.py
> +        site_check = []
This solution is not robust. A file hosted at `twitch.compromising-link.xyz/phishy-file.mp3` would be allowed.

2018-10-17 02:00 UTC, mikeshardmind commented on redbot/cogs/audio/audio.py
> +                site_check.append(True)
And on matching a solution that was, this can just be `return True` here, and everything else below it in the function would be omitable

2018-11-23 22:27 UTC, mikeshardmind approved these changes
Seems to work properly, giving this a :+1:

2018-12-13 17:29 UTC, Kowlin approved these changes

2018-12-13 17:31 UTC, merged