New Trivia
Cog-Creators/Red-DiscordBot pull request #2265
Opened 2018-10-23 17:09 UTC by MiniJennJenn

### Type

- [ ] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes

Updated: 
 - leagueoflegends
 - leagueults
New: 
 - games (thanks bobloy for submitting boardgames but since most of the questions weren't "boardgames" I combined it with the pre-existing games list)
 - sports (some of the questions from the aforementioned boardgames list went into this category as well)
 - r6seige (thanks MHLoppy)

2018-10-24 02:25 UTC, palmtree5 commented
I'm noticing there's curly quotes in at least the games trivia list atm

2018-10-24 03:06 UTC, MiniJennJenn commented
Could you give me an example of where? I don't see any.

2018-10-24 03:07 UTC, palmtree5 commented on redbot/cogs/trivia/data/lists/games.yaml
> +In "Twisted Metal 2″, what does Krista Sparks drive?:
Here

2019-03-16 20:50 UTC, hatred2k commented
Not sure if this is the correct issue, however, I've updated the sports trivia to accommodate for the most recent championships as well as I've added a couple of new ones.
V3: [sports.yaml](http://hatred2k.com/assets/sports.yaml)

2020-06-26 11:19 UTC, Drapersniper requested changes
@MiniJennJenn  could you please fix the conflicts so we can get this reviewed?

2020-06-26 19:10 UTC, MiniJennJenn commented
So, I can't actually access that link from hatred.

2020-06-26 22:16 UTC, hatred2k commented
> So, I can't actually access that link from hatred.

Updated version **[here](https://pastebin.com/raw/RcPZ02A7)**.

2020-06-29 14:18 UTC, MiniJennJenn commented
Okay. The rest of this is fine for commit. I think we just commit this one and I'll create a new PR for hatred's newer sports trivia version.

2020-06-29 14:26 UTC, MiniJennJenn commented
@hatred2k In the future, if you're going to update your trivia/add more, I suggest updating from the one we have. I had fixed it in the past to resolve a number of typos. Since your version doesn't have those fixes, I'll need to adjust accordingly.

2020-06-29 15:45 UTC, MiniJennJenn commented
Closing. All fixed in #4026

2020-06-29 15:45 UTC, closed without merging