[V3 Core] Graceful shutdown when SIGTERM si received
Cog-Creators/Red-DiscordBot pull request #2286
Opened 2018-11-03 11:59 UTC by retke

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

When the bot receives SIGTERM, it will close the connexion (with `bot.shutdown`) correctly. Without this handler, the process is killed and the gateway is stuck, with the bot still connected for a while. Using `sudo systemctl stop red.service <instance>` is now safe to correctly shutdown the bot.

What it looks like in the logs:
```
laggron@discordbots:~/RedDB-fork$ sudo systemctl stop redfork-discordbot.service
laggron@discordbots:~/RedDB-fork$ systemctl status redfork-discordbot.service
● redfork-discordbot.service - Red-DiscordBotV3:Red
   Loaded: loaded (/etc/systemd/system/redfork-discordbot.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

[...]
Nov 03 11:50:28 discordbots pipenv[12401]: [03/11/2018 11:50] INFO __main__ sigterm_handler 115: SIGTERM received. Quitting...
Nov 03 11:50:28 discordbots pipenv[12401]: [03/11/2018 11:50] INFO manager shutdown_lavalink_server 115: Shutting down lavalink server.
```

2018-11-04 14:57 UTC, retke commented
Note: this was only tested on Ubutnu 18.10 with systemdaemon, it should work the same with upstart, but I don't know how Windows handle this, so this might need testing on this OS (I don't have Red installed on Win)

2019-01-20 22:29 UTC, Tobotimus requested changes
Thanks for adding this. Just need a few changes and it should be good to go.

2019-01-20 22:29 UTC, Tobotimus commented on docs/autostart_systemd.rst
> +you can stop the service, still by adding the instance name after the **@**:
Grammar is slightly off here, maybe just say

> ...or you can stop the service with the following command:

2019-01-20 22:29 UTC, Tobotimus commented on redbot/__main__.py
> +    loop.add_signal_handler(SIGTERM, lambda: asyncio.ensure_future(sigterm_handler(red, log)))
This method is not implemented on non-unix systems, so this needs to be guarded under an `if os.name == "posix"` condition.

2019-01-22 23:26 UTC, Tobotimus approved these changes

2019-01-22 23:28 UTC, merged