[Mod] Fixed not handling of nicknames that are too long.
Cog-Creators/Red-DiscordBot pull request #2311
Opened 2018-11-24 20:57 UTC by Kowlin

### Type

- [x] Bugfix

### Description of the changes

Fixed Mod not handling nicknames that exceed 32 characters.

2018-12-02 22:22 UTC, mikeshardmind requested changes
This still isn't completely sufficient for preventig a traceback with this. see <https://discordapp.com/developers/docs/resources/user#usernames-and-nicknames>, should wrap in a try/except additionally.

2018-12-14 03:04 UTC, mikeshardmind requested changes

2018-12-14 03:04 UTC, mikeshardmind commented on redbot/cogs/mod/mod.py
> +            except discord.Forbidden:
I'd prefer doing a hierarchy and perm check before the API call here.

The other error still needs to be caught for cases where the nick limitation is a result of discord not sharing all invalid nick parameters.

2018-12-16 00:08 UTC, Tobotimus approved these changes

2018-12-16 00:21 UTC, merged