[V3 Audio] Sort local files
Cog-Creators/Red-DiscordBot pull request #2358
Opened 2019-01-05 20:59 UTC by retke

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

When using the `[p]local` command, the files were given in a weird order (directly returned from `os.listdir()`) and it was a problem, especially with the playlists whose files are indexed. This PR just add a `sorted()` where the bot must fetch the local tracks.

2019-01-10 10:28 UTC, Nodja commented
I modified my code similarly to this and was gonna make a pull request, but I saw this here.

The only change I would make would be to use `sorted([], key=lambda s: s.casefold())` so that the case doesn't affect file order.

2019-01-28 23:02 UTC, Tobotimus requested changes
Just a tiny change suggested :smile:

Also I agree with @Nodja that `casefold` should be used.

2019-01-28 23:02 UTC, Tobotimus commented on redbot/cogs/audio/audio.py
> +        )
You can use `sorted` directly on a generator expression, so you can remove the square brackets:
```diff
- folder_list = sorted(
-     [
-         f
-         for f in os.listdir(current_folder)
-         if (f.lower().endswith(allowed_files)) and (os.path.isfile(current_folder + f))
-     ]
- )
+ folder_list = sorted(
+     f
+     for f in os.listdir(current_folder)
+     if (f.lower().endswith(allowed_files)) and (os.path.isfile(current_folder + f))
+ )
```

2019-01-31 17:22 UTC, retke commented on redbot/cogs/audio/audio.py
> +        )
👍

2019-02-27 05:21 UTC, Tobotimus approved these changes

2019-02-27 05:22 UTC, merged