[Mod] Allow admin to choose amount of repeats for "deleterepeats"
Cog-Creators/Red-DiscordBot pull request #2437
Opened 2019-02-09 03:48 UTC by jack1142

### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes
This allows admin to set how many times message has to be repeated before `deleterepeats` removes it. (resolves #2267)
To stay compatible with previous versions I added check which will change the configuration to new format (it gets executed, on every message though, it might be better to iterate with that check through whole config on init, I can change that if needed)

2019-04-21 21:55 UTC, jack1142 commented
There was a big change in structure of Mod since I created this PR, so it was easier to just apply it on V3/develop again, everything should be okay now 👍

2019-04-21 22:00 UTC, mikeshardmind requested changes

2019-04-21 22:00 UTC, mikeshardmind commented on redbot/cogs/mod/settings.py
> +                repeats = min(max(repeats, 2), 20)  # Enforces the repeat limits
I'd prefer checking the userinput to changing it for them here.

2019-04-21 22:18 UTC, jack1142 commented on redbot/cogs/mod/settings.py
> +                repeats = min(max(repeats, 2), 20)  # Enforces the repeat limits
Other settings in Mod cog suggested me that this the way you want it to be, but I can change that, if you want.

2019-04-22 01:32 UTC, jack1142 commented
I changed what Sinbad asked for.

2019-04-23 02:26 UTC, mikeshardmind requested changes

2019-04-23 02:26 UTC, mikeshardmind commented on redbot/cogs/mod/settings.py
> +            self.cache.pop(guild.id, None)  # remove cache with old repeat limits
Last change request from me here.

Move this to after verifying a valid amount, and change it to create a new deque from the existing one.

for example:

```py
old_deque = deque([1,2,3], maxlen=4)
new_deque = deque(old_deque, maxlen=2)
```

2019-04-23 03:19 UTC, jack1142 commented
Fixed what you asked for and also changed check to only fetch config, if guild's dict is not in cache yet.

2019-04-23 13:52 UTC, mikeshardmind approved these changes

2019-04-23 14:01 UTC, merged