Refactor CogManager and extension loading
Cog-Creators/Red-DiscordBot pull request #2446
Opened 2019-02-12 22:53 UTC by Tobotimus

This kicked off with me realising our use of `Loader.load_module()` as a hacky way to import modules from random locations is deprecated. Looking closer, I realised there were a couple of smelly things here which could be cleaned up. Here's what's changed:
- Paths in CogManager are now inserted into `redbot.cogs.__path__`. This means to import any cog, including an external cog, the import path would be `redbot.cogs.cog_to_import`. It makes the rest of the logic really straightforward. The only side effect is, to differentiate core cogs from external cogs, we now need to look at a module's `__file__` rather than its `__module__` or `__package__`.
- Importing cog modules is now done with `importlib.import_module` - this is a high-level function which allows us to delegate all of the nitty gritty import logic to Python itself, and it should be much more reliable. We're also no longer dealing with `ModuleSpec` objects, we just go straight from cog name to module.
- Since lazy importing is used for cog modules, and because big packages can take quite a long time to import, whenever we're importing a cog module which is not already in `sys.modules`, we do it in a ThreadPoolExecutor to make it non-blocking.
- We're now using `importlib.reload` to reload modules like a good boy. This is done from the bottom-up, twice, to make sure *most* internal imports in the package are updated. Some old imports could hang around if people do lazy relative importing at the module level.
- Packages are no longer deleted from `sys.modules` in `Red.unload_extension()`. This was really smelly and, in my opinion, unnecessary. It would have resulted in a miniscule memory saving at best, although I'm pretty sure even after doing this the module would still remain in memory, as Python keeps a reference to imported modules in C code as well.
- `Red.load_extension` can take either a module, or a straight name. This means loading a package is as simple as `Red.load_extension(package_name)`, no more needing to know what method of `CogManager` to use.
- Some internal documentation was added in a module docstring of `redbot.core.cog_manager`.

2019-02-18 05:38 UTC, calebj commented
I haven't noticed any issues so far in using this, so it seems good. However, I would like to see some more widespread ~~battlefield~~ testing with a variety of third party cogs and external modules before giving my :+1:.

2019-07-04 09:20 UTC, Tobotimus commented
This is ready for review again and will be targetting 3.2

2019-11-08 15:01 UTC, mikeshardmind commented
I still have a few concerns with regard to using `importlib.reload` in this manner, but I also haven't seen this break any cogs which I use in any way which wouldn't already be broken with the current reload strategy. I'd like to do another pass over this later before merging it, but it should make the reload behavior of cogs more consistent from an end user standpoint at least.

2019-11-09 17:24 UTC, mikeshardmind requested changes

2019-11-09 17:24 UTC, mikeshardmind commented on redbot/core/bot.py
> +            module: types.ModuleType = self.cog_mgr.load_cog_module(module)
```suggestion
            module: types.ModuleType = self._cog_mgr.load_cog_module(module)
```

2019-11-09 17:24 UTC, mikeshardmind commented on redbot/core/cog_manager.py
> +        await ctx.bot.cog_mgr.reorder_path(to_move, to)
```suggestion
        await ctx.bot._cog_mgr.reorder_path(to_move, to)
```

2019-11-09 17:24 UTC, mikeshardmind commented on redbot/core/core_commands.py
> +                module = bot.cog_mgr.load_cog_module(name)
```suggestion
                module = bot._cog_mgr.load_cog_module(name)
```

2019-11-09 17:24 UTC, mikeshardmind commented on redbot/core/core_commands.py
> +                module = bot.cog_mgr.reload(module)
```suggestion
                module = bot._cog_mgr.reload(module)
```

2019-11-09 17:24 UTC, mikeshardmind commented on redbot/core/core_commands.py
> +        module = self.bot.cog_mgr.reload(module)
```suggestion
        module = self.bot._cog_mgr.reload(module)
```

2019-11-09 17:24 UTC, mikeshardmind commented on redbot/core/core_commands.py
> +        module = self.bot.cog_mgr.load_cog_module(cog_name)
```suggestion
        module = self.bot._cog_mgr.load_cog_module(cog_name)
```

2020-07-06 18:42 UTC, Drapersniper commented
@Tobotimus is this something you are still actively working on or have you dropped this PR. Unsure whether you are currently working on this locally and just haven't pushed any commits.

2020-07-23 09:25 UTC, Drapersniper commented
Closing due to innactivity.

2020-07-23 09:25 UTC, closed without merging