[V3 Audio] Seek command can now seek to position
Cog-Creators/Red-DiscordBot pull request #2470
Opened 2019-02-19 18:59 UTC by aikaterna

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
* Seek can now seek to a specific position, formatted like 00:00:00 or 00:00. Using negative or positive ints still functions the same as previously and will seek ahead or behind by that value instead.
* This PR requires the _time_convert func added in #2465 and should be merged after that one.

2019-03-03 00:09 UTC, TrustyJAID requested changes

2019-03-03 00:09 UTC, TrustyJAID commented on redbot/cogs/audio/audio.py
> +        """Seek ahead or behind on a track by seconds or a to a specific time."""
Might be good to include similar documentation here as #2465 for how to skip to a specific time in the track.

2019-03-09 01:27 UTC, TrustyJAID approved these changes

2019-03-10 07:25 UTC, Tobotimus approved these changes

2019-03-10 07:27 UTC, merged