[V3 Config] Require custom group initialization before usage
Cog-Creators/Red-DiscordBot pull request #2545
Opened 2019-04-03 13:51 UTC by tekulvw

…to disk

### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes
This is a breaking change when using Config's custom groups feature. In order to safely and effectively convert data between data backends we must know how to interpret custom groups. Prior to this PR that was impossible because we wouldn't know the length of the custom group's primary key. The primary key is the list of identifiers passed into `Config.custom()`.

This PR adds the `Config.init_custom()` method which allows you to register the length of each custom group's primary key. This method must be called before `register_custom()` or `custom()`. The information stored in config is written to disk the first time a get/set/clear happens.

2019-04-04 01:23 UTC, tekulvw commented
Information will not be stored to disk in this PR. I need to make another PR to change `bot.add_cog` into a coroutine first.

2019-04-05 00:01 UTC, mikeshardmind requested changes
Config objects need to be singletons with this change. The design direction this is going will require it here for some sanity instead of just at the driver.

Modification to object creation preferred over just the factory methods from me on this.

This also breaks the entire dataconverter cog. I'm fine with the removal of that cog until it can be rewritten in a more appropriate manner for future use.

2019-04-05 01:41 UTC, mikeshardmind approved these changes
Works as intended. Is breaking. Needs an announcement in #v3-burndown .

2019-04-05 01:44 UTC, Kowlin approved these changes

2019-04-05 01:47 UTC, merged