[i18n] Fix some missing i18n strings in the whole bot
Cog-Creators/Red-DiscordBot pull request #2633
Opened 2019-04-29 20:31 UTC by PredaaA

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
This PR fix some other i18n strings was missing in the whole bot, I think this time it will be done.

Note: [streamtypes.py](https://github.com/PredaaA/Red-DiscordBot/blob/patch-3/redbot/cogs/streams/streamtypes.py) have also things that can be translated, all embeds. But I am not sure how to implement i18n since there's not just one class in this file.

2019-04-30 14:36 UTC, mikeshardmind requested changes

2019-04-30 14:36 UTC, mikeshardmind commented on redbot/cogs/general/general.py
> +            return await ctx.send(_("This isn't a valid option. Try rock, paper, or scissors."))
This won't work. We don't actually want `rock` `paper` or `scissors` to be translated.

2019-04-30 15:06 UTC, PredaaA commented on redbot/cogs/general/general.py
> +            return await ctx.send(_("This isn't a valid option. Try rock, paper, or scissors."))
Yes, I forgot this little detail. Fixed.

2019-04-30 15:59 UTC, mikeshardmind submitted a review, later dismissed

2019-06-29 15:00 UTC, Tobotimus approved these changes

2019-06-29 15:13 UTC, merged