[Downloader] Fix problem with copying directory tree.
Cog-Creators/Red-DiscordBot pull request #2690
Opened 2019-05-16 14:43 UTC by jack1142

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
fix #2685
This might not be perfect solution as we have to clear `distutils.dir_util._path_created` dict, but it seems like the best way to fix this, if we don't want to reimplement `distutils.dir_util.copy_tree`.

2019-05-22 00:08 UTC, mikeshardmind commented
I'd like to explore this a bit more before using this particular fix to ensure resetting `distutils.dir_util._path_created` won't have extra side effects which aren't acceptable.

Additionally, shutil.copy_tree doesn't directly call any platform specific code, and we can copy the 3.8 implementation of it into `redbot.core.utils` with proper attribution if this fix does have undesirable side effects.

(see [bpo-20849](https://github.com/python/cpython/commit/9e00d9e88fbf943987e4771c753f5ca8f794103e) for more details)

2019-05-22 02:01 UTC, Tobotimus commented
When moving a directory tree in Python comes down to messing with the internals of distutils... Makes me wonder whether it's worth looking elsewhere (3rd party) or implementing it ourselves

2019-05-22 05:20 UTC, jack1142 commented
Okay, while I understand why we may not want to mess with internals just to copy directory directory tree, it seemed as a better option than having to copy updated implementation of shutil.copy_tree from Python 3.8 just for 

Before crating this PR I checked to make sure, that `_path_created` is not used for anything else than checking if path was created previously by dir_util and that variable is only used in 2 places: `mkpath` which check if path was created before trying to create it again (which is only put there to eliminate redundant calls and that will still happen as we only clear `_path_created` before using `copy_tree`) and `remove_tree` which removes paths from this cache after removing a particular directory.

Not sure if it makes it any better for you, that even Python's tests clear `_path_created` in tests running multiple times to make sure, that dir_util's cache won't cause any issues.
https://github.com/python/cpython/blob/3.7/Lib/test/libregrtest/refleak.py#L201

2019-05-23 00:06 UTC, mikeshardmind requested changes
I'm not super happy about this, but I can't find any reason for which this is unsafe to use.

I'd prefer if you added a comment linking to the issue *and* this PR next to that line prior to merge, but I'm fine with this being the solution used.

2019-05-23 06:48 UTC, jack1142 commented
Is this fine?
```
# clear copy_tree's cache to make sure missing directories are created (GH-2690)
```

2019-05-23 06:50 UTC, mikeshardmind commented
Yep, just something to prevent people from scratching heads at this later

2019-05-23 07:04 UTC, jack1142 commented
Okay, I added it.

2019-05-23 07:08 UTC, mikeshardmind approved these changes

2019-05-23 07:08 UTC, merged