[Config] Adds more channel type specificity
Cog-Creators/Red-DiscordBot pull request #2694
Opened 2019-05-17 02:51 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

This is breaking, despite a comment about not changing something in it to prevent (other) breakage.

This should not be merged prior to the cut off for micro version in the 3.1.x series.

2019-06-29 14:47 UTC, Tobotimus requested changes

2019-06-29 14:47 UTC, Tobotimus commented on redbot/core/config.py
> +        return await self._all_from_scope(self.VOICE_CHANNEL)
```suggestion
        return await self._all_from_scope(self.TEXT_CHANNEL)
```

2019-06-29 14:48 UTC, Tobotimus requested changes

2019-06-29 14:48 UTC, Tobotimus commented on redbot/core/config.py
> +        channel : `discord.TextChannel`
```suggestion
        channel : `discord.CategoryChannel`
```

2019-09-02 00:05 UTC, mikeshardmind commented
Closing this, for now. Will be easier to re-implement when time is correct with the other large changes to config.

2019-09-02 00:05 UTC, closed without merging