[Core] Fix user output on cog load/reload
Cog-Creators/Red-DiscordBot pull request #2767
Opened 2019-06-11 12:51 UTC by mikeshardmind

### Type

- [X] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
  - Properly fixes the load/reload exception handling
  - Fixes some i18n use here to not make assumptions about other
  languages pluralization rules.

2019-06-13 20:50 UTC, Flame442 requested changes

2019-06-13 20:50 UTC, Flame442 commented on redbot/core/core_commands.py
> +                    inline(not_found[0])
This throws a key error because `pack` is not found in the `.format()`

2019-06-13 20:50 UTC, Flame442 commented on redbot/core/core_commands.py
> +                ).format(humanize_list([inline(package) for package in not_found]))
This throws a key error because `packs` is not found in the `.format()`

2019-06-13 20:50 UTC, Flame442 commented on redbot/core/core_commands.py
> +                ).format(inline(failed[0]))
This throws a key error because `packs` is not found in the `.format()`

2019-06-13 20:50 UTC, Flame442 commented on redbot/core/core_commands.py
> +                    inline(not_found[0])
This throws a key error because `pack` is not found in the `.format()`

2019-06-13 20:50 UTC, Flame442 commented on redbot/core/core_commands.py
> +                    "The following packages were not found in any cog path: {packs}"
This throws a key error because `packs` is not found in the `.format()`

2019-06-13 22:34 UTC, Flame442 submitted a review, later dismissed

2019-06-29 14:36 UTC, Tobotimus submitted a review, later dismissed

2019-06-29 16:14 UTC, Tobotimus approved these changes

2019-06-29 16:16 UTC, merged