[Audio] One PR to rule them all, One PR to find them, One PR to bring them all, and in the darkness bind them (one-in-all pr)
Cog-Creators/Red-DiscordBot pull request #2904
Opened 2019-07-26 11:26 UTC by Drapersniper

### Type

- [x] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes

After discussing with @aikaterna she prefer everything in one PR so that conflicts and reviewing cross interaction and testing can be done more easily.

Note this is very much a draft and code here is likely to change. Hopping to get this done in 1-2 weeks, if you have any suggestions or ideas, just shout in here or in #2494 

This PR will superseded #2861 and #2890, in addition to those 2 I done a lot more work on other key areas of audio.

- **Bug Fixes**

1. Playlist save fix (will overwrite playlists with no confirmation)
    - Playlist are now stored by ID (`ctx.message.id`), this allows multiple playlist with the same name
2. `[p]playlist remove` now converts a playlist to a custom one if it was created from a link
    - Before this part of the code was always ignored
3. Delay of 2 seconds added for every lavalink query done after the first (only applicable for enqueing local track albums or spotify playlists/albums), this is to ensure the `LoadType(data["loadType"])` error that happen when the API gets rate limited.

- **Done**

1. Moved Playlist to a custom scope, there are 3 new custom scopes
    - `Global` Which only Bot Owner have edit access
    - `Guild` Which bot owners, DJ, Mods, Admins, Guild Owners, Authors have access to
    - `User` which bot owner and playlist author have access
2.  Playlists are now stored in `Playlist` object
3. Created API's to easily access/modify/delete Playlists based on the ModLog structure
4. Wrote a function that converts the old config schema to the new versions with the 
5. Update all playlist commands to use the new `Playlist` objects
6. Rename Playlists command `[p]playlist rename` added
7. V3 now have their own playlist schema that has song information, so when a playlist is uploaded no song information will need to be re-fetched, keeping support for V2 playlists
8. Making a dynamic converter for the Playlist ID, so that users can give the bot either the Playlist ID or the playlist name, it will prompt user to select one if multiple matches are found
9. Added `[p]playlist update` (If a playlist has a playlist url saved (non-custom playlist)) will now update the playlist to the latest tracks available.
10.  Child folders within "album" folders in localtracks (#270)
11. Implemented `LocalPath` and `Query` data classes to handle queries and paths.
12. Playlist now start playing after first song is loaded instead of waiting for the full playlist to load
13. Lavalink response is now cacheable as part of #2890 (Significantly faster loading, 2.7K songs went from 1+ hours to 1-2 minutes on follow up enqueues)
14. As part of the changes added by  #2890 Users are no longer able to enqueue any tracks while a playlist is enqueuing, this is to ensure queue order persists. But since songs now start being played the moment they are loaded, This doesn't have a major negative impact to users.

### Work started:
- [ ]  support timestamps in urls, like https://youtu.be/8CdcCD5V-d8?t=31
- [ ]  add more comments to explain things that are not clear
- [ ]   url or keyword blacklist 

### Considering:
- [ ] Subclassing Player method from lavalink (or making a PR over there)
- [ ]  autojoin/bind (a command to bind the bot to a text channel and a voice channel for the duration of the audio session), also setting a lock on the audio set notify channel via this method 
- [ ]  replay queue history by day (#366) 
- [ ]  remove multiple songs at once 
- [ ] queue: move songs up and down the list by number of songs (#621)
- [ ] remove multiple songs at once *
- [ ] Make playlist remember where it was stopped? (#1544)
- [ ] queue doesn't reflect actual order of songs when shuffle is applied because shuffle is random choice out of the queue
- [ ] Going over #623 so some features in case we missed any good ones

2019-07-31 10:04 UTC, Drapersniper commented
So I think it may be ready for review ....
I'm truly sorry for all the reviewers and QA's ... On the up side the code works ... on the downside i probably missed a fair amount of docs if you notice anything obvious don't hesitate to shout

2019-08-02 16:37 UTC, mikeshardmind commented
if you need.changes for red-lavalink, PR those and cross link it here. We cant handle the red-lavalink dep the way you have it here.

2019-08-02 16:58 UTC, Drapersniper commented
> if you need.changes for red-lavalink, PR those and cross link it here. We cant handle the red-lavalink dep the way you have it here.

Yeah I know this was just for testing I fully intend to revert it to the correct way before this is merged

2019-09-26 18:00 UTC, aikaterna requested changes
——
Run playlist download (there were multiple server playlists named the same thing as the query)
Get the file
The timeout replies with “Too many matches found and you did not select which one you wanted.” anyway, when it should return when the file is sent
——
Used the generated, downloaded file in playlist upload
Received:
```
[2019-09-26 10:12:34] [ERROR] red: ValueError
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 4782, in _playlist_upload
    scope_data=(scope, author, guild),
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/context.py", line 132, in invoke
    ret = await command.callback(*arguments, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 4353, in _playlist_save
    scope, author, guild, specified_user = scope_data
ValueError: not enough values to unpack (expected 4, got 3)
```
——
Use playlist append with the DJ role on and use a user that does not have the DJ role
The reply responds with “You do not have the permissions to manage playlist owned by {username of the person who did the command}”
The reply should respond with the owner of the playlist instead

Playlist delete has this same issue
Playlist remove has this same issue
——
Have a pleb user queue a playlist so that they are the requester.
Turn on DJ role.
Use [p]skip on the pleb act

```
[2019-09-26 10:43:06] [ERROR] red: Exception in command 'skip'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 6150, in skip
    if is_requester and not can_skip and skip_to_track is None and skip_to_track > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
——
The “Playlist modified” embed header for playlist append when the appending playlist has already-saved tracks should be in title case to match other Audio embed titles.
——
Where is the auto pause setting referred to in 721.feature.rst?
——
So this review isn’t entirely asking for changes, just wanted to mention the genre command is really slick and a great addition.

2019-10-02 16:35 UTC, Flame442 commented on changelog.d/audio/2904.enhance.2.rst
> +``[p]queue`` now works where there no tracks in the queue (it shows current track playing).
Should be "..where there **are** no tracks.."

2019-10-02 16:35 UTC, Flame442 commented on changelog.d/audio/2904.enhance.6.rst
> +``[p]seek`` and `[p]skip`` can be used by user if they are the song requester while DJ mode is enabled, if votes are disabled.
[p]skip is missing a backtick

2019-10-08 03:03 UTC, aikaterna commented
Playlist rename has “playlist update” in the help strings for the examples.

Playlist matching message should be changed.
Current: “{number} playlist match {name} Please try to be more specific or use the playlist ID.”
New: “{number} playlists match {name}: Please try to be more specific, or use the playlist ID.

Playlist update is able to be used by anyone, not just the author

Playlist dedupe message should be changed.
Current: “You do not have the permissions to manage playlist owned by {name}.”
New: “You do not have the permissions to manage {playlist name}, owned by {name}.” (Feel free to follow the format for Name/ID in other dialog boxes)
If it’s difficult to pull the playlist name at this point:
New: “You do not have the permissions to manage that playlist, which is owned by {name}.”

"""List all keywords added to the whitelist.""" is doubled.

Bump has some commented lines left in it.

2019-10-11 02:09 UTC, merged