Fixes it, I guess
Cog-Creators/Red-DiscordBot pull request #2971
Opened 2019-08-30 22:31 UTC by mikeshardmind

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
fixes #2910

2019-08-31 12:40 UTC, DevilXD commented
Since `role.mention` is approximately constant length at 22 characters, with comma and space making it 24, I suggest just going with a round 25 as future-proofing and checking how many role mentions can fit in 1024 characters:
```
1024 / 25 = 40,96
```
This way, one can limit the amount of roles displayed pretty accurately while still displaying at least the first 40 roles of a user:
```
roles = [x.mention for x in roles]
if len(roles) > 40:
    roles = roles[:40]
    roles.append("...")
roles = ", ".join(roles)
```
The above snippet makes the field use about `963` characters according to my testing. I thought this would be better than just a sad message about not being able to display the roles at all.

2019-08-31 16:37 UTC, Flame442 commented
Or just use pagify with the correct delim and only use the first page.

2019-08-31 19:39 UTC, mikeshardmind commented
I have no intent of only showing some of the roles. This may lead someone to think it's not behaving properly, or that someone has less roles than they do.

2019-09-01 07:22 UTC, DevilXD commented
The thing is, I think that showing at least some of the roles is better than showing no roles, or a sad message that no roles could be displayed.
Displaying some of them and adding "and X more roles not displayed due to embed limits." feels better, but the text feels cumbersome and overly technical for a general discord user.

Why not just "and X more..."?

2019-09-01 16:00 UTC, Flame442 commented
The last commit did add "and {numeric_number} more roles not displayed due to embed limits."

2019-09-01 20:36 UTC, DevilXD commented
I am aware, hence the last part of my last comment:

> Displaying some of them and adding "and X more roles not displayed due to embed limits." is much better, but the text feels cumbersome and overly technical for a general discord user.

> Why not just "and X more..."?

2019-09-01 20:41 UTC, mikeshardmind commented
Because there's a limitation on the discord side of things, most people wont ever see this, and placing why roles are truncated in that extreme case keeps people from asking us to change.that we don't show all of them.

2019-09-02 02:52 UTC, Flame442 requested changes
Error when the new code is triggered:
```py
Traceback (most recent call last):
  File "<venv>\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "<venv>\lib\site-packages\redbot\cogs\mod\names.py", line 147, in userinfo
    chunk = f"{r.mention}, "
AttributeError: 'str' object has no attribute 'mention'
```

2019-09-02 12:25 UTC, DevilXD commented on redbot/cogs/mod/names.py
>              data.add_field(name=_("Roles"), value=roles, inline=False)
```suggestion
            data.add_field(name=_("Roles"), value=roles_str, inline=False)
```
Shouldn't this be `roles_str` as well?

2019-09-02 13:33 UTC, Flame442 approved these changes

2019-09-02 13:38 UTC, merged