Tempban logging improvement
Cog-Creators/Red-DiscordBot pull request #2993
Opened 2019-09-10 18:40 UTC by DevilXD

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Added proper logging that possibly fixes #2912

2019-09-10 18:52 UTC, DevilXD commented
The changelog category is `misc` because this isn't really anything user-facing, just logging improvement.
The changelog entry itself might need a touchup too.

2019-09-12 21:21 UTC, mikeshardmind requested changes
Retain the prior catch. you can get a 50013 json response as part of a 403 response as well as part of a 400 response, but it isnt the only possible failure which was being caught by forbidden.

This was also catching a lack of 2FA with 2FA requirement.

2019-09-13 18:25 UTC, DevilXD commented
Doesn't `discord.Forbidden` inherit from `discord.HTTPException` tho? It should catch all of them.

Unless you mean like, the Forbidden should always make it log "due to permissions" occurrences, then I can just add `or e.status == 403` to the check.

2019-09-13 22:40 UTC, mikeshardmind approved these changes

2019-09-13 22:40 UTC, merged