Fixed crash originated in `bank.set_balance`
Cog-Creators/Red-DiscordBot pull request #2997
Opened 2019-09-12 10:47 UTC by Drapersniper

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Fixed crash seen in DM when calling `bank.set_balance`  which was introduced in #2926

2019-09-13 14:25 UTC, Flame442 commented
If this is fixing a bug introduced in dev, the changelog should probably be `misc`.

2019-09-18 23:13 UTC, Flame442 requested changes
The two functions affected by this change need to have their docstrings and typehints updated accordingly. Both now accept `Union[discord.Member, discord.User]` and both now raise `RuntimeError` (from the `get_`s they use) when a user is passed and the bank is server based.

2019-09-20 09:56 UTC, Drapersniper commented
All sorted, thanks for the review Flame!

2019-09-20 12:37 UTC, Flame442 commented
The wording of the RuntimeError's description "guild was not provided" makes it seems like there should be a way to pass a guild to the functions. This should be changed to something that references how a user was used and a member is required.

2019-09-20 15:15 UTC, Flame442 approved these changes

2019-09-22 06:05 UTC, merged