commit
Cog-Creators/Red-DiscordBot pull request #2998
Opened 2019-09-13 17:35 UTC by Vexed01

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Git updated the title they gave to the add to PATH option during setup for Windows from "Run Git from the Windows Command Prompt" to "Git from the command line and also from 3rd-party software", as we found out in [#support](https://discordapp.com/channels/133049272517001216/387398816317440000/622096446333911061). This PR also corrects some Windows-based vocabulary's capitalisation.

2019-09-13 17:47 UTC, Drapersniper commented
"Please note the launcher will be deprecated soon." if this is indeed being added here, shoudln't we add it to the  Mac and Linux docs ? given that this change will not be specific to windows

2019-09-13 17:48 UTC, Vexed01 commented
> "Please note the launcher will be deprecated soon." if this is indeed being added here, shoudln't we add it to the Mac and Linux docs ? given that this change will not be specific to windows

Good point, thanks for pointing out what my small brain cannot comprehend.

2019-09-28 21:30 UTC, mikeshardmind requested changes
While we *are* looking to remove the launcher, it's better to guide users away from it by not directing them to use it than to say "It's deprecated" when we haven't even decided on if removing it is in the cards, or if we should just be minimizing the code which lives in it.

2019-09-29 07:39 UTC, Vexed01 commented
I _think_ this is what you mean, you haven't clearly said exactly what changes you want.

2019-09-29 11:43 UTC, mikeshardmind approved these changes

2019-09-29 11:43 UTC, merged