[Docs] Update Cog Creation guide install
Cog-Creators/Red-DiscordBot pull request #3021
Opened 2019-10-01 04:05 UTC by yamikaitou

### Type

- [ ] Bugfix
- [ x] Enhancement
- [ ] New feature

### Description of the changes
Updates the Cog Creation guide to use the Stable version of Red instead of the Dev version (also removes the usage of the test egg)

2019-10-01 04:31 UTC, mikeshardmind requested changes
-1 from me on these changes. Would prefer to elaborate on why the development version may be useful to cog creators than not include it in the guide aimed at that group.

2019-10-01 04:40 UTC, yamikaitou commented
Good point, I'll see if I can rewrite it decently to detail both later

2019-10-22 12:15 UTC, mikeshardmind requested changes
The wording change is a slight nitpick.

Optionally, it might be worth tossing a link to [our cookiecutter](https://github.com/Cog-Creators/cog-cookiecutter) into the additional resources section while working on the cog creation guide, but I'll leave whether or not you think that should be included in this update up to you.

2019-10-22 12:15 UTC, mikeshardmind commented on docs/guide_cog_creation.rst
> +    The Develop version may have changes on it that break compatibility with the Stable version and other cogs.
```suggestion
    The Develop version may have changes on it which break compatibility with the Stable version and other cogs.
```

2019-10-23 19:58 UTC, yamikaitou commented on docs/guide_cog_creation.rst
> +    The Develop version may have changes on it that break compatibility with the Stable version and other cogs.
Updated and added

2019-10-23 21:50 UTC, mikeshardmind approved these changes

2019-10-23 21:51 UTC, merged