Add support for accessing config by ids
Cog-Creators/Red-DiscordBot pull request #3022
Opened 2019-10-02 00:05 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

Works toward a goal in #2804 

Adds a few methods for accessing config by ids without mocked objects.

This is technically a breaking change should anyone be using one of the following names as a key in a global scope:

- member_from_ids
- guild_from_id
- user_from_id
- channel_from_id
- role_from_id

2019-10-04 07:24 UTC, DevilXD commented
Wouldn't it be better to just modify the current groups to include the IDs as kwargs? Something like:

```py
def guild(self, guild: discord.Guild = None, *, guild_id: int = None) -> Group:
    if guild_id is None:
        guild_id = guild.id
    return self._get_base_group(self.GUILD, str(guild_id))
```

This approach could be enhanced with checks that'd make sure only one of the arguments was passed - however, in the above case it's not really necessary, as passing both will prioritize `guild_id` kwarg, and not passing anything will fail with `AttributeError` on the `guild.id` part.

This approach could be applied to `guild`, `user`, `channel` and `role` scopes.
For the special-cased `member` scope, same approach really:

```py
def member(
    self,
    member: discord.Member = None,
    *,
    guild_id: int = None,
    member_id: int = None
) -> Group:
    if guild_id is None:
        guild_id = member.guild.id
    if member_id is None:
        member_id = member.id
    return self._get_base_group(self.MEMBER, str(guild_id), str(member_id))
```

Same as above apply, with an exception of when passing in only one of the kwargs and a member object at the same time, the missing value would be substituted with the one from the member. This may have "hacky", but possibly beneficial applications:

```py
member: discord.Member
guild_id: int
other_member_id: int

# Changing the guild scope for the member passed
self.config.member(member, guild_id=guild_id)

# Targeting different member while retaining the original guild scope
self.config.member(member, member_id=other_member_id)
```

Overall, I think this is cleaner than adding five additional config methods, with an addition of making this a non-breaking change as well.

2019-10-04 14:40 UTC, mikeshardmind commented
I don't agree that this is cleaner than additional config methods, but I can appreciate not wanting more breaking changes. There's another approach I discussed before which I'll swap this to. 

I would prefer if config hadn't been using `__getattr__` in such a way while allowing global values to be attached directly to config without needing to explicit ask for a scope as it strongly limits what we can do here without breaking changes, but that ship has long since sailed.

2019-10-04 14:59 UTC, mikeshardmind commented
This is the other potential implementation. I'm still not convinced it is better, but see it and a brief overview of (some of) the considerations with it.

```py
    def member(
        self, 
        member: Optional[discord.Member] = ...,
        *,
        guild_id: Optional[int] = None,
        member_id: Optional[int] = None,
    ) -> Group:
        if member is ...:
            identifiers = str(guild_id), str(member_id)
        else:
            identifiers = str(member.guild.id), str(member.id)
        return self._get_base_group(self.MEMBER, *identifiers)
```

It is intentionally doing as little checking for the user as possible to minimize the overhead, while also retaining prior behavior for the large majority of existing uses.

It doesn't default to `None` for a member object intentionally as well here, as there are plenty of places where people are currently using `guild.get_member` and passing that to config without any checking, and being fine with the exception terminating things (such as in events)

Changing this to have different behavior for None here would be a larger breaking change than adding methods would.

2019-10-04 18:06 UTC, DevilXD commented
Looks alright to me, good point about `None` from `guild.get_member` there. I just think that adding kwargs to the existing methods would both - be a non-breaking change, and just work better syntax-wise and ease of use in the long run.

2019-10-07 15:40 UTC, mikeshardmind commented
I'm still not convinced that adding more to existing methods vs adding methods is correct here. In terms of maintaining various code, I'd rather config be slightly more verbose about the intent if it means all code using it is also easier to maintain. I'm leaving the implementation as is, the considerations for breakage remain either way, just in different ways.

2019-10-09 00:04 UTC, Flame442 requested changes
Everything works fine, however I don't like the gotcha from `member_from_ids` being the only plural.

2019-10-09 01:00 UTC, mikeshardmind commented
@Flame442 I don't feel this is a gotcha, just a natural consequence of the inability to identify a member from a singular id and accurate naming.

I'm open to other naming if you have an idea which doesn't present an issue with plurality.

2019-10-10 02:03 UTC, Flame442 requested changes
The changelog docs should probably state the new methods.
Although I would really like less confusing names for the methods, if no one can think of anything better they can stay.

2019-10-21 19:22 UTC, mikeshardmind commented
As we're now over a week without alternative name suggestion, I've gone and updated the changelog entry with the current names.

2019-10-22 20:01 UTC, Flame442 approved these changes

2019-10-22 20:25 UTC, merged