[Help] Add aliases if there is bellow syntax
Cog-Creators/Red-DiscordBot pull request #3040
Opened 2019-10-08 18:54 UTC by PredaaA

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
This PR just add back aliases in help formatter, I liked to have them before help rewritte.

2019-10-08 20:19 UTC, mikeshardmind submitted a review, later dismissed

2019-10-08 20:19 UTC, mikeshardmind commented on redbot/core/commands/help.py
> +            f"\n`Alias{'es' if len(command.aliases) > 1 else ''}: {', '.join(command.aliases)}`"
This construction isn't i18n safe and cannot be used as-is.

2019-10-08 20:41 UTC, mikeshardmind commented on redbot/core/commands/help.py
> +            f"\n`Alias{'es' if len(command.aliases) > 1 else ''}: {', '.join(command.aliases)}`"
Ignore this for now, the i18n stuff wasn't fully handled and this can be adapted for i18n when it is.

2020-01-09 02:08 UTC, mikeshardmind commented
This needs to be temporarily frozen until some of the help pagination behavior is changed in 3.2.1

This is *not* a rejection of adding this.

2020-04-28 16:36 UTC, jack1142 commented
The mentioned changes to the pagination have been done already so I'm unfreezing this.

@PredaaA can you resolve the conflicts and make the construction mentioned by Sinbad compatible with i18n?

2020-04-28 16:37 UTC, PredaaA commented
> The mentioned changes to the pagination have been done already so I'm unfreezing this.
> 
> @PredaaA can you resolve the conflicts and make the construction mentioned by Sinbad compatible with i18n?

Sure. I will do that later today.

2020-05-01 02:19 UTC, Jackenmen requested changes
Could you add a setting for showing aliases in help? It can be enabled by default.

2020-05-01 10:53 UTC, PredaaA commented
> Could you add a setting for showing aliases in help? It can be enabled by default.

Done.👍

2020-05-01 16:43 UTC, Jackenmen requested changes

2020-05-01 16:43 UTC, Jackenmen commented on redbot/core/core_commands.py
> +            await ctx.send(_("Help will show commands aliases."))
These two strings should be the other way around.
```suggestion
        if show_aliases:
            await ctx.send(_("Help will show commands aliases."))
        else:
            await ctx.send(_("Help will not show commands aliases."))
```

2020-05-01 16:43 UTC, jack1142 commented on redbot/core/commands/help.py
> +            signature += f"\n`{alias_fmt}: {humanize_list(command.aliases)}`"
This should probably show the prefix before the alias name and it also needs support for command groups (already discussed in Discord, just posting this here for completeness of review)
```suggestion
            signature += f"\n`{alias_fmt}: {humanize_list(command.aliases)}`"
```

2020-05-01 16:43 UTC, jack1142 commented on redbot/core/commands/help.py
> +            signature += f"\n`{alias_fmt}: {humanize_list(command.aliases)}`"
You will need to update handling for non-embed help but as discussed in Discord, this can wait until we decide on the formatting.

2020-05-01 16:43 UTC, jack1142 commented on redbot/core/commands/help.py
> +            signature += f"\n`{alias_fmt}: {humanize_list(command.aliases)}`"
We need some limit for amount of shown aliases as well as their max length.

2020-07-09 16:43 UTC, Jackenmen requested changes
There's one issue with conflict resolution + the non-embed help does not work properly with this PR as mentioned in the previous [review comment](https://github.com/Cog-Creators/Red-DiscordBot/pull/3040#discussion_r418624582). I said that it can wait until we decide on the formatting (which we did), so you have 2 options:
1. Update help's formatting as discussed [here (link to discussion in #old-advanced-coding)](https://discordapp.com/channels/133049272517001216/251782448629809152/705816866479669358)
2. Leave the formatting as is and make separate PR for that (assuming you want to do it of course).

And after either of these, you need to handle the non-embed help properly: there shouldn't be backticks in the formatting of non-embed help. Example of how it looks now:
![image](https://user-images.githubusercontent.com/6032823/87067167-f9d6ea00-c213-11ea-8bb0-66fcb682728d.png)

2020-07-09 16:43 UTC, jack1142 commented on redbot/core/commands/help.py
> +        )
Something went wrong with conflict resolution here - these lines weren't changed in this PR.

2021-01-20 22:39 UTC, jack1142 approved these changes
It's time.

2021-01-20 22:40 UTC, merged