[Core] Add `redbot --edit` cli flag
Cog-Creators/Red-DiscordBot pull request #3060
Opened 2019-10-15 18:54 UTC by jack1142

### Type

- [ ] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes
Yeah, so I forgot that I have this on my PC, I rebased the conflicts but leaving this as a draft for now as it hasn't been tested, it might still need a little cleanup as it seems quite long and I might have to move some fixes/enhancements made in here to separate PR.

2019-10-19 21:26 UTC, Malarne commented
After a bit of testing, a keyboard interrupt throws this error:
https://media.discordapp.net/attachments/133251234164375552/635226798006861834/unknown.png

2019-10-20 13:02 UTC, jack1142 commented
This is now ready for review, I updated the PR description accordingly.

2019-11-02 17:04 UTC, Flame442 requested changes

2019-11-02 17:04 UTC, Flame442 commented on changelog.d/3060.feature.rst
> +Add ``redbot --edit`` cli flag that allows to edit instance name, token, owner and datapath.
"allows to"

2019-11-02 17:04 UTC, Flame442 commented on redbot/__main__.py
> +        if not (15 <= len(str(owner)) <= 21):
You check `owner_id.isdecimal()` when done interactively, but not when done with flags.

2019-11-02 17:04 UTC, Flame442 commented on redbot/__main__.py
> +                "If you want to replace existing instance,"
This grammar isn't great.

2019-11-02 17:04 UTC, Flame442 commented on redbot/__main__.py
> +        print("Token updated.\n")
This appears to be the only one that actually outputs something to tell the user their change was successful.

2019-11-02 17:04 UTC, Flame442 commented on redbot/__main__.py
> +        red.loop.run_until_complete(red._config.token.set(token))
There is no validation that the token works when setting with flags.

2019-11-02 17:34 UTC, jack1142 commented on redbot/__main__.py
> +        if not (15 <= len(str(owner)) <= 21):
That's non-issue cause cli-flags is already set to "int"

2019-11-02 17:36 UTC, jack1142 commented on redbot/__main__.py
> +        print("Token updated.\n")
Should I add output to all other or remove it from here?

2019-11-02 17:59 UTC, Flame442 commented on redbot/__main__.py
> +        print("Token updated.\n")
There should probably be confirmation on all of them.

2019-11-08 17:05 UTC, Kowlin approved these changes
Works fine, can't break it.

2019-11-08 17:07 UTC, merged