More help improvements
Cog-Creators/Red-DiscordBot pull request #3063
Opened 2019-10-16 06:16 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

 - ``[botname]`` will be dynamically substituted in help
 - help now tries to be smart about newlines in docstrings
 - All user facing help text is i18n safe

resolves #2981

2019-10-25 22:00 UTC, Flame442 requested changes
As I described to you in #ac, the current behavior does not appear to match the description of `2981.enhance.2.rst`.

2019-10-25 22:00 UTC, Flame442 commented on redbot/core/commands/commands.py
> +# which is not imeediately followed by any of
Typo of "imeediately"

2019-10-25 22:00 UTC, Flame442 commented on changelog.d/2981.enhance.2.rst
> +docstrings for command help handle whitespace slightly differently to accomodate ease of writing good help.
Typo of "accomodate"

2019-10-26 15:29 UTC, mikeshardmind commented
Went with a different route due to other inconsistencies with what should be the replacement value of that prior regex being highly variable on context not captured. Also went and added changes to existing help as needed.

2019-10-26 19:25 UTC, mikeshardmind commented
After concerns raised in discord about this, the whitespace behavior change is made available to cog creators, but is not enabled by default.

2019-10-27 21:29 UTC, mikeshardmind commented
Changes still planned for deferred to a later version.

2019-11-24 01:27 UTC, closed without merging