change to_check.guild to getattr()
Cog-Creators/Red-DiscordBot pull request #3101
Opened 2019-11-07 15:50 UTC by Bakersbakebread

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Replaces to_check.guild with a getattr()

2019-11-07 15:53 UTC, mikeshardmind requested changes
As discussed in discord, this should actually return `True` in DMs (and docstring needs updating for this too)

Edit: hold on this, more discussion in discord

2019-11-07 16:12 UTC, Kowlin commented
Fixes #3100

2019-11-07 16:50 UTC, mikeshardmind commented on changelog.d/3100.bugfix.rst
> +change is_autmod_immune handling of guild check and support for checking webhooks
```suggestion
fix ``is_automod_immune`` handling of guild check and support for checking webhooks
```

2019-11-08 14:43 UTC, mikeshardmind approved these changes
Thanks for the quick follow up + discussion on discord.

2019-11-08 14:43 UTC, merged