admin string clarity changes
Cog-Creators/Red-DiscordBot pull request #3144
Opened 2019-11-19 21:42 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

This improves the clarity of the strings when a user isn't allowed to do something in the admin cog due to discord hierarchy.

2019-11-19 21:48 UTC, mikeshardmind commented
Additional thanks to [Dav](https://translate.discord.red/profile/Dav_) for reporting this problematic string to us on Crowdin.

![image](https://user-images.githubusercontent.com/22035876/69189394-40909c00-0aec-11ea-837e-914524f4792c.png)

2019-11-19 21:58 UTC, Dav-Git commented
I just started revising the German Translation so more might come up in the near future. If there is a place you want me to collect these at please let me know. If not I will just keep raising issues on Crowdin :)

2019-11-19 22:04 UTC, mikeshardmind commented
If one is easier than another, use whichever is easier. Opening issues about strings here may bring it to a wider audience than just those watching the crowdin issues though.

2019-12-30 00:03 UTC, Flame442 requested changes
These strings need to also include the fact that if the highest role is the same as the role in question it will fail.
EDIT: The bot hierarchy messages above these also need to be fixed.

2020-01-01 01:40 UTC, mikeshardmind commented
Strings in this are still gonna end up being improved, but @Flame442 is working on a better resolution of this (conversation in Discord) which involves cleaning up more of the user interaction than just the raw output, but also the usage and command syntax. As such, I'm closing this in favor of not duplicating work.

2020-01-01 01:40 UTC, closed without merging