[Docs] Update windows deps instructions
Cog-Creators/Red-DiscordBot pull request #3188
Opened 2019-12-13 19:51 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

This updates the Windows portion of our install documentation based on discussions about certain changes needed in 3.2

* This does not make the corresponding changes for other OSes
* This includes installing build tools for greater package support
* This uses adoptopenjdk11, but also clearly denotes this is only for audio support now.
* This does not add additional extras under current internal consideration.

2019-12-13 22:07 UTC, mikeshardmind commented
Note: These instructions are not safe on windows 7 due to reboot required updates that may not be installed. However, with Red 3.2 we will not be providing exceptional support to windows 7 due to Microsoft's decision to EOL it.

2019-12-14 18:26 UTC, palmtree5 requested changes

2019-12-14 18:26 UTC, palmtree5 commented on docs/install_windows.rst
> +    choco install choco install adoptopenjdk11jre --installarguments "ADDLOCAL=FeatureMain,FeatureJarFileRunWith,FeatureEnvironment,FeatureJavaHome,FeatureOracleJavaSoft INSTALLDIR=%ProgramFiles%\Ado
`choco install choco install`?

2019-12-14 18:26 UTC, palmtree5 commented on docs/install_windows.rst
> +    choco install choco install visualstudio2019-workload-vctools -y
`choco install choco install`?

2019-12-15 00:32 UTC, palmtree5 submitted a review, later dismissed

2019-12-15 01:57 UTC, palmtree5 approved these changes

2019-12-15 02:00 UTC, merged