[Audio] Change database backend
Cog-Creators/Red-DiscordBot pull request #3193
Opened 2019-12-17 20:08 UTC by Drapersniper

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Removed trhe Database dependency  and change it over to apsw, + update SQL statements and make them a little bit better

2019-12-18 09:04 UTC, mikeshardmind requested changes
This isn't a full review, just some things which I noticed at a relatively brief glance.

2019-12-18 09:04 UTC, mikeshardmind commented on redbot/cogs/audio/apis.py
> +    last_fetched TEXT
last_updated and last_fetched should be INTEGER types.

This may require altering existing tables if we are supporting people running dev changes.

2019-12-18 09:04 UTC, mikeshardmind commented on redbot/cogs/audio/apis.py
> +    track_info = :track_info,
use 
```
DO UPDATE SET track_info=excluded.track_info, last_updated=excluded.last_updated
```
While the query optimizer *should* handle this, I'd prefer to not run into any edge cases where it doesn't.

2019-12-18 09:04 UTC, mikeshardmind commented on redbot/cogs/audio/apis.py
> +_QUERY_LAST_FETCHED_LAVALINK_TABLE = """
After last_fetched is an INTEGER type, 
```
SELECT data from lavalink
WHERE last_fetched > :match_after_timestamp
```

2019-12-20 07:13 UTC, mikeshardmind requested changes

2019-12-20 07:13 UTC, mikeshardmind commented on redbot/cogs/audio/apis.py
> +            self._database = apsw.Connection(os.path.abspath(str(os.path.join(path, "cache.db"))))
use `redbot.core.data_manager.cog_data_path(None, raw_name="Audio") / "cache.db"` here.

2019-12-20 12:28 UTC, Drapersniper commented
Do we want the cache tables AND Playlist table to be in the same Database?
This PR uses "cache.db" but #3195 uses "Audio.db"... I'm all for making the cache tables into "Audio.db". WDYT @mikeshardmind. If the answer is yes should i reuse the connection/cursor or should i keep them separate

2019-12-20 12:31 UTC, mikeshardmind commented
Same DB, singular connection. Multiple cursors is fine.

2019-12-21 19:08 UTC, Drapersniper commented
Do not merge this one ... Merge #3205

2019-12-22 15:40 UTC, Drapersniper commented
Will setup a CPR for all of this so itsd easier to follow ... less likely to fuck up)

2019-12-22 15:40 UTC, closed without merging