[Core] Prevent users from locking themselves out with localblacklist
Cog-Creators/Red-DiscordBot pull request #3221
Opened 2019-12-25 23:40 UTC by jack1142

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Fixes #3207

2019-12-25 23:43 UTC, jack1142 commented
ehehe, just figured that you can also lock yourself out with localwhitelist 😄

2019-12-27 22:10 UTC, mikeshardmind requested changes
Also warrants minor changes to the actual logic used in the bot for this to retroactively prevent guild owners from being impacted by either this or local whitelist as well, up to you if you think that should be a separate PR or not.

2019-12-27 22:10 UTC, mikeshardmind commented on redbot/core/core_commands.py
> +                await ctx.send(_("You cannot blacklist an owner!"))
I feel like this leaves less room for misunderstanding with end users.
```suggestion
                await ctx.send(_("You cannot blacklist a bot owner!"))
```

2019-12-27 22:20 UTC, mikeshardmind submitted a review, later dismissed

2019-12-27 22:26 UTC, mikeshardmind approved these changes

2019-12-27 22:33 UTC, merged