Trivia upload
Cog-Creators/Red-DiscordBot pull request #3420
Opened 2020-01-20 08:25 UTC by Stonedestroyer

### Type

- [ ] Bugfix
- [ ] Enhancement
- [X] New feature

### Description of the changes
Trivia upload command. 

This is a draft PR so I can take ideas or if I am going in the wrong direction.

2020-01-20 09:54 UTC, Stonedestroyer commented
How do we want to support duplicate lists? 

I am thinking if a duplicate list is uploaded to either ask to overwrite or skip? 

And also if a list has the same name as a baselist warn user and gracefully error?

Does these two ideas sond good.

2020-01-20 10:55 UTC, Drapersniper commented
I would personally say if a playlist with the same name we prompt the user to override or skip. or simply silently fail and at the end of the command give a report to the user with failed list and reason it failed.

2020-01-20 11:10 UTC, Stonedestroyer commented
I am looking into adding maybe if you don't supply a file to ask you to add a file into that message or cancel but not sure. This should be done and work fairly well. 

Do we need a delete command?

2020-01-20 11:32 UTC, Stonedestroyer commented
Will add delete but the main command is ready for review.

2020-01-20 13:42 UTC, Stonedestroyer commented
This is WIP.

2020-01-20 14:53 UTC, mikeshardmind commented on redbot/cogs/trivia/trivia.py
> +            await file.save(filepath)
just something I noticed, don't know if the PR is intended to be ready yet. You've already saved this to a BytesIO object, just write the object, dont download from discord again

2020-01-20 17:14 UTC, Stonedestroyer commented on redbot/cogs/trivia/trivia.py
> +            await file.save(filepath)
Thank you, changed it.

2020-01-20 17:14 UTC, Stonedestroyer commented
This is pretty much done and ready to go for interview.

2020-03-17 13:00 UTC, Jackenmen requested changes
Overall, a good PR, there are few things that need changing but nothing major.

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            )
While I get why it's useful for bot owner to know which lists are custom (since these are the only ones owner can remove), I don't think it really should be shown to users like this. Maybe there should be a separate command for listing uploaded (custom) lists?

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            LOG.debug(f"File failed to upload: {exc}")
I think it might be worth sending the syntax error that happened during parsing of the YAML file (based on how permissions cog does it):
```suggestion
        except yaml.MarkedYAMLError as exc:
            await ctx.send(_("Invalid syntax: ") + str(exc))
```
And logging here is not gonna really be needed then as all the needed info is gonna already be in the sent message.

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            message = await ctx.bot.wait_for("message", check=MessagePredicate.same_context(ctx))
I propose using a timeout here, maybe 30 seconds?

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +        if filename in ("upload", "delete"):
It would be better to check against list of subcommands programatically than hardcoding those names:
```suggestion
        if filename in self.trivia.all_commands:
```

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            basefileexists = True
This check should probably happen *before* we try to download the attachment.

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +                    )
String has to be formatted after translation.
```suggestion
                    _(
                        "{filename} is a reserved trivia name and cannot be replaced.\n"
                        "Choose another name"
                    ).format(filename=filename)
```

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +                    )
String has to be formatted after translation.
```suggestion
                    _(
                        "{filename} already exists. Do you wish to overwrite?"
                    ).format(filename=filename)
```

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            await ctx.send("Saved Trivia list as {filename}".format(filename=filename))
This string has to be wrapped in `_()` for translations.
```suggestion
            await ctx.send(_("Saved Trivia list as {filename}").format(filename=filename))
```

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            await ctx.bot.wait_for("message", check=pred)
I think it might be friendlier to use reactions here, but it's up to you. Whatever you choose, use a timeout here as well.

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +            LOG.debug("Saved file as {filepath}".format(filepath=file))
I don't think logging is really needed here.

2020-03-17 13:00 UTC, Jackenmen commented on redbot/cogs/trivia/trivia.py
> +        basefileexists = None
Nitpick, I think using only bool type for this variable makes more sense here
```suggestion
        basefileexists = False
```

2020-03-21 13:43 UTC, Stonedestroyer commented on redbot/cogs/trivia/trivia.py
> +            )
Adding custom command trivialist while list shows all of it.

2020-03-21 13:49 UTC, jack1142 commented on redbot/cogs/trivia/trivia.py
> +                )
```suggestion
                _(
                    "{filename} is a reserved trivia name and cannot be replaced.\n"
                    "Choose another name"
                ).format(filename=filename)
```

2020-03-21 15:20 UTC, Jackenmen requested changes

2020-03-21 15:20 UTC, jack1142 commented on redbot/cogs/trivia/trivia.py
> +            overwrite_message_object: discord.Message = await ctx.send(message=overwrite_message)
```suggestion
            overwrite_message_object: discord.Message = await ctx.send(overwrite_message)
```

2020-03-21 15:20 UTC, jack1142 commented on redbot/cogs/trivia/trivia.py
> +    async def custom_trivia_list(self, ctx: commands.Context):
0 lists should be special-cased:
![image](https://user-images.githubusercontent.com/6032823/77229758-df5b0100-6b8f-11ea-9493-3a735705d83b.png)

2020-03-21 15:26 UTC, jack1142 commented on redbot/cogs/trivia/trivia.py
> +        if not personal_lists:
You have to return at the end of this `if`

2020-03-21 15:29 UTC, Jackenmen approved these changes
LGTM, thanks for the PR!

2020-03-21 15:30 UTC, merged