Add update check on bot startup
Cog-Creators/Red-DiscordBot pull request #356
Opened 2016-08-21 15:28 UTC by palmtree5

Checks for newer commits on github and messages the bot's owner if there is a mismatch (i.e. a newer version)

2016-08-21 17:53 UTC, tekulvw commented on red.py
> +        cur_version = os.popen(r'git show -s HEAD --format="%cr|%s|%h"')
Even though this should block for nearly no time at all, it's still bad practice. Check the `version` command in the Owner cog for a better (async) way to do this.

2016-08-21 18:04 UTC, palmtree5 commented
Referring to https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/owner.py#L526 presumably?

2016-08-21 23:30 UTC, tekulvw commented
Yep

2016-08-23 18:21 UTC, palmtree5 commented
So new commit. Sadly this functionality now uses requests as I was able to get the pulling of data from Github's API to work using requests but got [this](http://i.imgur.com/z93N19S.png) when trying to use aiohttp

2016-08-30 03:46 UTC, tekulvw commented
`run_in_executor` apparently makes whatever function call you supply it into a separate thread so no worries on the requests usage

2016-09-22 23:18 UTC, Twentysix26 requested changes
I haven't yet decided if I should implement this but requests is a no go

2016-09-22 23:38 UTC, palmtree5 commented
Ok so got it working with `aiohttp` (although it points to this repo regardless of whether it's a fork or not)

2016-09-22 23:48 UTC, Twentysix26 approved these changes

2016-12-17 23:17 UTC, Twentysix26 commented
Outdated and with various issues. Will implement in some other way if needed

2016-12-17 23:17 UTC, closed without merging

2016-12-17 23:28 UTC, palmtree5 commented
Lol I meant to close this with a note that this would be superseded by #533