Update deprecation warnings
Cog-Creators/Red-DiscordBot pull request #3608
Opened 2020-02-23 03:47 UTC by jack1142

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

2020-05-13 13:32 UTC, Flame442 requested changes
The strings are missing a few "the"s.
"...for removal in _**the**_ future..."
"...will be removed in _**the**_ first minor..."

2020-05-15 22:40 UTC, Flame442 submitted a review, later dismissed
A discussed in discord, these warnings are not showing up, seemingly for no reason, after applying this change. The old warnings do show up on a 3.3.6 bot, however the edited (and new) warnings do not appear. If someone else would like to test this PR to see if it is just me(/windows) being weird, that would be appreciated.

An example eval that produces a warning on 3.3.6 but not this pr is
```py
[p]eval
from redbot.core.utils import bounded_gather_iter
return bounded_gather_iter(ctx.send, loop='aaa')
```

2020-05-15 23:41 UTC, Flame442 submitted a review, later dismissed
Now that my warnings are not being suppressed, this works fine :P
For consistency's sake, all of the messages could be updated to have a similar format, but they work fine.

2020-05-16 00:27 UTC, Flame442 submitted a review, later dismissed

2020-05-16 02:04 UTC, Flame442 submitted a review, later dismissed
whatever...

2020-05-27 21:14 UTC, jack1142 commented
I found an issue with the module name shown by the `AttributeError` when import from `redbot.core.commands`:
![image](https://user-images.githubusercontent.com/6032823/83072860-c5e2a380-a06f-11ea-9a65-54ef90c1879b.png)
I fixed it in latest commit.

2020-06-05 18:59 UTC, Flame442 requested changes
```py
...\redbot\core\commands\__init__.py:150: DeprecationWarning: `APIToken` is deprecated since Red 3.3.0 and will be removed in the first minor release after 2020-08-05. Use `DictConverter` instead.
  return _converter__getattr__(name)
```
This is the warning I get from putting `from redbot.core.commands import APIToken` in a cog (or eval). It does not explain where the improper code is being used (and has that return line alone for some reason?)

2020-06-05 19:35 UTC, jack1142 commented
Ahh sorry, that's my oversight, I didn't notice that the deprecation warning needs a different stack level when being done from `commands` instead of `commands.converter`.

I pushed the commit that should fix this.

2020-06-05 19:53 UTC, Flame442 approved these changes

2020-06-22 01:08 UTC, jack1142 commented
We could probably already merge this PR - this only updates deprecation warnings which means there's no breaking change, and it seems beneficial that people will be able to see them sooner rather than later. It's in 3.4.0 milestone mostly because it needs to be ready *before* 3.4 gets released, but I don't think there's a reason to keep this hanging until we're actually ready with 3.4.

2020-06-22 01:25 UTC, Kowlin approved these changes

2020-06-22 01:25 UTC, merged