Deprecation warning - alternative
Cog-Creators/Red-DiscordBot pull request #3615
Opened 2020-02-26 10:41 UTC by Stonedestroyer

Alternative to #3613

Hides the known ones for non-debug and shows all for debug.

2020-02-26 10:46 UTC, Stonedestroyer commented
Updated to now also print warnings for both but hides the known ones for non-debug.

2020-02-26 15:06 UTC, Jackenmen requested changes
Few things that should be changed **if** we choose to handle #3612 in this way.

Also, this seems to missing one of the warnings mentioned in #3529?
```
<frozen importlib._bootstrap>:219: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
```

2020-02-26 15:06 UTC, Jackenmen commented on redbot/__init__.py
> +    _warnings.filterwarnings("default", category=DeprecationWarning)
This line is unnecessary

2020-02-26 15:06 UTC, Jackenmen commented on redbot/__init__.py
> +    _warnings.filterwarnings("ignore", category=DeprecationWarning, module="aiohttp", lineno=21)
Could you add link to related issue for these 2 warnings?
https://github.com/aio-libs/aiohttp/pull/4570

2020-02-26 15:06 UTC, Jackenmen commented on redbot/__init__.py
> +    )
Could you also add comment that this warning is caused by d.py? Something like
```
# discord.py is using deprecated kwarg name when making websockets connection
# https://github.com/Rapptz/discord.py/issues/2574
```
should suffice.

2020-02-26 15:18 UTC, Stonedestroyer commented
I have also updated https://github.com/Cog-Creators/Red-DiscordBot/issues/3529 to make it easier to track these changes.

2020-02-26 15:19 UTC, Stonedestroyer commented
@jack1142 I can remove the error messages and put a clearer error message if you want to reduce the clutter.

2020-02-28 01:22 UTC, Jackenmen approved these changes
LGTM

2020-02-28 01:22 UTC, merged