Downloader: smarter updating, track new, updated and deleted cogs
Cog-Creators/Red-DiscordBot pull request #363
Opened 2016-08-29 07:48 UTC by neonobjclash

The following changes were made:
* Show status of running update
* Show new, updated and deleted cogs
* Use git hash to determine if update is necessary
* Remove deleted cogs from the database

2016-08-30 03:40 UTC, tekulvw commented on cogs/downloader.py
> +            await self.bot.edit_message(msg, base_msg + status)
Use a try block to check for message existence, juuust in case

2016-08-30 03:41 UTC, tekulvw commented on cogs/downloader.py
>                  self.bot.unload_extension("cogs." + cog)
I'd definitely surround lines 215-216 in a try block (and possibly think about calling `reload` from Owner instead of doing this directly)

2016-08-30 06:56 UTC, neonobjclash commented
Changes made. Not sure about going through owner.py, will look into it further.

2016-09-17 15:11 UTC, Twentysix26 requested changes
`[p]cog update` seem to be blocking. It kills the bot with enough repos.

2016-10-05 09:28 UTC, neonobjclash commented
Only one task is run at a time now, instead of using `asyncio.gather()` which calls them all at once. Blocking is the only way to ensure the repos are updated before a) checking for new/deleted/updated cogs, and b) reloading updated cogs. The naive method of forking them off and waiting ten seconds is just that, and won't work with my change detection.

2016-10-22 14:06 UTC, Twentysix26 approved these changes

2016-11-02 22:53 UTC, Twentysix26 commented
https://github.com/Twentysix26/Red-DiscordBot/pull/363

2016-11-02 22:53 UTC, closed without merging