[Image] Allow user to choose how many images `[p]imgur search` sends
Cog-Creators/Red-DiscordBot pull request #3667
Opened 2020-03-17 17:43 UTC by jack1142

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Adds optional `count` argument that allows user to specify how many images they want to get.
By default, `[p]imgur search` command will send one image now.

2020-03-22 23:52 UTC, Flame442 requested changes

2020-03-22 23:52 UTC, Flame442 commented on redbot/cogs/image/image.py
> +        if 1 <= count <= 5:
This equality is backwards.

2020-03-23 00:17 UTC, jack1142 commented
Now that I looked at this again... I should probably also do the same change to imgur subreddit

2020-03-23 02:26 UTC, Flame442 approved these changes

2020-03-23 23:42 UTC, merged