Red V4 Release
Cog-Creators/Red-DiscordBot pull request #3716
Opened 2020-04-01 16:48 UTC by Drapersniper

The moment you all have been waiting for Red V4 is here.

Storage Backend
Don't like Config managing your database for you? Take back control with DataIO!

Music Playback
We've got less commands in audio now! Back to the basics.
No traffic egress used on your vps!
100% less memory used than v3's audio!

Fun Trivia games for your server
Edit your trivia files easier with the new and improved PLAIN TEXT FORMAT (no yaml formatting to learn)

Stream Alerts
Do they work? We don't know! But that's better than V3 eating your entire YouTube API quota!

3rd Party Cogs
Approved cog creator? Unapproved cog creator? Who needs those labels! Just hit up GitHub for over 1400 cogs that may or may not crash your bot.

* disclaimer: V4 should not be used for any Discord bot installation that actually needs to work and we will not be help accountable for you using this version of V4

2020-04-01 16:49 UTC, Jackenmen submitted a review, later dismissed
LGTM, that's the moment we've been waiting for!

2020-04-01 16:54 UTC, aikaterna commented
Man, who knew. No Audio is so much better. Approved

2020-04-01 16:57 UTC, PredaaA requested changes
Can you not Draperize this PR too? Resolve those conflicts and it'll be ready to go.
![74JZI-draperizedhonk](https://user-images.githubusercontent.com/46051820/78164961-e5cc6100-744a-11ea-977f-094c13ed1622.gif)

2020-04-01 16:59 UTC, NeuroAssassin submitted a review, later dismissed
I actually like it how it is, I think the draperization makes it better

2020-04-01 17:02 UTC, Flame442 requested changes
This looks like a really good change, thanks for contributing! Just need to sort out this one little issue then we can get this merged.

2020-04-01 17:02 UTC, Flame442 commented on .github/CONTRIBUTING.md
> +We've recently started adding unit-testing into Red. All current tests can be found in the `tests/` directory at the root level of the repository. You will need `py.test` installed in order to run th
Wouldn't this be `requirements.txt`?

2020-04-01 17:47 UTC, Stonedestroyer commented
I tried to run this and I get a websocket error, it seems audio is broken?

2020-04-01 17:49 UTC, Drapersniper commented
> I tried to run this and I get a websocket error, it seems audio is broken?

No it’s a hidden feature

2020-04-01 18:49 UTC, fixator10 commented
But can it run Minecraft?

2020-04-01 20:32 UTC, Jackenmen requested changes
I'm -1 on this, this would require us to maintain over 10k lines of code instead of maybe 250.

2020-04-01 20:33 UTC, PredaaA commented
Are you excepting to put docs on audio cog?

2020-04-02 10:22 UTC, Drapersniper commented
People aren't Ready for the awesomeness of a V4 release

2020-04-02 10:22 UTC, closed without merging