[Performance Improvements][Part 3] Make a most large loops lazier and async to avoid blocking large bots.
Cog-Creators/Red-DiscordBot pull request #3767
Opened 2020-04-18 11:47 UTC by Drapersniper

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
This one depends on #3766

2020-04-19 15:52 UTC, Jackenmen requested changes

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +    async def __anext__(self) -> Awaitable[_T]:
Incorrect type hint, it should be:
```suggestion
    async def __anext__(self) -> _T:
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            i = next(self.content)
`item` will be clearer than `i`, especially considering we already use `i` for index.
```suggestion
            item = next(self.content)
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +        return i
`item` will be clearer than `i`, especially considering we already use `i` for index.
```suggestion
        return item
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +    def __await__(self):
Add type hint (remember to import `Generator` from `typing`)
```suggestion
    def __await__(self) -> Generator[Any, None, List[_T]]:
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +    def __aiter__(self):
Add type hint (you need to add `from __future__ import annotations` at the top of the file):
```suggestion
    def __aiter__(self) -> AsyncGen[_T]:
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +        self, contents: Union[Iterator[_T], Iterable[_T]], delay: float = 0.0, steps: int = 1
Considering we're passing iterable (iterator is an iterable), I think it would be clearer to call it `iterable` instead of `contents`

I also have two suggestions for typings here:
a) we can simplify `Union[Iterator[_T], Iterable[_T]]` to just `Iterable[_T]` as all iterators are iterable
b) since `float` is not an `int`, we need to specify union of both here if we want to accept both (and since it's only used for `asyncio.sleep()`, I think we do want it)
```suggestion
        self, iterable: Iterable[_T], delay: Union[float, int] = 0, steps: int = 1
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +        self.content = iter(contents)
I think it would be clearer if this attribute were called `iterator` (or `it` if you prefer short version)

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +    async def remove_dupes(self):
This needs a better name - this doesn't remove duplicates, it gives you iterator without duplicated entries, maybe it should be called `without_duplicates()`?

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +    async def remove_dupes(self):
Add type hint:
```suggestion
    async def remove_dupes(self) -> AsyncIterator[_T]:
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +        self.steps = steps
I think all these attributes should be private.

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            start += 1
- I think using `async_enumerate` would be better here just so that all the logic is in one place.
- `start` is missing type hint
```suggestion
    def enumerate(self, start: int = 0) -> AsyncIterator[Tuple[int, _T]]:
        return async_enumerate(self, start)
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +        return self.flatten()
You need to return the result of the `coro.__await__()` not `coro` itself from `__await__` function:
```suggestion
        return self.flatten().__await__()
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/cogs/admin/announcer.py
> +        async for g in AsyncGen(guild_list, delay=0.5):
It would be better to use `asyncio.gather` here but I guess it's kind of out of scope for this PR.

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +    """Yield entry every `delay` seconds per `steps`."""
Better docstring needed (list parameters and their expected types as with any other function in this file)

We should also be a little more descriptive about what this does. Something more like (still needs to be better worded):
```
Asynchronous iterator yielding items from ``iterable`` that sleeps for ``delay`` seconds every ``steps`` items.
```

Last but not least, you need to add `automethod` directive for this class to `docs/framework_utils.rst`

2020-04-19 15:52 UTC, Jackenmen commented on redbot/cogs/mod/kickban.py
> +from ...core.utils import AsyncGen
It's a nitpick but I think it would be clearer to do `from redbot.core.utils import AsyncGen`

2020-04-19 15:52 UTC, Jackenmen commented on redbot/cogs/permissions/converters.py
> +            ),
This and the `all_roles` list that was added above can be simplified to:
```suggestion
            *(
                filter(lambda r: not r.is_default(), guild.roles)
                async for guild in AsyncGen(bot.guilds, steps=100)
            ),
```
That also means that `all_roles` from above can be removed.

2020-04-19 15:52 UTC, Jackenmen commented on redbot/cogs/permissions/converters.py
>          if not maybe_matches:
This whole thing should be done differently - we should stop when we figure out there's more than one match.

2020-04-19 15:52 UTC, Jackenmen commented on redbot/cogs/permissions/converters.py
>                  maybe_matches.append(obj)
Same as above, we should stop iterating when figure out there's more than one match.

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +class AsyncGen(AsyncIterable[_T]):
This class is not just `AsyncIterable` but also `AsyncIterator` so that generic suits it better. It can also be awaited so I think you should add `Awaitable` generic as well.
```suggestion
class AsyncGen(AsyncIterator[_T], Awaitable[List[_T]]):  # pylint: disable=duplicate-bases
```

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +        _temp = []
Since we don't care about order in `_temp` here, can you use `set` for better performance?

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +class AsyncGen(AsyncIterable[_T]):
This class name (`AsyncGen`) might be confusing - despite of what the name says, this isn't async generator, it's async iterator (and these two terms are different).

2020-04-19 15:52 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +__all__ = ("bounded_gather", "deduplicate_iterables", "AsyncGen")
It's not a part of the PR, but could you add `bounded_gather_iter` to `__all__`?
```suggestion
__all__ = ("bounded_gather", "bounded_gather_iter", "deduplicate_iterables", "AsyncGen")
```

2020-04-19 15:52 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            yield i
- Arguments are passed in wrong order to `async_filter()`
- `function`'s type hint is incorrect
- I think `*args, **kwargs` are unnecessary here, if someone wants to, they can pass partial themselves.
- This whole function can be simplified to regular function returning result of `async_filter()` function:
```suggestion
    def filter(self, function: Callable[[_T], Union[bool, Awaitable[bool]]]) -> AsyncFilter[_T]:
        return async_filter(function, self)
```

2020-04-19 15:52 UTC, jack1142 commented on redbot/cogs/permissions/converters.py
> +                    obj.id == member.id async for obj in AsyncGen(maybe_matches, steps=100)
I didn't test this but I doubt this works at all - `any()` can be used with regular iterables, not with async iterables.

2020-04-19 16:21 UTC, Drapersniper commented on redbot/cogs/permissions/converters.py
>          if not maybe_matches:
This is out of the scope of this PR no? I mean im happy to address it but .. just want to be sure

2020-04-19 18:58 UTC, Jackenmen requested changes

2020-04-19 18:58 UTC, jack1142 commented on docs/framework_utils.rst
> +    :members:
For the methods to show as `async for ... in enumerate(start=)` we need to manually indicate it for these two methods:
![image](https://user-images.githubusercontent.com/6032823/79696560-a17bf600-827d-11ea-8bf3-df493adc13b7.png)

```suggestion

.. autoclass:: AsyncIter
    :members:
    :exclude-members: enumerate, filter

    .. automethod:: enumerate
        :async-for:

    .. automethod:: filter
        :async-for:

```

2020-04-19 18:58 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +           [1, 5]
bad indentation here
```suggestion
            >>> from redbot.core.utils import AsyncIter
            >>> def predicate(value):
            >>>     return value <= 5
            >>> iterator = AsyncIter([1, 10, 5, 100])
            >>> await iterator.filter(predicate)
            [1, 5]
```

2020-04-19 18:58 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            >>>    return value <= 5
Let's use 4 space indent here
```suggestion
            >>>     return value <= 5
```

2020-04-19 18:58 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            >>> async for i in iterator.filter(predicate):
This looks incomplete, maybe you wanted to add a `print()` here?
```suggestion
            >>> async for i in iterator.filter(predicate):
            >>>     print(i)
```

2020-04-19 18:58 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            >>> async for i in iterator.enumerate(start=10):
This looks incomplete, maybe you wanted to add a `print()` here?
```suggestion
            >>> async for i in iterator.enumerate(start=10):
            >>>     print(i)
```

2020-04-19 18:58 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            >>> async for i in iterator.without_duplicates():
This looks incomplete, maybe you wanted to add a `print()` here?
```suggestion
            >>> async for i in iterator.without_duplicates():
            >>>     print(i)
```

2020-04-19 18:58 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +        self._content = iter(iterable)
Wouldn't it make more sense to call this `self._iterator`?

2020-04-19 19:02 UTC, Jackenmen requested changes

2020-04-19 19:02 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +        self._content = iter(iterable)
```suggestion
        self._iterator = iter(iterable)
```

2020-04-19 19:02 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            item = next(self._content)
```suggestion
            item = next(self._iterator)
```

2020-04-19 20:24 UTC, jack1142 commented on redbot/cogs/permissions/converters.py
> +            ),
This isn't actually a valid code - `*` can't be used with async iterators

2020-04-20 09:02 UTC, Jackenmen requested changes

2020-04-20 09:02 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            >>>     print(i)
```suggestion
            ...     print(i)
```

2020-04-20 09:02 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            >>>     print(i)
```suggestion
            ...     print(i)
```

2020-04-20 09:02 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            >>>     return value <= 5
```suggestion
            ...     return value <= 5
```

2020-04-20 09:02 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            >>>     return value <= 5
```suggestion
            ...     return value <= 5
```

2020-04-20 09:02 UTC, Jackenmen commented on redbot/core/utils/__init__.py
> +            >>>     print(i)
```suggestion
            ...     print(i)
```

2020-04-20 17:55 UTC, Jackenmen approved these changes

2020-04-20 17:56 UTC, merged