Send notification to channel when song changes
Cog-Creators/Red-DiscordBot pull request #379
Opened 2016-09-16 03:11 UTC by gizmo385

This is in response to #284 and similar to the change proposed in #325. However, this change should work no matter what channel the bot is in. 

It required storing the text channel that the play commands are initiated so that the bot can send the message to the right channel.

2016-09-17 12:17 UTC, Socialery commented
perhaps False for no notification, True for notification to the channel the song was requested for, and channel ID for a specific channel?

2016-09-18 00:03 UTC, gizmo385 commented
That's definitely a possible thing that could be added. Anyone else have any thoughts on it?

2016-09-22 22:20 UTC, Eslyium commented
So after testing this, And Discord started to freak out or something else occurred it started relaying now playing to all servers. Might be a problem.

2016-09-23 17:32 UTC, gizmo385 commented
Hmm that's odd. I'll look into it and see if I can replicate the issue. Thanks for the heads up!

2016-11-15 13:40 UTC, tekulvw requested changes

2016-11-15 13:40 UTC, tekulvw commented on cogs/audio.py
> +        if self.settings.get("NOTIFY"):
This should really be a per server configurable option so all servers can have their song announced on change.

2016-12-22 01:22 UTC, xdtrammell commented
Is this branch going to be merged I would really like this feature.

2017-02-21 01:21 UTC, closed without merging