Added slot statistics
Cog-Creators/Red-DiscordBot pull request #383
Opened 2016-09-19 19:53 UTC by matthewknecht

`[p]sstats` <@user>` gets the user who was mentioned
`[p]sstats` gets the information of the user who ran the command

There should be sufficient catching of potential errors, but I could've overlooked something. This can be optimized but I tried to make it readable.

2016-11-15 13:51 UTC, tekulvw requested changes
Have you tested this at all? You'd get at least 6 `NameError`s if you were to load it into a working bot

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +from cogs.utils.dataIO import fileIO
You  need to import `dataIO` here, not `fileIO`

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +        temp_msg = "```ruby\nSlot statistics for {0.name}:\n\nLose:\t  {1}\nx2:\t\t{2}\nx3:\t\t{3}\nx4:\t\t{4}\nx5000:\t {5}\n\n+500:\t  {6}\n+800:\t  {7}\n+1000:\t {8}\n\nSpent:\t {9}\nGained:\t{10}
This thing looks like it could be done in a slightly more clean way

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +        dataIO.save_json(self.file_path, self.system)
`self.system` doesn't exist

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +        dataIO.save_json(self.file_path, self.system)
`self.system` doesn't exist

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +        dataIO.save_json(self.file_path, self.system)
`self.system` doesn't exist

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +        dataIO.save_json(self.file_path, self.system)
`self.system` doesn't exist

2016-11-15 13:51 UTC, tekulvw commented on cogs/economy.py
> +        dataIO.save_json(self.file_path, self.system)
`self.system` doesn't exist

2016-12-22 14:40 UTC, Twentysix26 commented
Closing as this would require major rework (the code is very messy) and there's an incoming slot machine refactor

2016-12-22 14:40 UTC, closed without merging