[Docs] Update docs now mention need to restart
Cog-Creators/Red-DiscordBot pull request #3849
Opened 2020-05-14 11:32 UTC by Dav-Git

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes
Previously the update docs never mentioned that you have to restart yur bot for the update to take effect.

2020-05-14 13:15 UTC, Drapersniper commented
I think, it would be better just telling them to Always complete the update with the bot off, this would avoid potential permissions error, and any other potential issue wit ha hot update.

2020-05-14 14:22 UTC, Dav-Git commented
I'm not quite sure on the wording for 3.1.X and 3.0 and older...

2020-05-28 21:59 UTC, Jackenmen requested changes
I'll commit the suggestions in a moment, looks good otherwise

2020-05-28 21:59 UTC, jack1142 commented on docs/update_red.rst
> +If you have Red 3.2.0 or newer, upgrading can be achieved by following these 4 easy steps:
```suggestion
If you have Red 3.2.0 or newer, you can upgrade by following these 4 easy steps:
```

2020-05-28 21:59 UTC, jack1142 commented on docs/update_red.rst
> +If you have Red 3.2.0 or newer, upgrading can be achieved by following these 4 easy steps:
```suggestion
If you have Red 3.2.0 or newer, you can upgrade by following these 4 easy steps:
```

2020-05-28 22:12 UTC, Kowlin approved these changes
LGTM

2020-05-28 22:14 UTC, Jackenmen approved these changes

2020-05-28 22:14 UTC, merged