[Core] Add check to `Localwhitelist add` to avoid blacklisting invoker or guild owner
Cog-Creators/Red-DiscordBot pull request #3903
Opened 2020-06-03 16:13 UTC by Drapersniper

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
fixes #3222

2020-06-04 11:18 UTC, jack1142 commented
Adding guild owner is actually unnecessary - the linked issue description is slightly outdated and we always return `True` for guild owner already:
https://github.com/Cog-Creators/Red-DiscordBot/blob/2c313594dacf298e47e3e5ec339f2af2c545b9b2/redbot/core/bot.py#L383-L385

*(I just happened to look at issue tracker :P)*

2020-06-04 12:06 UTC, Drapersniper commented
> Adding guild owner is actually unnecessary - the linked issue description is slightly outdated and we always return `True` for guild owner already:
> https://github.com/Cog-Creators/Red-DiscordBot/blob/2c313594dacf298e47e3e5ec339f2af2c545b9b2/redbot/core/bot.py#L383-L385
> 
> _(I just happened to look at issue tracker :P)_

yeah i saw this after i added but forgot to remove it, thanks for spotting it

2020-06-18 22:10 UTC, Jackenmen requested changes
Similar check is needed `[p]localwhitelist remove` as well - I can add myself, then someone else and later remove myself and then I will lose my access to the bot.

Also, I was thinking that the error message in `[p]localwhitelist add` could mention that to prevent access loss, you should add yourself to the whitelist first.

2020-06-21 18:41 UTC, Jackenmen requested changes
The comment I made in Discord that would be good to address in this PR:
These checks are not needed for guild owners and bot owners as they're not affected by the local whitelist and it may make it unnecessarily harder to add/remove some role on the whitelist.

2020-07-06 23:23 UTC, Jackenmen requested changes

2020-07-06 23:23 UTC, jack1142 commented on redbot/core/core_commands.py
> +            theoretical_whitelist = current_whitelist + uids
You're concatenating list and set here which raises an error.

2020-07-07 18:03 UTC, Jackenmen approved these changes
Looks good to me.

2020-07-07 18:08 UTC, merged