[core.utils] Add 2 new methods to `AsyncIter`
Cog-Creators/Red-DiscordBot pull request #3921
Opened 2020-06-05 12:46 UTC by Drapersniper

### Type

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature

### Description of the changes

Adds `AsyncIter.map` which allows users to specify a callable to wrap returns in.
Adds `AsyncIter.find` which allows users to give a predicate and return the first value that matchs said predicate

I intentionally did not Add `get` here as i can't think of sane way to implement that on something that may or may not have non class object.

fixes #3887

2020-06-05 12:47 UTC, Drapersniper commented
![image](https://user-images.githubusercontent.com/27962761/83877824-11ade080-a733-11ea-80e2-5eeb5c1b3488.png)
![image](https://user-images.githubusercontent.com/27962761/83877862-24c0b080-a733-11ea-9e64-b738973e02fe.png)

2020-06-07 14:26 UTC, Drapersniper commented on redbot/core/utils/__init__.py
> +        >>> async for value in AsyncIter(range(3)).map(bool):
```suggestion
        >>> async for value in AsyncIter(range(3)).map(bool)
```

2020-06-07 14:26 UTC, Drapersniper commented on redbot/core/utils/__init__.py
> +        >>> await AsyncIter(range(3)).find(lambda x: x == 1):
```suggestion
        >>> await AsyncIter(range(3)).find(lambda x: x == 1)
```

2020-06-18 22:56 UTC, Jackenmen requested changes

2020-06-18 22:56 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +        return await maybe_coroutine(self._map, item)
Considering that `await`s give control back to the event loop, I'm not sure if it's that good to await if we don't have to - would it be possible to default `self._map` to `None` and only await if it's not `None`?

2020-06-18 22:56 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +        if func and not callable(func):
We don't allow anything that isn't evaluating to True, so we should just straight check if it's callable.
```suggestion
        if not callable(func):
```

2020-06-18 22:56 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +    def map(self, func: Union[Coroutine[..., _S], Callable[..., _S]]) -> AsyncIter[_S]:
Type hint should specify what should the function `func` accept:
```suggestion
    def map(self, func: Callable[[_T], Union[_S, Awaitable[_S]]]) -> AsyncIter[_S]:
```

2020-06-18 22:56 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +        self, predicate: Union[Callable, Coroutine], default: Optional[Any] = None
Type hint should specify what should the function `predicate` accept and return:
```suggestion
        self,
        predicate: Callable[[_T], Union[bool, Awaitable[bool]]],
        default: Optional[Any] = None,
```

2020-06-18 22:56 UTC, jack1142 commented on redbot/core/utils/__init__.py
> +            The value to return if there is no matches.
```suggestion
            The value to return if there are no matches.
```

2020-06-19 22:07 UTC, Jackenmen submitted a review, later dismissed
Looks good to me, although this PR does not implement the `next()` method that was proposed in the issue @fixator10 made: #3887

2020-06-19 22:09 UTC, Drapersniper commented
ermmm i didnt see the next() nethod ... i can implement that relatively easily ... tomorrow.

2020-06-21 17:33 UTC, Jackenmen approved these changes
LGTM 👍 ([Will you be my friend?](https://cdn.discordapp.com/attachments/160386989819035648/723950271465652324/DiWsOPgW4AAYTSD.png))

2020-06-21 17:47 UTC, merged