Fix the copyright in LICENSE file
Cog-Creators/Red-DiscordBot pull request #3985
Opened 2020-06-18 14:51 UTC by jack1142

![image](https://user-images.githubusercontent.com/6032823/85035804-dfb16b00-b183-11ea-8f6a-d73ab556b8e9.png)

Twentysix is part of Cog Creators so I'm guessing it's fine to just replace "Twentysix" with "Cog Creators"?

2020-06-19 16:12 UTC, Kowlin commented
I'm currently thinking to not fully replace Twentysix's name within the copyright, and rather add a new line in for Cog-Creators on when Red was moved to the org, I tried to find examples of this in the wild and I couldn't find any. So I'm not sure on how legally sound this plan of mine is.

2020-06-19 16:15 UTC, jack1142 commented
I thought that Red V3 was made by Cog Creators since the beginning? I thought that since this LICENSE is on V3/develop branch, it would only apply to the code inside it, but I'm really not sure how that sounds in legal terms.

2020-07-28 23:25 UTC, Kowlin requested changes

2020-07-28 23:25 UTC, Kowlin commented on LICENSE
> +    Copyright (C) 2015-2020  Cog Creators
```suggestion
    Copyright (C) 2019-2020  Cog Creators
    Copyright (C) 2015-2019  Twentysix
```

2020-07-28 23:25 UTC, Kowlin commented on LICENSE
> +    Red-DiscordBot  Copyright (C) 2015-2020  Cog Creators
```suggestion
    Red-DiscordBot  Copyright (C) 2019-2020  Cog Creators
    Red-DiscordBot  Copyright (C) 2015-2019  Twentysix
```

2020-07-28 23:35 UTC, Kowlin approved these changes

2020-07-28 23:36 UTC, merged

2020-08-10 08:49 UTC, nfitzen commented
If we get Twentysix to sign a copyright waiver, we could possibly reassign copyright. Isn't V3 a near-rewrite?

That said, the [GPL's copyright permission notice](//gnu.org/licenses/gpl-3.0.html) states:

> Copyright (C) 2007 Free Software Foundation, Inc.
<https://fsf.org/>
>
> Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

As such, it's actually illegal to change any part of the license document from the FSF's published copy, including the "How to Apply These Terms to Your New Programs" section.

Also, is this project licensed under GPL-3.0-only or GPL-3.0-or-later? I assume it's GPLv3 only, but I assume it's probably too late to start now.