Fixed Mod cog tempban taking local timezone into account
Cog-Creators/Red-DiscordBot pull request #4017
Opened 2020-06-25 13:53 UTC by DevilXD

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

`.utcfromtimestamp()` takes local timezone into account when converting a timestamp back into a `datetime` object: https://cdn.discordapp.com/attachments/160386989819035648/725707305320185876/unknown.png
Considering that the timestamp that ends up being stored is in UTC, this is probably not what was intended.

Ref of where the value is stored: https://github.com/Cog-Creators/Red-DiscordBot/blob/632840384b0cc3d67ac31a74e20a3dfd1c5cff03/redbot/cogs/mod/kickban.py#L445

There appears to be one other place where `.utcfromtimestamp()` is used, and it might require the same change - I can add it once that's confirmed: https://github.com/Cog-Creators/Red-DiscordBot/blob/ad979180e57e1f770c7ca013f0d46ca043bcb3b2/redbot/core/bank.py#L136

2020-06-25 14:02 UTC, Dav-Git submitted a review, later dismissed

2020-06-30 13:52 UTC, jack1142 commented
Hmm, the actual issue here is with how we create the timestamp - `datetime.timestamp()` assumes that naive `datetime` instances (such as the one generated by `datetime.utcnow()`) represents local time and therefore generates incorrect POSIX timestamp that is relative to local timezone.

I don't think we can really solve that though, when we already have existing data, so I guess this might be needed middle ground 😐

2020-06-30 17:15 UTC, DevilXD commented
> `datetime.timestamp()` assumes that naive datetime instances (such as the one generated by `datetime.utcnow()`) represents local time (...)

This is not really the case though? `datetime.utcnow()` always generates a UTC timestamp object, no matter the timezone. The `.timestamp()` method converts that to a POSIX timestamp, and `datetime.fromtimestamp()` converts it back - also no matter the timezone. You should always operate on UTC timestamps internally, only **optionally** using timezone conversions when displaying the information to the user - otherwise you're exposing yourself to lots of potential bugs, such as the stored time intervals changing when you change the system timezone, among many others.

My recommendation would be to stick to UTC stamps, and as explained, only deal with timezones when it's time (duh) to display it to the user.

2020-06-30 17:16 UTC, jack1142 commented
> This is not really the case though? `datetime.utcnow()` always generates a UTC timestamp object, no matter the timezone. The `.timestamp()` method converts that to a POSIX timestamp, and `datetime.fromtimestamp()` converts it back - also no matter the timezone.

Well, not really. `.timestamp()` **assumes** the time is local when the datetime object is naive. And `datetime.utcnow()` returns a naive datetime object that is not in local timezone.

2020-07-04 07:39 UTC, DevilXD commented
This is technically ready to go. Aware datetime objects are now used in places where they are (or can end up) being stored in the config, along with UTC conversion back.

One thing I'd like to point out tho - the audio cog has lots of `datetime.utcnow()` usage, and probably lots of timestamp conversions too. Because the internals of that cog appear to be too complicated for me, I haven't touched anything there. I'm not sure if its in the scope of this PR, but if someone knowledgeable about that would / could point me to the right places, I'll add the changes as needed.

2020-08-10 22:25 UTC, Jackenmen requested changes
A very late review, sorry for that.

Aside from review comments:
- The `message.created_at` in `redbot/cogs/filter/filter.py:L376` was missed
- Per your comment, I checked Audio's usage of `utcnow()` and it shouldn't need any changes, so this PR doesn't need to touch it.

2020-08-10 22:25 UTC, Jackenmen commented on redbot/core/modlog.py
> +                datetime.utcfromtimestamp(self.modified_at).strftime("%Y-%m-%d %H:%M:%S")
Would it be possible to include " UTC" suffix or something like that so that it's clear to users in what timezone this is in?

2020-08-10 22:25 UTC, Jackenmen commented on redbot/core/modlog.py
>              end_fmt = end.strftime("%Y-%m-%d %H:%M:%S")
Would it be possible to include " UTC" suffix or something like that so that it's clear to users in what timezone this is in?

2020-08-10 22:25 UTC, jack1142 commented on redbot/core/events.py
> +        bot._uptime = datetime.now(timezone.utc)
Bot's uptime from this var is exposed in `bot.uptime` property, so this change could break someone (+ it does break `[p]uptime` command). I don't think the change here is really needed.

2020-08-12 08:43 UTC, Jackenmen approved these changes
Looks good to me, thanks for contributing these fixes for the timezone madness 😄

2020-08-12 08:46 UTC, merged