[Core Commands] Add Help settings view
Cog-Creators/Red-DiscordBot pull request #4022
Opened 2020-06-26 20:46 UTC by mikeshardmind

### Type

- [ ] Bugfix
- [ ] Enhancement
- [X] New feature

### Description of the changes

Adds a command for viewing the current help settings.

resolves #4013 depends on #4011

2020-06-26 20:50 UTC, mikeshardmind commented
Just for a quick reference of how this looks with the default formatter, though there's a small bit about prepending a warning that these settings may not be used if a non-default formatter is in use.
![image](https://user-images.githubusercontent.com/22035876/85899968-f5024700-b7cc-11ea-80e2-7433a1322a60.png)

2020-06-26 21:04 UTC, jack1142 commented
Maybe this would look better in code block?

2020-06-26 21:11 UTC, mikeshardmind commented
I'm not convinced that it looks better, especially when a custom tagline is in use (which I realize isn't shown in the quick example)

2020-07-06 08:28 UTC, Drapersniper commented
Since the tagline is only added as `"{tagline_info}"` couldnt we add the first art into a code block followed by the tagline.
IMO it will kee in line with the existing Setting dislays in core.

2020-08-06 00:13 UTC, jack1142 commented
Needs conflict resolution

2020-08-06 00:43 UTC, jack1142 commented on redbot/core/commands/help.py
> +            tagline_info = _("\nCustom Tagline: {tag}").format(tag)
```suggestion
            tagline_info = _("\nCustom Tagline: {tag}").format(tag=tag)
```

2020-08-06 01:21 UTC, Jackenmen requested changes
It would be nice if `Delete delay` were suffixed with " seconds" when it's set.

If you won't be able to do this, I'll just do a follow up PR for it later after merging

2020-08-06 01:38 UTC, Jackenmen approved these changes
Looks good to me, thanks for the follow up!

2020-08-06 01:38 UTC, merged