[Core] Docstring full stops and a few other grammar fixes
Cog-Creators/Red-DiscordBot pull request #4023
Opened 2020-06-27 17:22 UTC by Vexed01

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
It seems that the majority of the docstrings in core_commands.py don't have full stops - this adds them!
There are also a few general grammar fixes as well.

2020-06-27 17:24 UTC, aikaterna commented on redbot/core/core_commands.py
> +        Configured for automatic moderation action immunity.
This is one string here: "Gets the current members and roles configured for automatic moderation action immunity."

2020-07-06 16:42 UTC, jack1142 commented on redbot/core/core_commands.py
> +        """Customizes a section of [p]info.
Quotation needed, but I believe we decided that command names in help docstrings in Red should be put in backquotes. (don't change this until someone confirms)
```suggestion
        """Customizes a section of `[p]info`.
```

2020-07-06 17:23 UTC, Jackenmen requested changes
Looks good, but I found few typos in the lines edited by this PR that could be addressed by it as well

2020-07-06 17:23 UTC, jack1142 commented on redbot/core/core_commands.py
> +        Adds a destination text channel to recieve owner notifications.
```suggestion
        Adds a destination text channel to receive owner notifications.
```

2020-07-06 17:23 UTC, jack1142 commented on redbot/core/core_commands.py
> +        Makes a user or roles immune from automated moderation actions.
```suggestion
        Makes a user or role immune from automated moderation actions.
```

2020-07-06 17:23 UTC, jack1142 commented on redbot/core/core_commands.py
> +        Makes a user or roles immune from automated moderation actions.
```suggestion
        Makes a user or role immune from automated moderation actions.
```

2020-07-06 17:23 UTC, jack1142 commented on redbot/core/core_commands.py
> +        """Customizes a section of [p]info.
You know... Just do it 👍

2020-07-06 17:23 UTC, jack1142 commented on redbot/core/core_commands.py
> +        """Interally reloads modules so that changes are detected."""
```suggestion
        """Internally reloads modules so that changes are detected."""
```

2020-07-06 18:21 UTC, Jackenmen approved these changes
Looks good to me.

2020-07-06 18:21 UTC, merged