[Core]Make help.py translatable
Cog-Creators/Red-DiscordBot pull request #4044
Opened 2020-07-06 21:53 UTC by Dav-Git

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
This closes #3818

2020-07-07 18:41 UTC, Jackenmen reviewed
This isn't a review, just two things I noticed when looking at this.

2020-07-07 18:41 UTC, jack1142 commented on redbot/core/commands/help.py
> +                    name=_("{ctx.me.display_name} 'Help Menu'").format(ctx=ctx),
Quotes weren't part of the string her.
```suggestion
                    name=_("{ctx.me.display_name} Help Menu").format(ctx=ctx),
```

2020-07-07 18:41 UTC, jack1142 commented on redbot/core/commands/help.py
> +                    name=f"{ctx.me.display_name} {_('Help Menu')}", icon_url=ctx.me.avatar_url
There's still use of `_()` inside f-string here

2020-07-07 19:50 UTC, Dav-Git commented
When reviewing please pay close attention to Lines 594 - 597. For whatever reason pyling is going ham here but flake8 seems to be ok?

2020-07-07 23:34 UTC, Jackenmen requested changes
I ended up reviewing it...
One issue with a string + you need to replace `_` with something else (`__` is what's usually used when `_` is already taken) on line 193 so that it doesn't end up replacing the variable with translator.

2020-07-07 23:34 UTC, jack1142 commented on redbot/core/commands/help.py
> +                    title = _("**__('No Category'):__**")
Parentheses and quotes weren't part of the string.
```suggestion
                    title = _("**__No Category:__**")
```

2020-07-08 00:20 UTC, mikeshardmind commented
For context, `T_` was used here was to make it visually distinct from markdown, not realizing that redgettext wasn't grabbing this as well (other cogs at the time had used `T_` to denote a deferred translation, so I hadn't even checked)

2020-07-08 13:08 UTC, Jackenmen approved these changes
Looks good to me.

2020-07-08 13:11 UTC, merged