[Docs] Fix free hosting wording
Cog-Creators/Red-DiscordBot pull request #4050
Opened 2020-07-08 15:11 UTC by Vexed01

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
Looking at this it doesn't make complete sense. The company and tier are listed, then it says that those companies have free tier VPSes which has already been mentioned.
And I would hope it's very clear that these are VSPes.

_Stupid author and reviewer of #3916..._

2020-07-08 15:15 UTC, Drapersniper commented
I somewhat disagree with the wording here.

The changes imply that AWS is suitable to small bots, rather than the original stating that free tiers are avaliable and those free tiers are suitable.

If anything I'd change:

`AWS EC2 Free Tier <https://aws.amazon.com/free/>`_ have free tier VPSes suitable for small bots.
AWS EC2 is not *always* free—it's a 12 month free trial.

to

`AWS EC2 <https://aws.amazon.com/free/>`_ have free tier VPSes suitable for small bots.
AWS EC2 is not *always* free—it's a 12 month free trial.

2020-07-08 16:29 UTC, Jackenmen requested changes

2020-07-08 16:29 UTC, jack1142 commented on docs/host-list.rst
> +Note AWS EC2 is not *always* free—it's a 12 month free trial.
I think this note would be clearer like this:
```suggestion
Note: AWS EC2's free tier does not last forever - it's a 12 month trial.
```

2020-07-08 16:57 UTC, Jackenmen requested changes

2020-07-08 16:57 UTC, jack1142 commented on docs/host-list.rst
>  for 12 months.
It doesn't look that good without any line breaks:
![image](https://user-images.githubusercontent.com/6032823/86947970-d137ed00-c14c-11ea-9cd3-eff76483538d.png)

Perhaps we could add some?
![image](https://user-images.githubusercontent.com/6032823/86947926-c3826780-c14c-11ea-9688-e5053a239b4c.png)

```suggestion
| `Google Cloud Compute Engine <https://cloud.google.com/free/docs/gcp-free-tier>`_,
  `Oracle Cloud Compute <https://oracle.com/cloud/free/#always-free>`_ and
  `AWS EC2 <https://aws.amazon.com/free/>`_ have free tier VPSes suitable for small bots.
| **Note:** AWS EC2's free tier does not last forever - it's a 12 month trial.
| Additionally, new Google Cloud customers get a $300 credit which is valid
for 12 months.
```

2020-07-09 16:12 UTC, Jackenmen approved these changes
Looks good to me, thanks for the PR.

2020-07-09 16:12 UTC, merged