Update warnings.py -- Checks for warning people above in hierarchy and server owner
Cog-Creators/Red-DiscordBot pull request #4100
Opened 2020-07-23 07:10 UTC by Generaleoley

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

Added checks to warnings to prevent abuse.

2020-07-23 07:49 UTC, Dav-Git requested changes
You also need to format this using black. See https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md

2020-07-23 07:49 UTC, Dav-Git commented on redbot/cogs/warnings/warnings.py
> +            await ctx.send(_("The person you're trying to warn is equal or higher to you on the discord hierarchy, you cannot warn them."))
I'm pretty sure it should be "is equal or higher than you in the discord hierarchy"

2020-07-23 09:23 UTC, Drapersniper submitted a review, later dismissed
Both comments from Dav can be considered requested changes for this PR.

2020-07-28 23:42 UTC, Kowlin reviewed
As an additional note to add on-top of the already existing comments, Style checks are failing. You can run the style checking from the make file.

2020-09-03 14:22 UTC, Kowlin approved these changes

2020-09-03 14:22 UTC, Kowlin commented
Thank you for your contribution.

2020-09-03 14:23 UTC, merged