[Modlog] add timestamp to [p]casesfor and [p]case
Cog-Creators/Red-DiscordBot pull request #4137
Opened 2020-07-31 10:18 UTC by Dav-Git

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Added timestamps display to the non-embedded version of ``[p]case`` and ``[p]casesfor``.
![grafik](https://user-images.githubusercontent.com/57032623/89025849-16e47180-d317-11ea-9824-fe7aee2de505.png)
![grafik](https://user-images.githubusercontent.com/57032623/89025882-25328d80-d317-11ea-8689-dd7836d6d859.png)

2020-07-31 11:00 UTC, Dav-Git commented
ignore latest empty commit, i'm dumb

2020-08-13 10:51 UTC, Dav-Git commented
I just accepted incoming here, let's hope datetime isn't needed anywhere I guess

2020-08-13 11:10 UTC, Dav-Git commented
@jack1142 does any of this now require different handling with #4017 merged? I've honestly not quite kept up with the underlying issue there and am unsure if this sort of display is affected.

2020-08-13 12:59 UTC, Jackenmen requested changes

2020-08-13 12:59 UTC, Jackenmen commented on redbot/cogs/modlog/modlog.py
> +                message = _("{case}\n**Timestamp**: {timestamp}").format(
The colon is bolder for other fields, so it should be bolded here too for consistency.
```suggestion
                message = _("{case}\n**Timestamp:** {timestamp}").format(
```

2020-08-13 12:59 UTC, Jackenmen commented on redbot/cogs/modlog/modlog.py
> +                message = _("{case}\n**Timestamp**: {timestamp}").format(
The colon is bolder for other fields, so it should be bolded here too for consistency.
```suggestion
                message = _("{case}\n**Timestamp:** {timestamp}").format(
```

2020-08-13 12:59 UTC, jack1142 commented on redbot/cogs/modlog/modlog.py
> +                        "%Y-%m-%d %H:%M:%S"
Updated handling per #4017:
```suggestion
                    timestamp=datetime.utcfromtimestamp(case.created_at).strftime(
                        "%Y-%m-%d %H:%M:%S UTC"
```

2020-08-13 12:59 UTC, jack1142 commented on redbot/cogs/modlog/modlog.py
> +                        "%Y-%m-%d %H:%M:%S"
Updated handling per #4017:
```suggestion
                    timestamp=datetime.utcfromtimestamp(case.created_at).strftime(
                        "%Y-%m-%d %H:%M:%S UTC"
```

2020-08-13 21:15 UTC, Jackenmen approved these changes
LGTM, thanks for PRing.

2020-08-13 21:17 UTC, merged