chemistry quiz
Cog-Creators/Red-DiscordBot pull request #4157
Opened 2020-08-05 06:07 UTC by ellwhy

### Type

- [ ] Bugfix
- [ ] Enhancement
- [X] New feature

### Description of the changes

Added a chemistry quiz. Special thanks to authors Hanumat, Stolas, Hermes! Yaml linted to perfection using https://codebeautify.org/yaml-validator

2020-08-05 06:28 UTC, ellwhy commented
I noticed there's an old trivia quiz PR (https://github.com/Cog-Creators/Red-DiscordBot/pull/4005/files). We'll probably combine the two and remove any overlap/reiterations. Let me know if that sounds good with you (whoever is reviewing this).

2020-08-05 06:49 UTC, ellwhy commented
I noticed there's an old chemistry trivia quiz PR (https://github.com/Cog-Creators/Red-DiscordBot/pull/4005/files). I'm thinking of combining the two trivia files into this PR's yaml. Let me know if that sounds good with you (whoever is reviewing this). For now I'll go ahead and remove any overlap that this quiz has with the other one.

2020-08-05 07:48 UTC, Drapersniper commented
First and foremost wanted to say thanks for PRing is great seeing new contributors.

> I noticed there's an old chemistry trivia quiz PR (https://github.com/Cog-Creators/Red-DiscordBot/pull/4005/files). I'm thinking of combining the two trivia files into this PR's yaml. Let me know if that sounds good with you (whoever is reviewing this). In the mean time, any overlap that this quiz has with the other one has been removed from this yaml.

That PR is only from the 22nd, so it's not stale.
Please never copy an open PR without explicit approval from the PR author, I don't see anything wrong with having 2 different chemistry trivial.

2020-08-05 07:57 UTC, ellwhy commented
> First and foremost wanted to say thanks for PRing is great seeing new contributors.
> 
> > I noticed there's an old chemistry trivia quiz PR (https://github.com/Cog-Creators/Red-DiscordBot/pull/4005/files). I'm thinking of combining the two trivia files into this PR's yaml. Let me know if that sounds good with you (whoever is reviewing this). In the mean time, any overlap that this quiz has with the other one has been removed from this yaml.
> 
> That PR is only from the 22nd, so it's not stale.
> Please never copy an open PR without explicit approval from the PR author, I don't see anything wrong with having 2 different chemistry trivial.

No problem, I figured you were probably thinking of leaving the two separate PRs intact, which is why I went ahead and re-committed a yaml that excludes any overlaping questions from the other PR. I'd argue that it would be cleaner to just combine the two yamls into one, seeing as how they're both general chemistry knowledge. I'll leave a comment on the other PR and see what the other author wants to do.

Keep in mind, both PR#4005 and this include an addition of a file titled "chemistry.yaml" so there will be some merge conflict if left intact.

2020-08-05 08:07 UTC, Drapersniper commented
You could make a PR to their branch and add your questions to their trivia and both of you coauthor it thats okay, and add yourself to the Author string in line of of their PR, so that it is co-authored.

Alternatively it could be a variant on name like `chemestry2`, `chemestryadvanced` or something like this.

Personally I don't have a preference, whichever way you two find better here is fine with me.

2020-08-05 08:16 UTC, ellwhy commented
Sounds good! I'll start that conversation with the author of the other PR and update this one accordingly.

2020-08-14 18:50 UTC, ellwhy commented
Due to inactivity from the other PR #4005, I'm going to go ahead and keep this PR separate. chemistry.yaml has been renamed to chemistryplus.yaml in case of naming conflict when #4005 gets merged in.

This yaml has been linted accordingly and is ready to merge whenever.

2020-08-14 19:36 UTC, ellwhy commented
Upon further discussion, we have decided to combine the contents of #4005 into this PR's yaml file. 

This yaml has been linted accordingly and is ready to merge whenever.

2022-08-23 01:31 UTC, Flame442 requested changes
The bulk of the content of this list is good, however the imgur image links provide some interesting challenges. All images used need to be licensed in a way that let us use them, and the links need to be from a red-controlled domain.

If you find public domain versions of these images (where they are not already), and message them (or their URLs) to @aikaterna (aikaterna#1393 on discord), she can provide you with appropriate URLs to replace the current imgur links with. If you'd rather not do that, or can't find public domain versions of any of the images, you can delete those questions instead.

Other than that, this looks good to go. Let me know when you've sorted that out.

2026-05-18 23:52 UTC, Jackenmen approved these changes
This has been in limbo long enough, so I opted to just remove the questions with images myself. Let's just merge this without them, there are only two of them anyway.

2026-05-18 23:52 UTC, merged

2026-05-19 00:58 UTC, MiniJennJenn commented
Oops, I never even registered that this happened...4 years ago.

On Mon, May 18, 2026 at 4:52 PM Jakub Kuczys ***@***.***>
wrote:

> Merged #4157 <https://github.com/Cog-Creators/Red-DiscordBot/pull/4157>
> into V3/develop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Cog-Creators/Red-DiscordBot/pull/4157?email_source=notifications&email_token=AFUGIY52CAL3SW2YP2UC7WD43OO5VA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTENJWHAZDEMRZGQYTNJTSMVQXG33OU5RW63LNMVXHJJLFOZSW45FMMZXW65DFOJPWG3DJMNVQ#event-25682229416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUGIYZU4HTLZUVKSA2FZ4343OO5VAVCNFSM6AAAAACZDQLHTOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMRVGY4DEMRSHE2DCNQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you commented.Message ID:
> ***@***.***>
>