Modlog types fix
Cog-Creators/Red-DiscordBot pull request #4326
Opened 2020-08-20 03:44 UTC by TrustyJAID

### Type

- [x] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
`create_case` has missmatching types for user where it should match the Case object typehints.

2020-08-20 04:10 UTC, mikeshardmind commented
Repeating what I said in the linked pull for context: modlog should probably accept `discord.Object` (and pull out the id and use it as it already accepts the id) since it's already doing type detection and it's possible for things like message authors to be a`discord.Object` in some rare cases (this is documented in discord.py) so if moderation happens based on one of these cases, it will fail to create a case.

2020-08-20 04:57 UTC, TrustyJAID commented
I have changed this to accept discord.Object objects as a potential type and adjusted the logic for what to do when dealing with an Object rather than an int or User object. I also added an extra optional arg for `create_case` to allow for users to provide the `last_known_username` when creating cases since it was easy to add.

2020-08-20 16:03 UTC, jack1142 commented
This is modifying current API of the `Case ` by breaking existent expectations where non-cached users are presented as an `int`.
I would suggest to instead just cast `discord.Object` to `int` if that's what's passed to `user`, `moderator`, or `amended_by`.

2020-08-20 16:06 UTC, jack1142 requested changes
I should have done the comment above as a "request changes" review since PR is in current state a breaking change. Fixing that with this review.

2020-08-20 19:35 UTC, TrustyJAID commented
@jack1142 this does not remove the option to still provide an int, just extends that it may be an int, a fake user object with missing attributes, or a valid user object.

2020-08-20 22:29 UTC, jack1142 commented
@TrustyJAID I meant that the resulting `Case` object may now be of `discord.Object` type which changes user's expectations. While it's not that big of a deal considering this will only be returned like this from `modlog.create_case()` (so developer would need to explicitly pass `discord.Object` to `create_case()`) and using `modlog.get_case()` will still return a `Case` object with an `int`, it does break consistency.

And on top of that, this imo complicates the logic unnecessarily when it's possible to just cast it to `int` in `Case`'s `__init__`.

2020-08-22 01:11 UTC, Jackenmen submitted a review, later dismissed
Type hints don't have `discord.Object` as supported type, and the types in docstrings are still inaccurate. Also, `Case.edit()` still does not support `discord.Object` with this PR which would be good to fix for consistency.

2020-09-19 15:08 UTC, jack1142 requested changes
Looks good to me, I just have one comment about documentation improvement for the new `last_known_username` that would be nice to address.

2020-09-19 15:08 UTC, jack1142 commented on redbot/core/modlog.py
> +        The last known username of the user
Might be worth noting that this will be ignored, if passed `user` parameter implements `discord.abc.User`.

2020-09-19 16:32 UTC, jack1142 requested changes
Looks like there's a bug here I missed

2020-09-19 16:32 UTC, jack1142 commented on redbot/core/modlog.py
> +                setattr(self, item, data[item])
```suggestion
            value = data[item]
            if isinstance(value, discord.Object):
                # probably expensive to call but meh should capture all cases
                setattr(self, item, value.id)
            else:
                setattr(self, item, value)
```

2020-09-19 17:02 UTC, jack1142 approved these changes
Looks good to me, thanks!

2020-09-19 17:05 UTC, merged