[Mod] Pluralize properly in userinfo/serverinfo
Cog-Creators/Red-DiscordBot pull request #4397
Opened 2020-09-03 21:06 UTC by Dav-Git

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
Resolves #4379

2020-09-03 21:09 UTC, Dav-Git commented
I didn't edit anything in serverinfo because serverinfo gramatically makes sense with he plural

2020-09-04 15:42 UTC, Predeactor submitted a review, later dismissed

2020-09-07 16:48 UTC, TurnrDev commented
I really think it would be useful if the translation module supported [Plural-Forms](https://www.gnu.org/software/gettext/manual/html_node/Translating-plural-forms.html).

2020-09-07 16:49 UTC, TurnrDev approved these changes, later dismissed

2020-09-07 18:22 UTC, Dav-Git commented
Yeah, I tried to make this as translation safe as possible by using to strings as not all languages pluralize by appending an s.

2020-09-19 22:20 UTC, jack1142 requested changes

2020-09-19 22:20 UTC, jack1142 commented on redbot/cogs/mod/names.py
> +                name=_("Previous Names") if len(val) > 1 else _("Previous Name"),
You need to check the length of names list, not the length of the resulting string.
```suggestion
                name=_("Previous Names") if len(names) > 1 else _("Previous Name"),
```

2020-09-19 22:20 UTC, jack1142 commented on redbot/cogs/mod/names.py
> +                name=_("Previous Nicknames") if len(val) > 1 else _("Previous Nickname"),
You need to check the length of names list, not the length of the resulting string.
```suggestion
                name=_("Previous Nicknames") if len(nicks) > 1 else _("Previous Nickname"),
```

2020-09-20 20:56 UTC, Dav-Git commented
lmao how did this derp sneak through? Thanks for noticing :)

2020-09-20 21:23 UTC, jack1142 requested changes

2020-09-20 21:23 UTC, jack1142 commented on redbot/cogs/mod/names.py
> +            )  # len(roles) > 2 because @everyone is a "role" which is just not displayed.
Sorry, I somehow missed this. We already strip the `@everyone` role above (see line 173), so this results in incorrect results.
```suggestion
                name=_("Roles") if len(roles) > 1 else _("Role"), value=role_str, inline=False
            )
```

2020-09-20 22:39 UTC, jack1142 approved these changes
LGTM, thanks!

2020-09-20 22:39 UTC, merged