[ModLog] Add [p]listcases and typing indicator to casesfor
Cog-Creators/Red-DiscordBot pull request #4426
Opened 2020-09-13 22:37 UTC by TrustyJAID

### Type

- [ ] Bugfix
- [x] Enhancement
- [x] New feature

### Description of the changes
This adds a `[p]listcases` command to show multiple cases for a user in a single message rather than trying to utilize the menu for each individual case. This also adds a typing indicator to casesfor so you know the bot is working when there's a lot of modlog cases to gather.

2020-09-28 11:17 UTC, Kowlin requested changes, later dismissed

2020-09-28 11:17 UTC, Kowlin commented on redbot/cogs/modlog/modlog.py
> +    @modlogset.command()
You're undoing a purposefully set alias here.

2021-01-22 00:36 UTC, jack1142 requested changes
Two things I've noticed.
1. Pagifying may cut a case in half.
2. No separators between each case make the message a bit hard to read.

I think that at least the first issue should be solved.

![image](https://user-images.githubusercontent.com/6032823/105429577-f952ed80-5c51-11eb-9a0a-d6eb95dcc6ba.png)

2021-01-23 19:37 UTC, jack1142 requested changes
`1.` still doesn't work properly due to lack of `priority` kwarg to `pagify()`

2021-01-23 19:37 UTC, jack1142 commented on redbot/cogs/modlog/modlog.py
> +            for page in pagify(message, ["\n\n", "\n"]):
```suggestion
            for page in pagify(message, ["\n\n", "\n"], priority=True):
```

2021-01-23 19:47 UTC, jack1142 approved these changes
Looks alright now.

2021-01-23 19:48 UTC, merged