Move modlogset/bankset commands to core
Cog-Creators/Red-DiscordBot pull request #4486
Opened 2020-10-13 03:07 UTC by palmtree5

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Fixes #4128 

This accomplishes everything on the list in the mentioned issue, though I did this by simply moving the commands over. The only renames happening here are:

- `[p]economyset registeramount` -> `[p]bankset registeramount`
- `[p]bank reset` -> `[p]bankset reset`
- `[p]bank prune` -> [p]bankset prune`

This obviously removes the `Bank` cog. The `Modlog` cog remains with 3 commands (`[p]case`, `[p]casesfor`, and `[p]reason`)

2020-10-13 05:29 UTC, Dav-Git requested changes
I don't think this move serves it's intended purpose without grouping all commands under ``set``. The idea was to have all settings in one place which this PR doesn't really accomplish now.
If the commands were moved into the ``set`` command group we would have achieved that goal.

2020-10-13 07:45 UTC, Drapersniper commented
There's such a thing as having too many commands, when the audio api is done for example it will not be under set due to the number of commands it will introduce. I disbelieve that every single global configuration command must be under set... that becomes a mess of a user experience as there's too many commands under a single group to deal with

2020-10-14 06:42 UTC, palmtree5 commented
I agree with Draper. Commands for configuring APIs on the bot (like modlog and bank) should absolutely be in the core cog, but I also feel they should not all be under `[p]set` as that will result in a further mess (which is already the case there meaning we may wish to do some regrouping of `[p]set`'s subcommands either by creating command groups under it or splitting things out of `[p]set` into their own groups to group relevant commands together)

2020-10-14 11:40 UTC, Dav-Git commented
That's a good point. A regrouping of set commands to sort them by core API /feature they belong to makes sense. However with these groups any commands that control core or API settings need to be in ``set``

2020-10-16 03:38 UTC, palmtree5 commented
So this PR was already a breaking change for the command moves and renames but initially there was an issue with tests failing, necessitating moving `redbot.cogs.mod.converters.RawUserIds`. I wound up moving that to `redbot.core.commands.converter.RawUserIds` and getting rid of `redbot.cogs.mod.converters` meaning that particular converter would be covered in our version guarantees moving forward.

2021-05-27 03:46 UTC, palmtree5 commented
Merge conflicts have been fixed on this one. Should hopefully have not broken anything either but still probably needs testing to be sure of that

2021-05-27 03:57 UTC, palmtree5 commented
Ok, NOW the merge conflicts have actually been fixed (after I managed to miss a couple trying to resolve in vscode lol).

2021-07-23 17:40 UTC, aikaterna commented on redbot/core/core_commands.py
> +            - `[p]economyset registeramount 5000`
This should be `[p]bankset registeramount 5000`

2021-07-23 17:41 UTC, aikaterna commented
There was some talk in AC this morning about some setting info that is duplicated in both bankset showsettings and economyset showsettings (max balance and default initial balance) where they should be removed from the economy settings and just have them available in bank settings.

https://discord.com/channels/133049272517001216/718148684629540905/868174816082006036
https://discord.com/channels/133049272517001216/718148684629540905/868181565878960168

2021-10-24 00:07 UTC, jack1142 commented
@palmtree5 If you have some time to resolve the conflicts that have shown up here since May, I think I could go ahead with getting this reviewed and merged soon.
Let me know if you won't have time for this and I'll try finding some time to resolve these conflicts myself.

2021-10-24 00:49 UTC, palmtree5 commented
I'll try to look at this in the next couple days

2021-10-27 00:04 UTC, palmtree5 commented
@jack1142 conflicts have been resolved on this and checks have passed

2021-11-25 09:04 UTC, jack1142 approved these changes
LGTM

![](https://i.fluffy.cc/3X84Bq2RR182XcPr0NTKKCp7wvNT8MhD.gif)

2021-11-25 09:06 UTC, merged