[Docs] CustomCommands Cog Guide
Cog-Creators/Red-DiscordBot pull request #4490
Opened 2020-10-14 20:44 UTC by bobloy

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Adds the customcom cog guide to the docs. Based on the descriptions provided in the commands.
Same method as #4488 , so depends on that approach being approved.

2020-10-19 17:33 UTC, bobloy commented
Now ready for review. Part of #1734 as well.

I am interested in feedback on how I handled command aliases. I'm not sure Tip is the right way, or in the right spot.

2020-10-26 23:41 UTC, Flame442 requested changes
One (1) typo, then this should be good to go!

2020-10-26 23:41 UTC, Flame442 commented on docs/cog_guides/customcommands.rst
> +- ``<cooldown>`` The number of seconds to wait before allowing the command to be invoked again. If ommited, will instead return the current cooldown settings.
```suggestion
- ``<cooldown>`` The number of seconds to wait before allowing the command to be invoked again. If omitted, will instead return the current cooldown settings.
```

2020-10-26 23:41 UTC, Flame442 commented on redbot/cogs/customcom/customcom.py
> +        - `<cooldown>` The number of seconds to wait before allowing the command to be invoked again. If ommited, will instead return the current cooldown settings.
```suggestion
        - `<cooldown>` The number of seconds to wait before allowing the command to be invoked again. If omitted, will instead return the current cooldown settings.
```

2020-10-29 03:49 UTC, Flame442 approved these changes
Thanks!

2020-10-29 03:49 UTC, merged