[downloader] Smarter updates and patch notes
Cog-Creators/Red-DiscordBot pull request #450
Opened 2016-11-07 06:02 UTC by neonobjclash

Cumulative commit of previous work done by Redjumpman and myself:
* Blocking repo updates with progress indicator
  - The existing method of 'start *all* the `git pull`s and wait ten seconds' is dumb.
* Smart reload of only changed cogs
  - Reloading all repo cogs because they *might* have been updated... is dumb.
* Doesn't break when cogs are removed from a repo
  - This is also dumb.
* Display of added, removed, and updated cogs
* Patch notes for updated cogs using `git log` (original idea by @Redjumpman)

No @irdumbs's were hurt in the making of this PR

2016-11-07 16:45 UTC, Jan200101 commented
Seems clean and good

2016-11-08 17:04 UTC, tekulvw requested changes

2016-11-08 17:04 UTC, tekulvw commented on cogs/downloader.py
> +            run(["git", "-C", dd + name, "stash", "-q"])
Can we change this to `git reset --hard HEAD`?

2016-11-08 17:22 UTC, tekulvw approved these changes

2016-11-08 21:39 UTC, neonobjclash commented
@Twentysix26 please test the parallel updates and see if you have the same issue as before

2016-11-09 14:34 UTC, Redjumpman approved these changes
+1

2016-11-10 02:48 UTC, neonobjclash commented
Needs some final testing for the windows plebs, but it's squashed and ret2merge otherwise 🎉

2016-11-10 07:29 UTC, neonobjclash commented
Appears to work fine on windows, I will have to add error handling for each `git` call later.

2016-11-10 10:21 UTC, Twentysix26 commented
Seems to be working fine. Want to add some finishing touches?

2016-11-10 14:24 UTC, Jan200101 approved these changes

2016-11-11 06:28 UTC, neonobjclash commented
Nah, it's good. Like I said, I'll implement detailed error handling for strange cases like already-cloned repos, filenames too long/incompatible with windows, and repos with an invalid structure in a future PR.

2016-11-13 15:47 UTC, Redjumpman commented
No bugs that I can replicate. Downloader seems to be ready for production

2016-11-13 15:48 UTC, Jan200101 approved these changes
Great. Tested on Linux 4.4.12v7-aufs and Windows 10 both worked and I am already using it

2016-11-13 17:58 UTC, Kowlin commented
Going to give this a shot on my ends, but I doubt I have any problems, will tag once its done.

2016-11-13 18:26 UTC, YeahImRose approved these changes
Worked with no problems on Ubuntu 16.04 for me :+1:

2016-11-13 19:48 UTC, Kowlin approved these changes
Core functionality seems to be working. I'll add another comment on the stuff that could use some touching up. For now I think this can be merged with some work down the line.

2016-11-13 19:51 UTC, Kowlin commented
For the extra stuff, I doubt the bot will time out a thread if that thread requires additional information such as an authenticated ``git pull``, also the bot can return a ``NoneType`` if the repo isn't found. But this isn't exactly new news.

2016-11-13 20:04 UTC, tmercswims approved these changes
Working great for me!

2016-11-15 13:35 UTC, merged