[Docs] Streams user guide
Cog-Creators/Red-DiscordBot pull request #4521
Opened 2020-10-23 01:48 UTC by palmtree5

# Enhancement request

#### Describe the enhancement

This adds a user guide for the streams cog to the docs.

#### Does this enhancement break existing functionality?

- [ ] Yes
- [x] No

2020-10-26 02:32 UTC, palmtree5 commented
Marked ready for review.

2020-11-09 01:03 UTC, Flame442 requested changes, later dismissed
Almost all set!

2020-11-09 01:03 UTC, Flame442 commented on docs/cog_guides/streams.rst
> +Manage custom message for stream alerts.
```suggestion
Manage custom messages for stream alerts.
```
OR
```suggestion
Manage the custom message for stream alerts.
```

2020-11-12 04:43 UTC, palmtree5 commented on docs/cog_guides/streams.rst
> +Manage custom message for stream alerts.
Fixed, though it's worth noting that was basically a copy/paste from the command's docstring so I took the liberty of fixing it there too

2020-11-27 02:50 UTC, Flame442 submitted a review, later dismissed
Thanks!

2020-11-27 03:01 UTC, Flame442 approved these changes
*grumbles*

2020-11-27 18:52 UTC, merged