stop playing on empty channel after 5 minutes
Cog-Creators/Red-DiscordBot pull request #456
Opened 2016-11-08 21:00 UTC by SomeFixItDude

I removed the elif and changed the statement to an "or" comparison, you'll see below. This way if you disconnect reconnect due to network or accident you don't dump your whole queue. Also then moved the clear queue to the section where it preforms the disconnect. So basically if the bot is done playing or no one is in the channel for 5 minutes, its clears queue, stops, disconnects.

2016-11-08 21:01 UTC, SomeFixItDude commented
Improvement from https://github.com/Twentysix26/Red-DiscordBot/pull/453

2016-11-08 21:16 UTC, palmtree5 commented
Endorsing this over #453. Definitely a much better idea to wait until it's time to disconnect to stop the music rather than immediately on the bot being the only user in the voice channel

2016-11-10 01:45 UTC, Twentysix26 requested changes
I assume you haven't tested it, [this](https://github.com/SomeFixItDude/Red-DiscordBot/blob/232b86357ea32cce69b6b8e936f9c7b421f6c2cd/cogs/audio.py#L1851) will equal to true in the next cycle (5 secs later) and the timestamp gets reset everytime.

2016-11-10 13:29 UTC, SomeFixItDude reviewed
Thanks @Twentysix26 - Updated the logic and now will not fall through to the elif where the timer is reset

2016-11-10 22:54 UTC, Twentysix26 approved these changes

2016-11-10 22:56 UTC, merged