Red 3.4.2 - Changelog
Cog-Creators/Red-DiscordBot pull request #4560
Opened 2020-10-28 17:08 UTC by jack1142

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Docs

### Description of the changes
Changelog for Red version 3.4.2.

Rendered documentation can be seen at https://red-discordbot--4559.org.readthedocs.build/en/4559/changelog_3_4_0.html

2020-10-28 17:27 UTC, Flame442 requested changes

2020-10-28 17:27 UTC, Flame442 commented on docs/changelog_3_4_0.rst
> +- Fixed ``[p]local search`` command (:issue:`4553`)
```suggestion
- Fixed the ``[p]local search`` command (:issue:`4553`)
```

2020-10-28 17:27 UTC, Flame442 commented on docs/changelog_3_4_0.rst
> +- Added info about metadata file to ``redbot --debuginfo`` (:issue:`4557`)
```suggestion
- Added info about the metadata file to ``redbot --debuginfo`` (:issue:`4557`)
```

2020-10-28 17:27 UTC, Flame442 commented on docs/changelog_3_4_0.rst
> +- Added error messages for exceeded YouTube quota in Streams cog (:issue:`4552`)
```suggestion
- Added error messages when exceeding the YouTube quota in the Streams cog (:issue:`4552`)
```

2020-10-28 17:27 UTC, Flame442 commented on docs/changelog_3_4_0.rst
> +- Improved logging for unexpected errors in Streams cog (:issue:`4552`)
```suggestion
- Improved logging for unexpected errors in the Streams cog (:issue:`4552`)
```

2020-10-28 18:01 UTC, Flame442 approved these changes

2020-10-28 18:01 UTC, zephyrkul approved these changes

2020-10-28 18:02 UTC, ltzmax approved these changes

2020-10-28 18:02 UTC, PredaaA approved these changes

2020-10-28 18:02 UTC, Drapersniper approved these changes

2020-10-28 18:02 UTC, Dav-Git approved these changes

2020-10-28 18:04 UTC, Vexed01 approved these changes

2020-10-28 18:04 UTC, TrustyJAID approved these changes

2020-10-28 18:06 UTC, aikaterna approved these changes

2020-10-28 18:08 UTC, phenom4n4n approved these changes

2020-10-28 18:08 UTC, bobloy approved these changes

2020-10-28 18:10 UTC, TrustyJAID approved these changes

2020-10-28 18:11 UTC, zephyrkul approved these changes

2020-10-28 18:13 UTC, flaree approved these changes

2020-10-28 18:14 UTC, Drapersniper approved these changes
APPROVED as long as it doesn't break shit

2020-10-28 18:14 UTC, TrustyJAID approved these changes
LGTM, as the pros say.

2020-10-28 18:16 UTC, Vexed01 approved these changes

2020-10-28 18:22 UTC, retke approved these changes

2020-10-28 18:22 UTC, Twentysix26 approved these changes

2020-10-28 18:24 UTC, Drapersniper approved these changes
I APPROVE TWENTYSIX' APPROVAL

2020-10-28 18:24 UTC, merged

2020-10-28 18:35 UTC, NeuroAssassin reviewed
LGTM

2020-10-30 16:20 UTC, leElvyn approved these changes