[Docs] Filter Cog Guide
Cog-Creators/Red-DiscordBot pull request #4579
Opened 2020-11-05 20:00 UTC by bobloy

### Type

- [ ] Bugfix
- [X] Enhancement
- [ ] New feature

### Description of the changes

User guide for the Filter cog. Docs were automatically generated using the same method as #4488 
A step towards the #1734 goal

2020-11-12 21:25 UTC, bobloy commented
This is now ready for review. If #4599 is accepted, will fix `[words...]` to `<words...>`

2021-01-13 17:36 UTC, Flame442 requested changes
Some minor consistency and grammar issues, but otherwise solid. Thanks for contributing.

2021-01-13 17:36 UTC, Flame442 commented on docs/cog_guides/filter.rst
> +This cog is designed for "filtering" unwanted words and phrases from a guild.
```suggestion
This cog is designed for "filtering" unwanted words and phrases from a server.
```
Everywhere else in this document, "server" is used, so either consistently use "guild" or change this instance.

2021-01-13 17:36 UTC, Flame442 commented on docs/cog_guides/filter.rst
> +Base command to add or remove words from server filter.
```suggestion
Base command to add or remove words from the server filter.
```
I'm also not a fan of "*add* or *remove* words *from*", but there isn't a good way to make this sound better besides being overly verbose ("add words to or remove words from"). Unless you can think of a better wording I'm fine leaving that how it is.

2021-01-13 17:36 UTC, Flame442 commented on docs/cog_guides/filter.rst
> +Base command to add or remove words from channel filter.
```suggestion
Base command to add or remove words from the channel filter.
```

2021-01-13 17:36 UTC, Flame442 commented on redbot/cogs/filter/filter.py
> +    """This cog is designed for "filtering" unwanted words and phrases from a guild.
```suggestion
    """This cog is designed for "filtering" unwanted words and phrases from a server.
```

2021-01-13 17:36 UTC, Flame442 commented on redbot/cogs/filter/filter.py
> +        """Base command to add or remove words from server filter.
```suggestion
        """Base command to add or remove words from the server filter.
```

2021-01-13 17:36 UTC, Flame442 commented on redbot/cogs/filter/filter.py
> +        """Base command to add or remove words from channel filter.
```suggestion
        """Base command to add or remove words from the channel filter.
```

2021-01-16 01:54 UTC, Flame442 submitted a review, later dismissed
Good to go once the merge conflict is resolved!

2021-01-16 02:10 UTC, Flame442 approved these changes
📦

2021-01-16 02:10 UTC, merged