Make command usage in help for required arguments consistent
Cog-Creators/Red-DiscordBot pull request #4589
Opened 2020-11-10 17:45 UTC by jack1142

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

2020-11-30 21:25 UTC, bobloy approved these changes, later dismissed
All your changes look good to me.

There were a few you missed. Would you like me to list them here, or make a separate PR?

2020-11-30 21:25 UTC, bobloy commented on redbot/core/core_commands.py
> +    @_set.command(name="streaming", aliases=["stream"], usage="[(<streamer> <stream_title>)]")
While weird, I like this method.

2020-11-30 22:00 UTC, bobloy commented
I'll just list them since it's not as many as I thought. I was confused about `require_var_positional`'s interaction with `Greedy`

- Image:
  - `gif`
  - `gifr`
- Permissions:
  - `permissions canrun`

2020-12-15 00:30 UTC, jack1142 commented
I used `require_var_positional=True` in `[p]set api remove` and edited `[p]gif` and `[p]gifr` to be a consume all argument as it didn't make much sense to begin with.
`[p]permissions canrun` wasn't using var positional argument (`*args`), so I haven't touched that one.
Thanks for the help @bobloy!

2020-12-21 03:17 UTC, Flame442 requested changes

2020-12-21 03:17 UTC, Flame442 commented on redbot/cogs/permissions/permissions.py
>          `<who_or_what>` is one or more users, channels or roles the rule is for.
Should this one be `<who_or_what...>`?

2020-12-21 03:17 UTC, Flame442 commented on redbot/cogs/permissions/permissions.py
>          `<who_or_what>` is one or more users, channels or roles the rule is for.
Should this one be `<who_or_what...>`?

2020-12-21 03:17 UTC, Flame442 commented on redbot/cogs/permissions/permissions.py
>          `<who_or_what>` is one or more users, channels or roles the rule is for.
Should this one be `<who_or_what...>`?

2020-12-21 03:17 UTC, Flame442 commented on redbot/cogs/permissions/permissions.py
>          `<who_or_what>` is one or more users, channels or roles the rule is for.
Should this one be `<who_or_what...>`?

2020-12-21 03:17 UTC, Flame442 commented on redbot/core/core_commands.py
> +    @commands.command(name="reload", require_var_positional=True)
Any reason why this `name` is here when it is the same as the function name?

2020-12-21 09:57 UTC, jack1142 commented on redbot/core/core_commands.py
> +    @commands.command(name="reload", require_var_positional=True)
It was like this already so I just haven't touched it. Just changed it now.

2020-12-22 19:08 UTC, Flame442 approved these changes

2020-12-22 19:14 UTC, merged