[Core] Altered call_alias to prevent stripping of newlines
Cog-Creators/Red-DiscordBot pull request #4632
Opened 2020-11-20 00:54 UTC by goettner

### Type

- [X] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes
As detailed in issue #2704 when an alias for a command is created, and this alias is passed input, any newlines in the input are stripped. This is reproducible with the [p]say command (an example can be seen in the issue documentation).

To fix this, I added a new method to alias_entry, get_args_as_single_string(). Unlike get_extra_args_from_alias(), this method retrieves the arguments given to a command alias as an entire string, therefore maintaining any newlines within. To ensure that given arguments are valid, the new method is only used after the args have been validated with get_extra_args_from_alias() and commands.BadArgument.
 
I also added a test case for this issue to tests/cogs/test_alias.py. This required the splitting up of the call_alias in redbot/cogs/alias/alias.py into two functions, in order to return a value that could be tested. It also required the creation of two new fixtures in redbot/pytest/core.py, newline_message and prefix. In the case that more tests are eventually added to test_alias, these might prove useful.

2020-11-20 01:03 UTC, goettner commented
Also not sure why I'm getting the Lint Python error, if anyone knows why let me know and I'll be happy to rectify it.

2020-11-20 01:05 UTC, jack1142 commented
> Also not sure why I'm getting the Lint Python error, if anyone knows why let me know and I'll be happy to rectify it.

`translate_alias_message()` is a method of `Alias` instance, so you need to use it with `self`:
```py
new_message = self.translate_alias_message(message, prefix, alias)
```

2020-11-20 01:46 UTC, goettner commented
> > Also not sure why I'm getting the Lint Python error, if anyone knows why let me know and I'll be happy to rectify it.
> 
> `translate_alias_message()` is a method of `Alias` instance, so you need to use it with `self`:
> 
> ```python
> new_message = self.translate_alias_message(message, prefix, alias)
> ```

Gotcha, will do.

2020-11-20 03:49 UTC, zephyrkul requested changes
This PR doesn't play well with [alias parameters](https://github.com/Cog-Creators/Red-DiscordBot/pull/2455).

If parameters are used, they are inserted into the new message content *and* appended to the content, creating [results like this](https://cdn.discordapp.com/attachments/718148684629540905/779190681100353616/unknown.png).

2020-11-20 04:40 UTC, goettner commented
> This PR doesn't play well with [alias parameters](https://github.com/Cog-Creators/Red-DiscordBot/pull/2455).
> 
> If parameters are used, they are inserted into the new message content _and_ appended to the content, creating [results like this](https://cdn.discordapp.com/attachments/718148684629540905/779190681100353616/unknown.png).

Huh, okay. I wasn't aware of that feature. I'll see if I can find a way to still allow for that while maintaining newlines. Thanks for the feedback!

2020-11-20 19:36 UTC, goettner commented
Alright, customized parameters should work now, alongside newlines. Let me know what you think.

2020-12-01 00:23 UTC, closed without merging

2020-12-01 00:25 UTC, goettner commented
I accidentally pushed some unrelated changes to this PR, and couldn't figure out a way to revert them. I'll open a new PR when I fix it.