[Trivia]
Cog-Creators/Red-DiscordBot pull request #4649
Opened 2020-12-02 08:33 UTC by leblancg

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

This PR is for issue #3931. These changes allow for more than one winner of the trivia game. Each winner will receive an even split of the payout. This also adds a new message to congratulate the winner(s).

2020-12-02 08:41 UTC, leblancg commented
I've tested it out on my own, but is any additional QA recommended? Not really sure how to unit test this using pytest.

2020-12-02 08:52 UTC, jack1142 commented
There's no need for making unit tests here, PRs are reviewed by one of our Core Dev/QA members.

2020-12-18 02:06 UTC, jack1142 requested changes
This is a really clean solution, the code also seems more readable than what's been there before 😄 

The new functionality appears to work fine however, I got a few review comments before I can approve this.

2020-12-18 02:06 UTC, Jackenmen commented on redbot/cogs/trivia/session.py
> +        if len(winners) == 0 or num_humans < 3:
According to our style guide, the fact that empty sequences evaluate to false should be used instead of `len()` (you can see PEP 8 for more information)
```suggestion
        if not winners or num_humans < 3:
```

2020-12-18 02:06 UTC, Jackenmen commented on redbot/cogs/trivia/session.py
> +        )
There's a few things with how this message is defined that need to be changed:
1. `_()` is a call to Translator object defined at the top of the file and is needed in order for the string to be translated when there's a translated version available.
2. Instead of `.join()`, we have a `humanize_list()` utility function that formats a list according to formatting rules of the locale in use.
3. To support plural rules properly with translations, the string for a single user should be a separate from the string for multiple users as it allows translators to make more appropriate translations. While that is not perfect (Red currently doesn't support tools that would be more appropriate for this), it's still better for translating than using a single string with a `{plural}` format field.
```suggestion
        if len(winners) > 1:
            msg = _(
                "Congratulations {users}! You have each received {num} {currency} for winning!"
            ).format(
                users=humanize_list([bold(winner.display_name) for winner in winners]),
                num=payout,
                currency=await bank.get_currency_name(self.ctx.guild),
            )
        else:
            msg =  _(
                "Congratulations {user}! You have received {num} {currency} for winning!"
            ).format(
                user=bold(winners[0].display_name),
                num=payout,
                currency=await bank.get_currency_name(self.ctx.guild),
            )
        await self.ctx.send(msg)
```

2020-12-18 02:06 UTC, Jackenmen commented on redbot/cogs/trivia/session.py
>      async def pay_winner(self, multiplier: float):
Since this is not a public API, it would be clearer if this got renamed to `pay_winners()` and the usage of it got updated appropriately.
```suggestion
    async def pay_winners(self, multiplier: float):
```

2021-01-17 22:21 UTC, jack1142 approved these changes
I went ahead and made the appropriate changes on my own and this is now ready to be merged.
Thanks for your contribution!

2021-01-17 22:32 UTC, merged