[Economy] Add setting for new account initial balance
Cog-Creators/Red-DiscordBot pull request #472
Opened 2016-11-16 22:18 UTC by palmtree5

Supersedes #367 as that PR is extremely out of date. This brings the changes into the current version of economy, thus using dataIO instead of fileIO.

2016-11-17 17:19 UTC, tekulvw requested changes

2016-11-17 17:19 UTC, tekulvw commented on cogs/economy.py
> +            account = self.bank.create_account(user, credits)
This line MUST be `account = self.bank.create_account(user, initial_balance=credits)` because of the damned `*` operator.

2016-11-17 17:19 UTC, tekulvw commented on cogs/economy.py
> +        self.settings[server.id]["REGISTER_CREDITS"] = credits
Should probably limit this to 0 through infinity

2016-11-17 18:24 UTC, palmtree5 commented
Changes have been made

2016-11-17 18:35 UTC, tekulvw submitted a review, later dismissed

2016-11-17 18:35 UTC, tekulvw commented on cogs/economy.py
> +            await self.bot.say("Registering an account will now give " + str(credits) + " credits.")
This should be outside of the if/else block

2016-11-20 17:02 UTC, palmtree5 commented on cogs/economy.py
> +            await self.bot.say("Registering an account will now give " + str(credits) + " credits.")
Not sure I fully understand

2016-11-20 17:18 UTC, Twentysix26 commented on cogs/economy.py
> +            await self.bot.say("Registering an account will now give " + str(credits) + " credits.")
If you don't do that, setting credits lower than 0 will save changes without the bot saying anything

2016-11-24 18:08 UTC, palmtree5 commented
whoops, sorry. Kinda forgot about this pr lol

2016-11-30 17:13 UTC, merged