show a brief info message after cleanup
Cog-Creators/Red-DiscordBot pull request #4762
Opened 2021-01-26 17:45 UTC by AndyButAnnoying

show a message with the amount deleted after cleanup

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature

### Description of the changes

2021-02-22 20:20 UTC, Flame442 requested changes
This PR is currently failing the style check. Please review our [contributing guidelines](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md#43-style) for more information.

2021-02-22 20:20 UTC, Flame442 commented on redbot/cogs/cleanup/cleanup.py
> +        return collected, len(collected)
Rather than returning `len(collected)` in the helper, just get the length from the returned result where you call this helper.

2021-02-22 20:34 UTC, jack1142 commented
In addition to Flame's review, I also want to mention that as discussed in #4732 this should be toggleable.

2021-02-23 17:09 UTC, Andeeeee commented
ill look to it and attempt to fix the stuff

2021-03-07 05:59 UTC, closed without merging