[Docs] Add information about the red index
Cog-Creators/Red-DiscordBot pull request #4778
Opened 2021-02-01 19:12 UTC by bobloy

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Docs

### Description of the changes

Added information about the Red-Index to the Publishing cogs guide.

2021-02-01 20:22 UTC, BreezeQS requested changes

2021-02-01 20:22 UTC, BreezeQS commented on docs/guide_publish_cogs.rst
> +To be added to the index, make a pull request to the `Red-Index repository <https://github.com/Cog-Creators/Red-Index>`_ in the unnapproved section.
Just "unapproved section" looks a bit confusing at first, so tried to address that. Also fixed a small typo.
```suggestion
To be added to the index, make a pull request to the `Red-Index repository <https://github.com/Cog-Creators/Red-Index>`_ in the unapproved section. You can learn more about this process in the repository description.
```

2021-02-01 23:12 UTC, kreus7 requested changes
:doc:`/guide_cog_creators`

2021-02-13 18:08 UTC, Flame442 approved these changes
Looks all set, thanks for helping out!

2021-02-13 18:08 UTC, merged