Fixed a bug Phantium pointed out and more.
Cog-Creators/Red-DiscordBot pull request #480
Opened 2016-11-19 22:14 UTC by Jan200101

Fixed the bot throwing a error when no one was in the voice channel and someone wanted to stop the bot.

Also made nonbots default to 0 because if there is no user in the voice channel it throws a error

2016-11-19 22:25 UTC, Jan200101 commented
Removed unneeded fix.

Nothing more to add to pr

2016-11-20 17:14 UTC, Twentysix26 requested changes

2016-11-20 17:14 UTC, Twentysix26 commented on cogs/audio.py
> +                                     " channel.")
Change this to  
`await self.bot.say("You need to be in the voice channel to stop the music.")`

2016-11-20 19:55 UTC, Jan200101 commented
Also changed the response for skip to fit the same style

2016-11-20 20:29 UTC, Twentysix26 approved these changes

2016-11-20 20:30 UTC, merged