[Mod] Send ban reason on Temp Bans
Cog-Creators/Red-DiscordBot pull request #4837
Opened 2021-02-19 15:11 UTC by kreusada

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes

Closes #4836. Tempbans will DM the user with the reason specified if any

2021-02-19 16:07 UTC, Kowlin reviewed
From a quick glance at it this does not handle whenever the bot *should* send it's reason via the accompany guild setting

2021-02-19 18:32 UTC, Naseer502 submitted a review, later dismissed

2021-02-19 19:09 UTC, Drapersniper requested changes
If adding more config calls in a command, you should simplify these by only calling config once in a command/function/code path.

2021-09-01 23:59 UTC, jack1142 requested changes

2021-09-01 23:59 UTC, jack1142 commented on redbot/cogs/mod/kickban.py
> +                    msg += _("\n\n**Reason:** {reason})").format(
```suggestion
                    msg += _("\n\n**Reason:** {reason}").format(
```

2021-09-01 23:59 UTC, jack1142 commented on redbot/cogs/mod/kickban.py
> +        if settings["dm_on_kickban"]:
The message should be sent *always* but the reason should only be sent *if* dm_on_kickban is True

2021-09-01 23:59 UTC, jack1142 commented on redbot/cogs/mod/kickban.py
> +        settings = await self.config.guild(guild).all()
Can we go for `guild_data` as a var name here instead?

2021-09-02 17:06 UTC, jack1142 approved these changes
Looks good to me, thanks!

![](https://i.fluffy.cc/27MHQpGVHf8zsBqx96gxT5PB5mS1jtjD.gif)

2021-09-02 17:07 UTC, merged