[Docs] Mutes Cog Guide
Cog-Creators/Red-DiscordBot pull request #4875
Opened 2021-03-04 10:26 UTC by Kreusada

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Documentation

### Description of the changes

The Mutes cog guide.

2021-03-21 00:30 UTC, jack1142 reviewed
This PR should update the `.github/labeler.yml` file similarly to how it's done for existing cog guides:
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/.github/labeler.yml#L1-L5

```yaml
"Category: Mutes Cog":
  # Source
  - redbot/cogs/mutes/*
  # Docs
  - docs/cog_guides/mutes.rst
```

2021-03-21 00:36 UTC, jack1142 commented on .github/labeler.yml
> +  - docs/cog_guides/mutes.rst
For consistency with the other entries in the labeler file (the one in the branch this PR is created from is outdated so you can't really see that's the case), there should be appropriate comments:
```suggestion
"Category: Mutes Cog":
  # Source
  - redbot/cogs/mutes/*
  # Docs
  - docs/cog_guides/mutes.rst
```

2021-05-08 00:45 UTC, Flame442 requested changes
A few little things, but otherwise good.

2021-05-08 00:45 UTC, Flame442 commented on docs/cog_guides/mutes.rst
> +* ``<true_or_false>``: Whether or not to enable/disable this setting, most provide ``true`` or ``false``.
```suggestion
* ``<true_or_false>``: Whether to enable or disable this setting, must provide ``true`` or ``false``.
```

2021-05-08 00:45 UTC, Flame442 commented on docs/cog_guides/mutes.rst
> +and rejoin no longer being muted.
![image](https://user-images.githubusercontent.com/34169552/117520144-c91b2a80-af74-11eb-8f60-e2b8f203397e.png)
The syntax on this is broken

2021-05-08 00:45 UTC, Flame442 commented on docs/cog_guides/mutes.rst
> +* ``<true_or_false>``: Whether or not to enable/disable this setting, most provide ``true`` or ``false``.
```suggestion
* ``<true_or_false>``: Whether to enable or disable this setting, must provide ``true`` or ``false``.
```

2021-05-08 00:45 UTC, Flame442 commented on docs/cog_guides/mutes.rst
> +* ``<true_or_false>``: Whether or not to enable/disable this setting, most provide ``true`` or ``false``.
```suggestion
* ``<true_or_false>``: Whether to enable or disable this setting, must provide ``true`` or ``false``.
```

2021-05-08 06:43 UTC, Kreusada commented
Thanks for reviewing, I've made the requested changes.

2021-05-18 21:06 UTC, Flame442 approved these changes
Thanks for making those changes, all set to go now!

2021-05-18 21:06 UTC, merged