[Docs] Mod Cog Guide
Cog-Creators/Red-DiscordBot pull request #4886
Opened 2021-03-14 00:07 UTC by Kreusada

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Documentation

### Description of the changes

Documentation for the Mod cog. (#1734)
Currently not ready for review

2021-03-18 17:22 UTC, bobloy requested changes

2021-03-18 17:22 UTC, bobloy commented on redbot/cogs/mod/kickban.py
>          """Unban a user from this server.
```suggestion
        """Unban a user from this server.

```
Keep the space here, otherwise the next line will be bolded in the help command.

2021-03-18 17:22 UTC, bobloy commented on redbot/cogs/mod/kickban.py
> +    @commands.command(usage="<member> [reason]")
Seems to me like renaming the variable to `member` would be better than having usages in most of the commands.

2021-03-21 00:29 UTC, jack1142 reviewed
This PR should update the `.github/labeler.yml` file similarly to how it's done for existing cog guides:
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/.github/labeler.yml#L1-L5

```yaml
"Category: Mod Cog":
  # Source
  - redbot/cogs/mod/*
  # Docs
  - docs/cog_guides/mod.rst
```

2021-03-21 00:35 UTC, jack1142 commented on .github/labeler.yml
> +  - docs/cog_guides/mod.rst
For consistency with the other entries in the labeler file (the one in the branch this PR is created from is outdated so you can't really see that's the case), there should be appropriate comments:
```suggestion
"Category: Mod Cog":
  # Source
  - redbot/cogs/mod/*
  # Docs
  - docs/cog_guides/mod.rst
```

2021-03-21 00:36 UTC, Kreusada commented
Just realized, will update momentarily

2021-05-08 01:49 UTC, Flame442 requested changes
A few grammar issues, but otherwise good to go.

2021-05-08 01:49 UTC, Flame442 commented on docs/cog_guides/mod.rst
> +* ``[days]``: The amount of days of messages to cleanup on ban. This parameter default to no days.
```suggestion
* ``[days]``: The amount of days of messages to cleanup on ban. This parameter defaults to no days.
```
The default is **not** no days, it's the `defaultdays` setting value.

2021-05-08 01:49 UTC, Flame442 commented on docs/cog_guides/mod.rst
> +* ``<user_ids...>``: The users to ban. This must be a list of user IDs seperated by spaces.
```suggestion
* ``<user_ids...>``: The users to ban. This must be a list of user IDs separated by spaces.
```

2021-05-08 01:49 UTC, Flame442 commented on docs/cog_guides/mod.rst
> +Use this command without any parameter to see current setting.
```suggestion
Use this command without any parameter to see the current setting.
```

2021-05-08 01:49 UTC, Flame442 commented on docs/cog_guides/mod.rst
> +* ``[reason]``: The reason why this user was banned.
```suggestion
* ``[reason]``: The reason why these users were banned.
```

2021-05-08 01:49 UTC, Flame442 commented on docs/cog_guides/mod.rst
> +    This will ban all the added userids and delete 7 days of worth messages.
```suggestion
    This will ban all the added userids and delete 7 days worth of their messages.
```

2021-05-08 01:49 UTC, Flame442 commented on docs/cog_guides/mod.rst
> +* ``[repeats]``: The number of repeated messages to auto-delete.
This should probably be changed to talk about how it's the number of repeated messages needed **before** further messages are deleted

2021-05-08 16:18 UTC, Kreusada commented
Thanks for reviewing, I've addressed the outlined changes.

2021-05-18 21:09 UTC, Flame442 approved these changes
All set now, thanks!

2021-05-18 21:10 UTC, merged