[Mutes] Add guild ID to mutes data
Cog-Creators/Red-DiscordBot pull request #4906
Opened 2021-03-21 20:56 UTC by PredaaA

### Type

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature

### Description of the changes
The reason of this change is because the `bot.get_channel` in `_handle_channel_unmutes` was too much intensive on bot runtime, even more since this runs every 30s.

It includes a converter for the data that runs on `initialize` task before everything else.

2021-03-21 21:13 UTC, Kowlin approved these changes, later dismissed
Code looks good in theory, haven't tested it.

2021-03-21 21:18 UTC, jack1142 requested changes, later dismissed
Just to block Kowlin's review (because I don't have plans for the full review, at least not right now), this won't act properly on bot startup (or at least not efficiently) as `initialize()` is awaited in `setup()` which happens before the bot is ready and its internal cache is filled.
And I've also mentioned to Preda it might be better to use integer for config schema version for the ease of use in future, although that's not as important.

2021-03-24 02:39 UTC, PredaaA commented
> Just to block Kowlin's review (because I don't have plans for the full review, at least not right now), this won't act properly on bot startup (or at least not efficiently) as `initialize()` is awaited in `setup()` which happens before the bot is ready and its internal cache is filled.
> And I've also mentioned to Preda it might be better to use integer for config schema version for the ease of use in future, although that's not as important.

PR got updated to match requested changes.
And also at the same time I can confirm that it fixes performance issues on bot.

2021-04-01 19:55 UTC, TrustyJAID requested changes
One issue needs to be fixed and another slightly better way to handle the conversion imo.

2021-04-01 19:55 UTC, TrustyJAID commented on redbot/cogs/mutes/mutes.py
> +            await self.config.version.set(schema_version)
```suggestion
            await self.config.schema_version.set(schema_version)
```

2021-04-01 19:55 UTC, TrustyJAID commented on redbot/cogs/mutes/mutes.py
> +                    for user_id, mute_data in channel_data["muted_users"].items():
```suggestion
                    async with self.config.channel_from_id(channel_id) as muted_users:
                        for user_id, mute_data in muted_users.items():
                            mute_data["guild"] = channel.guild.id
                            
```

2021-04-01 22:06 UTC, PredaaA commented
Updated the PR with the requested changes.

2021-04-02 00:59 UTC, TrustyJAID approved these changes
This looks good to me. Thanks for making this addition!

2021-04-02 01:01 UTC, merged