[Docs] Warnings Cog Guide
Cog-Creators/Red-DiscordBot pull request #4920
Opened 2021-03-27 22:36 UTC by Kreusada

### Type

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [x] Documentation

### Description of the changes

A user guide for the warnings cog. (#1734)

2021-05-18 21:32 UTC, Kreusada commented
Closing and re-opening to re-run actions

2021-05-26 17:43 UTC, Flame442 requested changes
A few issues, but overall good.

2021-05-26 17:43 UTC, Flame442 commented on docs/cog_guides/warnings.rst
> +* ``<member>``: The member to warn. |member-input-quotes|
```suggestion
* ``<member>``: The member to remove the warn from. |member-input-quotes|
```

2021-05-26 17:43 UTC, Flame442 commented on docs/cog_guides/warnings.rst
> +* ``<points>``: The number of points the warning should be for. If no number is supplied, 1 point will be given. Pre-set warnings disregard this.
```suggestion
* ``[points]``: The number of points the warning should be for. If no number is supplied, 1 point will be given. Pre-set warnings disregard this.
```

2021-05-26 17:43 UTC, Flame442 commented on docs/cog_guides/warnings.rst
> +* ``<reason>``: The reason for the warning. This can be a registered reason if it exists or a custom one is created by default.
This second sentence is a bit awkward, perhaps break it into 2 sentences? You also should specify that custom reasons are only allowed if `[p]warningset allowcustomreasons` is set.

2021-05-27 21:37 UTC, Kreusada commented
Thanks for the review, I've made some changes

2021-05-28 17:00 UTC, Flame442 approved these changes
All set, thanks!

2021-05-28 17:06 UTC, merged