[WIP, not yet working] Config option to not disconnect when just bot in voice
Cog-Creators/Red-DiscordBot pull request #497
Opened 2016-11-28 07:21 UTC by FrostTheFox

Little too hard to explain in the title, but adds an option in audio settings to enable or disable the check that's basically "if only bot in here, disconnect in 5 minutes"

doesn't work yet, dunno why, python noob here

opened PR by request of "if !help answers it u owe me a 🍪" in Discord ;)

2016-11-28 07:34 UTC, Chovin requested changes
thanks for your work.
I suggest you look at some simple cogs for examples, there are some pretty useful examples in some of them.

2016-11-28 07:34 UTC, Chovin commented on cogs/audio.py
> +        setting_nodis = self.settings["NOPPL_DIS"]
`_noppl_disconnect ` is never called and even if it was, the setting is never put into the settings dict `self.settings` or into the `settings.json` file.

2016-11-28 07:34 UTC, Chovin commented on cogs/audio.py
> +                    if (vc.audio_player.is_done() == 1):
`== 1` eh?

2016-11-28 07:34 UTC, Chovin commented on cogs/audio.py
> +                    elif self._noppl_disconnect == False:
you defined this as a function above. this isn't how you call a function.
`if not a_boolean:` is preferred over `if a_boolean == False:`

2016-11-28 07:38 UTC, FrostTheFox commented on cogs/audio.py
> +                    elif self._noppl_disconnect == False:
whoop i'm an idiot

2016-11-28 07:50 UTC, FrostTheFox commented on cogs/audio.py
> +                    if (vc.audio_player.is_done() == 1):
haha understood 👍

2016-11-28 07:59 UTC, FrostTheFox commented on cogs/audio.py
> +        setting_nodis = self.settings["NOPPL_DIS"]
Wouldn't the addition at line 2060 add it if not present? Just tried and it seemed to...

2016-11-28 08:24 UTC, FrostTheFox commented
Alright, it's at least working now.

2016-11-28 08:29 UTC, FrostTheFox commented on cogs/audio.py
> +                    if (vc.audio_player.is_done() == 1):
Fixed this 👍

2016-11-28 08:29 UTC, FrostTheFox commented on cogs/audio.py
> +                    elif self._noppl_disconnect == False:
fixed 👍

2016-11-28 13:21 UTC, tekulvw commented on cogs/audio.py
> +        setting_nodis = self.settings["NOPPL_DIS"]
Yeah it will, Kowlin pulled some magic out of his ass a while back on load to make this happen

2016-11-28 13:22 UTC, tekulvw commented
Can you make this editable by contributors? You've got a good start, there's just a few things I'd like to change and add real quick

2016-11-28 18:44 UTC, FrostTheFox commented
Done. Sorry, it became habit on other projects.

2016-11-30 06:55 UTC, tekulvw commented
Okay I think we're ready to go now @Twentysix26

2016-11-30 18:35 UTC, Twentysix26 commented
As it is, it's a global setting. It has no reason to be global.

2016-11-30 18:44 UTC, Twentysix26 requested changes
It should be server based

2016-11-30 19:52 UTC, Twentysix26 approved these changes

2016-11-30 22:03 UTC, FrostTheFox commented
heh, thanks for fixing this up, I wrote this really late at night and I may have been drinking some wine so I was not at peak performance :P

2016-12-06 23:52 UTC, merged