[Docs] updates to the Linux and Mac auto-restart docs
Cog-Creators/Red-DiscordBot pull request #5020
Opened 2021-05-02 18:39 UTC by Obi-Wan3

Updates include:
- add `sudo systemctl disable` command to Linux auto-restart docs
- specify the purposes of each of the two `.log` files for Mac auto-restart
- add a note on what users should do for multiple bots in Mac auto-restart docs
- more commands (that more or less correspond to Linux's) for the loading/starting the `.plist` in Mac auto-restart docs

The Linux update has been tested on a Ubuntu 20.04 VPS, and Mac updates on MacOS Big Sur (non-M1). Anyone with a different MacOS version and/or M1 architecture is welcome to test these command as well, but I don't expect there to be issues.

2021-05-02 18:53 UTC, jack1142 requested changes
Review for the Linux part of the changes.

2021-05-02 18:53 UTC, jack1142 commented on docs/autostart_systemd.rst
> +To disable the service, run the following, adding the instance name after the **@**:
To not give a wrong impression, this should say that what the command does is making the bot not start on boot anymore:
```suggestion
To set the bot to not start on boot anymore, you must disable the service by running the following command, adding the instance name after the **@**:
```

2021-05-12 17:07 UTC, jack1142 requested changes

2021-05-12 17:07 UTC, jack1142 commented on docs/autostart_systemd.rst
> +To view Red’s log, you can access through journalctl:
This sentence is grammatically incorrect.

2021-05-12 17:07 UTC, jack1142 commented on docs/autostart_mac.rst
> +To start the bot and enable auto-restart, run the following:
These might perhaps need the same changes I mentioned for Linux part of the PR?

2021-05-12 17:53 UTC, aikaterna approved these changes
Tested the Mac side of things on a Catalina (10.15.x) x86/Intel device.

2021-05-12 17:54 UTC, jack1142 approved these changes

2021-05-12 17:59 UTC, merged