[Docs] Trivia List Creation User Guide
Cog-Creators/Red-DiscordBot pull request #5023
Opened 2021-05-03 07:55 UTC by Kreusada

A guide for creating trivia lists, closes #4595.

Currently still a work in progress/draft, adaptable for changes via #4580.

2021-05-26 19:00 UTC, Flame442 requested changes
A few typos, but otherwise ok.

2021-05-26 19:00 UTC, Flame442 commented on docs/guide_trivia_list_creation.rst
> +If there are multiple authors, we can seperate them with commas.
```suggestion
If there are multiple authors, we can separate them with commas.
```

2021-05-26 19:00 UTC, Flame442 commented on docs/guide_trivia_list_creation.rst
> +Answers will follow below, each seperated by a line break and with a
```suggestion
Answers will follow below, each separated by a line break and with a
```

2021-05-26 19:00 UTC, Flame442 commented on docs/guide_trivia_list_creation.rst
> +Its always nice to include alternative answers if a question needs it.
```suggestion
It's always nice to include alternative answers if a question needs it. 
```

2021-05-26 19:00 UTC, Flame442 commented on docs/guide_trivia_list_creation.rst
> +answer multiple times in different casing.
```suggestion
answer multiple times in different casings.
```

2021-05-26 20:24 UTC, Kreusada commented
Thanks for reviewing, I've made those changes.

2021-05-28 17:02 UTC, Flame442 approved these changes
All set, thanks!

2021-05-28 17:06 UTC, merged