Add CommandConverter and CogConverter + add usage in Core
Cog-Creators/Red-DiscordBot pull request #5037
Opened 2021-05-11 20:12 UTC by phenom4n4n

Adds a command and cog converter to the `commands.converter` module, which would be useful in several core commands and various cogs.

2021-06-13 07:34 UTC, phenom4n4n commented
This PR is ready for review.

2021-09-02 22:11 UTC, jack1142 requested changes

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/commands/converter.py
> +        """
```suggestion
        """Converts a command name to the matching `Command` object."""
```

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/commands/converter.py
> +        """
```suggestion
        """Converts a cog name to the matching `Cog` object."""
```

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/core_commands.py
>              - `[command_name]` - Checks this command for command specific embed settings.
Argument name was changed: 
```suggestion
            - `[command]` - Checks this command for command specific embed settings.
```
This also needs equivalent change in the docs.

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/core_commands.py
> +    async def command_default_disable_cog(self, ctx: commands.Context, *, cogname: CogConverter):
As with command_name->command, this should also be renamed from cogname to cog:
```suggestion
    async def command_default_disable_cog(self, ctx: commands.Context, *, cog: CogConverter):
```
You will need to update the docstring and docs as well.

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/core_commands.py
> +    async def command_default_enable_cog(self, ctx: commands.Context, *, cogname: CogConverter):
As with command_name->command, this should also be renamed from cogname to cog:
```suggestion
    async def command_default_enable_cog(self, ctx: commands.Context, *, cog: CogConverter):
```
You will need to update the docstring and docs as well.

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/core_commands.py
> +    async def command_disable_cog(self, ctx: commands.Context, *, cogname: CogConverter):
As with command_name->command, this should also be renamed from cogname to cog:
```suggestion
    async def command_disable_cog(self, ctx: commands.Context, *, cog: CogConverter):
```
You will need to update the docstring and docs as well.

2021-09-02 22:11 UTC, Jackenmen commented on redbot/core/core_commands.py
> +    async def command_enable_cog(self, ctx: commands.Context, *, cogname: CogConverter):
As with command_name->command, this should also be renamed from cogname to cog:
```suggestion
    async def command_enable_cog(self, ctx: commands.Context, *, cog: CogConverter):
```
You will need to update the docstring and docs as well.

2021-09-02 22:11 UTC, jack1142 commented on redbot/core/core_commands.py
>              if command not in disabled_commands:
`command` used to be a string so this needs to be updated appropriately:
```suggestion
            if command.qualified_name not in disabled_commands:
```

2021-09-02 22:11 UTC, jack1142 commented on redbot/core/core_commands.py
>              if command not in disabled_commands:
`command` used to be a string so this needs to be updated appropriately:
```suggestion
            if command.qualified_name not in disabled_commands:
```

2021-09-02 22:11 UTC, jack1142 commented on redbot/core/core_commands.py
> +        self, ctx: commands.Context, command: CommandConverter, enabled: bool = None
The argument name was changed so this also needs equivalent change in the docs.

2021-09-02 22:11 UTC, jack1142 commented on redbot/core/core_commands.py
> +        self, ctx: commands.Context, command: CommandConverter, enabled: bool = None
The argument name was changed so this also needs equivalent change in the docs.

2021-09-02 22:11 UTC, jack1142 commented on redbot/core/core_commands.py
> +        self, ctx: commands.GuildContext, command: CommandConverter, enabled: bool = None
The argument name was changed so this also needs equivalent change in the docs.

2021-09-07 21:42 UTC, jack1142 approved these changes
Looks good to me, thanks for the PR!

![](https://i.fluffy.cc/27MHQpGVHf8zsBqx96gxT5PB5mS1jtjD.gif)

2021-09-07 21:43 UTC, merged