Splitting #5011 - Part 1
Cog-Creators/Red-DiscordBot pull request #5044
Opened 2021-05-17 08:19 UTC by Drapersniper

- bump RLL
- logging changes
- player.channel.guild->player.guild

2021-05-17 10:16 UTC, jack1142 requested changes

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/global_db.py
> +                            title.author,
```suggestion
                            "GET/spotify || Ping %s || Status code %d || %s - %s",
                            r.headers.get("x-process-time"),
                            r.status,
                            title,
                            author,
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                        log, exc, "Running database writes for %d (%s)", lock_id, lock_author
I think you didn't mean to change this?
```suggestion
                        log, exc, "Failed database writes for %d (%s)", lock_id, lock_author
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                        log.debug("Running database writes for %d (%s)", lock_id, lock_author)
I think you didn't mean to change this?
```suggestion
                        log.debug("Completed database writes for %d (%s)", lock_id, lock_author)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                            log, exc, "Failed to fetch %s from YouTube table", track_info
```suggestion
                            log, exc, "Failed to fetch %r from YouTube table", track_info
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                            log, exc, "Failed to fetch %s from YouTube table", track_info
```suggestion
                            log, exc, "Failed to fetch %r from YouTube table", track_info
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                        log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                        log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                debug_exc_log(log, exc, "Failed to fetch %s from YouTube table", track_info)
```suggestion
                debug_exc_log(log, exc, "Failed to fetch %r from YouTube table", track_info)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                debug_exc_log(log, exc, "Failed to fetch '%s' from Lavalink table", query_string)
```suggestion
                debug_exc_log(log, exc, "Failed to fetch %r from Lavalink table", query_string)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                    log.debug("Updating Local Database with %s", query_string)
```suggestion
                    log.debug("Updating Local Database with %r", query_string)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                        log.debug("Querying Global DB api for %s", query)
```suggestion
                        log.debug("Querying Global DB api for %r", query)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                log.debug("Querying Lavalink api for %s", query_string)
```suggestion
                log.debug("Querying Lavalink api for %r", query_string)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                    "Failed to enqueue write task for '%s' to Lavalink table",
```suggestion
                    "Failed to enqueue write task for %r to Lavalink table",
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/interface.py
> +                        log.debug("Query is not allowed in %s (%d)", player.guild, player.guild.id)
```suggestion
                        log.debug("Query is not allowed in %r (%d)", player.guild.name, player.guild.id)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/spotify.py
> +                log.debug("Issue making GET request to %s: [%d] %s", url, r.status, data)
```suggestion
                log.debug("Issue making GET request to %r: [%d] %r", url, r.status, data)
```

2021-05-17 10:16 UTC, Jackenmen commented on redbot/cogs/audio/apis/spotify.py
> +                log.debug("Issue making POST request to %s: [%d] %s", url, r.status, data)
```suggestion
                log.debug("Issue making POST request to %r: [%d] %r", url, r.status, data)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/commands/player.py
> +                log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/commands/player.py
> +                            log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                            log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/commands/playlists.py
> +                            log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                            log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/events/lavalink.py
> +        log.debug("Received a new lavalink event for %d: %s: %s", guild_id, event_type, extra)
```suggestion
        log.debug("Received a new lavalink event for %d: %s: %r", guild_id, event_type, extra)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/events/lavalink.py
> +                    "Player resumed Reason: Error code %d & %s, %r", code, reason, player
```suggestion
                    "Player resumed | Reason: Error code %d & %s, %r", code, reason, player
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/events/lavalink.py
> +                    "Reconnecting to channel %d in guild: %d | %d:.2fs",
```suggestion
                    "Reconnecting to channel %d in guild: %d | %.2fs",
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/events/lavalink.py
> +                    "Reconnecting to channel %d in guild: %d | %d.2fs", channel_id, guild_id, delay
```suggestion
                    "Reconnecting to channel %d in guild: %d | %.2fs", channel_id, guild_id, delay
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/events/lavalink.py
>                      )
Should the player be logged here too?

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/tasks/startup.py
> +                            log, exc, "Failed to restore music voice channel (%s)", vc_id
Consistency with the same log above
```suggestion
                            log, exc, "Failed to restore music voice channel %s", vc_id
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/utilities/formatting.py
> +                log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/utilities/player.py
> +                        log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                        log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/utilities/player.py
> +                        log.debug("Query is not allowed in %s (%d)", ctx.guild, ctx.guild.id)
```suggestion
                        log.debug("Query is not allowed in %r (%d)", ctx.guild.name, ctx.guild.id)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/utilities/playlists.py
> +                debug_exc_log(log, err, "Failed to get track for %s", song_url)
```suggestion
                debug_exc_log(log, err, "Failed to get track for %r", song_url)
```

2021-05-17 10:16 UTC, jack1142 commented on redbot/cogs/audio/core/utilities/playlists.py
> +                debug_exc_log(log, err, "Failed to create track for %s", track)
```suggestion
                debug_exc_log(log, err, "Failed to create track for %r", track)
```

2021-05-17 10:23 UTC, Drapersniper commented on redbot/cogs/audio/core/events/lavalink.py
>                      )
Yes, Added

2021-05-17 10:51 UTC, jack1142 approved these changes, later dismissed
Looks good to me, waiting for RLL 0.8.1.

2021-05-18 22:55 UTC, jack1142 approved these changes
Looks good to me

2021-05-18 22:56 UTC, merged