[cleanup] toggleable notification of how many messages were deleted.
Cog-Creators/Red-DiscordBot pull request #5218
Opened 2021-08-16 19:09 UTC by flaree

### Description of the changes

Addition of a toggleable notification allowing to see how many messages have been deleted. Defaults to on

Addition of cleanupset commands, locked to admin or manage message until further discussion.

closes #4732

2021-09-01 01:03 UTC, jack1142 requested changes
Works fine, need to add `force_registration=True` when getting the Config object.

I am wondering about one possible source of confusion though.
When I run `[p]cleanup messages 2`, I'll get "3 messages were deleted." message. While this is *technically* true, I feel like including the command message as part of the count is a bit counter-intuitive and may cause some unnecessary worry.
What do you think about it?

2021-09-01 01:03 UTC, Jackenmen commented on redbot/cogs/cleanup/cleanup.py
> +        self.config = Config.get_conf(self, 8927348724)
```suggestion
        self.config = Config.get_conf(self, 8927348724, force_registration=True)
```

2021-09-01 07:32 UTC, flaree commented
> Works fine, need to add `force_registration=True` when getting the Config object.
> 
> I am wondering about one possible source of confusion though.
> When I run `[p]cleanup messages 2`, I'll get "3 messages were deleted." message. While this is *technically* true, I feel like including the command message as part of the count is a bit counter-intuitive and may cause some unnecessary worry.
> What do you think about it?
> 
> Small note on the possible implementation: in some cases (i.e. command message in `[p]cleanup self`), it is not enough to just unconditionally subtract 1.

~~I actually didn't even know the invoking message got deleted.~~

Yeah, I agree it can be confusing in the cases where you provide an amount.

2021-09-02 22:42 UTC, flaree commented
Haven't went through each command properly, just what I quickly thought needed the invoking message not included.

2021-09-02 22:46 UTC, jack1142 requested changes
- `[p]cleanup bot` should have one message subtracted too
- `[p]cleanup self` should use `can_mass_purge` variable to determine whether one message should be subtracted from the count

2021-09-02 23:11 UTC, jack1142 approved these changes
Looks good to me, thanks for the PR!

![](https://i.fluffy.cc/qHzfcB6BZ9ZD7K3wFknqLsrHqsq56bPM.gif)

2021-09-02 23:12 UTC, merged