Remove semicolon as a valid separator...
Cog-Creators/Red-DiscordBot pull request #5226
Opened 2021-08-25 15:41 UTC by Kowlin

### Description of the changes
*sigh*... I don't like this change...

Closes #5222

2023-09-22 08:58 UTC, Jackenmen commented
I think we should go ahead with this one. Ideally we would also remove the comma but that one is a lot more likely to be used in some old cog's instructions since it used to be the only way to specify these. Let's just leave it like that and reconsider for a future breaking version if anyone starts needing a comma in a token (which I'm kind of surprised hasn't happened *before* semicolon...)

2023-09-22 09:00 UTC, Jackenmen requested changes

2023-09-22 09:00 UTC, Jackenmen commented on redbot/core/core_commands.py
> +            - `<tokens>` - Pairs of token keys and values. The key and value should be separated by one of ` `, or `,`.
This needs to be updated in the relevant cog guide as well + the merge conflict needs to be resolved.

2026-03-04 01:45 UTC, Kowlin commented
Not really needed after all these years it seems.

2026-03-04 01:45 UTC, closed without merging