[Owner] display availble update count in [p]version
Cog-Creators/Red-DiscordBot pull request #533
Opened 2016-12-17 19:50 UTC by palmtree5

This will pull the commit log for the repo from github's api and return an int representing the number of available updates (aka commits that have not yet been pulled) which is then added into the embed that [p]version posts or return None if there is some sort of failure in that check (for example if the repo url is somehow not valid)

2016-12-17 19:52 UTC, Jan200101 commented
testing 👍

2016-12-17 21:20 UTC, Rapptz commented on cogs/owner.py
> +from requests.compat import json as complexjson
Unused import

2016-12-17 21:20 UTC, Rapptz commented on cogs/owner.py
> +    async def _check_remote_commitlog(self, url, chash):
You can do this differently.

Invoking `git remote update` will update the remote refs (pointed by the red repo) in which you can then use something like `git status` on it. Bypassing the github API completely. See [here](http://stackoverflow.com/a/3278427/1381108) for more info.

2016-12-17 21:20 UTC, Rapptz commented on cogs/owner.py
> +import json
Unused import.

2016-12-18 16:50 UTC, Twentysix26 requested changes
What @Rapptz pointed out

2017-02-20 21:22 UTC, closed without merging

2017-02-20 21:22 UTC, Twentysix26 commented
Might be better suited for the launcher. Anyway, closing.