[Audio] Spotify post request fix
Cog-Creators/Red-DiscordBot pull request #5359
Opened 2021-10-01 21:30 UTC by npc203

### Description of the changes
Report by alec in discord. When the status of request to fetch token from spotify isn't 200, The content-type is not json.
This PR handles it ,makes sure the error is propagates and handled.

2021-10-02 09:14 UTC, npc203 commented
While we are still here, the `self.get()` suffers from the same problem, it tries to parse json despite the response not necessarily being one (mostly when response status is 5xx). However fixing the get req needs lots of other changes and error handling pretty much all over the api interface, because it is used in many places unlike post (which just occurs once). Thus I didn't cramp it up into a single PR and let better people deal with it. but do let me know if you would like me to update this PR with a similar approach as done in post.

2021-12-26 01:18 UTC, jack1142 requested changes

2021-12-26 01:18 UTC, jack1142 commented on redbot/cogs/audio/apis/spotify.py
> -            if r.status != 200:
We still should be checking for status code as some (if not most) non-200 responses contain valid JSON. Yes, with current usage this doesn't technically matter but we should be doing it nonetheless.
If we do this, we could probably even simplify `get_access_token()` and remove the `try-except` with `KeyError` from it and just directly assign instead.

2021-12-26 01:19 UTC, jack1142 commented
> While we are still here, the `self.get()` suffers from the same problem, it tries to parse json despite the response not necessarily being one (mostly when response status is 5xx). However fixing the get req needs lots of other changes and error handling pretty much all over the api interface, because it is used in many places unlike post (which just occurs once). Thus I didn't cramp it up into a single PR and let better people deal with it. but do let me know if you would like me to update this PR with a similar approach as done in post.

I suppose this could be added to this PR as well, it's part of the same issue.

2026-05-22 05:30 UTC, closed without merging

2026-05-22 05:30 UTC, Jackenmen commented
It's been over 4 years since the last changes on this PR were made, and there are still unresolved review comments on this PR. It's time to just close this and let someone else pick it up. I made a tracking issue at #6776