Discord Emote to Unicode
Cog-Creators/Red-DiscordBot pull request #536
Opened 2016-12-20 04:14 UTC by levi506

/N{} does not work with The Boxed Numbers and Heart

2016-12-20 05:01 UTC, Chovin commented on cogs/economy.py
> +	'TWO': '2\u20e3',
probably won't compile. mixed indentation, tabs/spaces

2016-12-20 05:04 UTC, Chovin commented on cogs/economy.py
> +     {TWO}{SIX}Bet * 4
were the missing spaces here and above on purpose?

2016-12-20 05:05 UTC, Chovin commented on cogs/economy.py
> +        reel_pattern = ["{CHERRIES}".format(**slot_emotes), "{COOKIE}".format(**slot_emotes), "{TWO}".format(**slot_emotes), "{FOUR LEAF CLOVER}".format(**slot_emotes),
please find a more concise way to do this

2016-12-20 06:08 UTC, Chovin requested changes
please see comments

2016-12-20 06:08 UTC, Chovin commented on cogs/economy.py
> +            reels[1][2].format(**slot_emotes) + " " + reels[2][2].format(**slot_emotes) + "\n"
suggest formatting it all afterwards instead of at each concat

2016-12-20 06:08 UTC, Chovin commented on cogs/economy.py
>          if line[0] == "{TWO}".format(**slot_emotes) and line[1] == "{TWO}".format(**slot_emotes) and line[2] == "{SIX}".format(**slot_emotes):
1. you only really need the values for printing
2. you'll probably never win since `line` only has the emote keys, not the values

2016-12-20 06:14 UTC, Chovin requested changes
please reread previous comments

2016-12-20 06:14 UTC, Chovin commented on cogs/economy.py
> +    'TWO': '"2\u20e3"',
huh?

2016-12-20 06:14 UTC, Chovin commented on cogs/economy.py
> +        if line[0] == "2\u20e3" and line[1] == "2\u20e3" and line[2] == "6\u20e3":
I think you're kinda going backwards here

2016-12-20 06:35 UTC, Chovin commented
most recent changes seem acceptable for the scope of this PR
Nice job :)
just need to test it now to make sure it works for sure. sadly I don't have the time to do this.

2016-12-20 06:36 UTC, Chovin commented
ah. 👍  from me once this gets tested

2016-12-21 15:47 UTC, Twentysix26 commented
Closing in favor of #538 👍

2016-12-21 15:47 UTC, closed without merging