Do not include 'I agree' prompt in translation string
Cog-Creators/Red-DiscordBot pull request #5364
Opened 2021-10-02 17:09 UTC by jack1142

### Description of the changes
Draft because I might as well look through other occurrences of this pattern in the rest of the code.
Fixes #5363

2021-10-02 18:54 UTC, jack1142 commented
This should now include all occurrences of the strings including the response expected by us when we use `bot.wait_for()`.

2021-10-13 09:41 UTC, Dav-Git requested changes
There's a few things that would make the code better readable, but from a functional perspective everything looks fine.

2021-10-13 09:41 UTC, Dav-Git commented on redbot/cogs/mutes/mutes.py
> +                command_2=inline(command_2),
Having this closer to where the variables were defined would make this code a lot more readable.

2021-10-13 09:41 UTC, Dav-Git commented on redbot/cogs/downloader/checks.py
> +    await ctx.send(T_(REPO_INSTALL_MSG).format(confirmation_message=bold("I agree")))
I see why you put the `.format()` here. If we're already moving the text that needs to be typed into the function, you'll probably want to use the same string here as in line 34.
```py
confirmation_message="I agree"
await ctx.send(T_(REPO_INSTALL_MESSAGE).fornmat(confirmation_message=bold(confirmation_message)))
# ...
await ctx.bot.wait_for(
	"message", check=MessagePredicate.lower_equal_to(confirmation_message.lower(), ctx), timeout=30
)
```
That way there's only one place to look for the correct string.

2021-10-13 21:47 UTC, Jackenmen commented on redbot/cogs/mutes/mutes.py
> +                command_2=inline(command_2),
I'm not sure I agree - these variables are defined right above the definition of `msg` variable which makes it easy to see what are the contents of the replacement fields in that text.

2021-10-13 21:48 UTC, Jackenmen commented on redbot/cogs/downloader/checks.py
> +    await ctx.send(T_(REPO_INSTALL_MSG).format(confirmation_message=bold("I agree")))
Done 👍

2021-10-13 23:06 UTC, Dav-Git submitted a review, later dismissed

2021-10-14 18:52 UTC, Flame442 requested changes
Mild formatting issues.

2021-10-14 18:52 UTC, Flame442 commented on redbot/cogs/mutes/mutes.py
> +            "{command_2} if you just want a basic role created setup.\n\n"
There is no space between the previous line and this one (same behavior as the old code, but incorrect)

2021-10-14 18:52 UTC, Flame442 commented on redbot/core/core_commands.py
> +                + "(yes/no)"
This one still needs a leading space

2021-10-15 16:59 UTC, Flame442 approved these changes

2021-10-15 22:02 UTC, merged