[Modlog]Raise error instead of failing silently on invalid arguments
Cog-Creators/Red-DiscordBot pull request #5386
Opened 2021-10-12 20:17 UTC by Dav-Git

### Description of the changes
Closes #3346 

Raise ValueError when an invalid casetype is passed to modlog.create_case()

Shouldn't an error also be raised when the bot is passed as the user?
Imo that would then be consistent behaviour within the method.

2021-10-12 22:34 UTC, Dav-Git commented
Someone who knows how to fix pytest... pls help (and teach me how to do it)

2021-10-24 00:13 UTC, Jackenmen submitted a review, later dismissed

2021-10-24 00:13 UTC, Jackenmen commented on redbot/core/modlog.py
> +    user_id = user if type(user) == int else user.id
We could get away with checking against `type()` if it weren't a user-provided argument but since it isn't, we should use `isinstance` here instead:
```suggestion
    user_id = user if isinstance(user, int) else user.id
```

2023-03-18 21:07 UTC, Flame442 requested changes

2023-03-18 21:07 UTC, Flame442 commented on redbot/core/modlog.py
> +        raise ValueError("That is not a valid action type.")
Instead of "that", put the action type that was entered.
```suggestion
        raise ValueError(f"{action_type} is not a valid action type.")
```

2023-03-18 21:07 UTC, Flame442 commented on redbot/core/modlog.py
> +        If user is the bot itself
```suggestion
        If user is the bot itself.
```

2023-03-18 21:24 UTC, Flame442 approved these changes
Thanks!

2023-03-18 21:31 UTC, merged