Document setting overrides in Trivia list format
Cog-Creators/Red-DiscordBot pull request #5390
Opened 2021-10-13 18:58 UTC by Vexed01

Document the CONFIG key in the Trivia List Creation Guide, fixes #3977

Doc build at https://red-discordbot--5390.org.readthedocs.build/en/5390/guide_trivia_list_creation.html#optional-custom-overrides

Also fix the spelling of medallist :)

2021-10-20 09:46 UTC, jack1142 commented
I'm not sure something like "bool" or "int" tells a regular user (as in, not a developer) much and that's who we target with this document.

2021-10-20 15:58 UTC, Vexed01 commented
That's certainly a very valid point that I hadn't considered, thanks for pointing it out.

2021-10-20 17:59 UTC, Jackenmen commented
Most of these accept any number with or without fractional component but there's also `max_score` which only accepts integers. Do you think this could be improved in some way?

2021-10-20 18:18 UTC, Vexed01 commented
I've added decimals to the defaults which accept them and clarified "whole number" for `max_score`.

Would it be worth a new issue to actually validate these, as at the moment anything would be accepted?

2021-10-20 18:21 UTC, Jackenmen commented
> Would it be worth a new issue to actually validate these, as at the moment anything would be accepted?

They are validated, see #4571/#4659.

As for the change, I'm not entirely sure "whole number" is clearer than "integer" would have been. I'm not a native speaker so someone else might want to chime in here.

2021-10-20 18:33 UTC, Vexed01 commented
As far as I'm aware, integers can be positive or negative while whole numbers are always positive - and a negative number for max_score (well, as well as 0) wouldn't be good.

I'm not saying that "whole number" is better as I would hope someone advanced enough to touch this wouldn't put in a negative for max score. Though, "integer" is better than "int". Basically idk either and a 3rd opinion would be useful, but from a technical standpoint I'm pretty sure "whole number" is more accurate for what's wanted, and I think it would look odd if "integer" was surrounded by "number" for the floats.

2021-10-20 18:38 UTC, Flame442 commented
"positive number" / "positive integer" would be my votes, unless it supports zero, in which case "whole number" is best. For the floats, perhaps "number with decimal" or something like that, to avoid the oddity of using just "number" for floats?

2021-10-23 23:46 UTC, Jackenmen commented
The valid values for each of these are:
- max_score: positive integer (>0)
- delay: positive number greater than or equal to 4 (>=4.0)
- timeout: positive number (>0.0)
- payout_multiplier: non-negative number (>=0.0)

Additional notes:
- for `timeout`, equivalent `[p]triviaset` command also imposes an additional requirement that this value is higher than `delay`, we might want to restrict in the same way for YAML files
- for all of the numeric fields, we need to be stricter with what we accept per the requirements above as currently we only restrict to int/float

2023-01-02 04:35 UTC, Jackenmen commented
#5947 is now merged, this PR still needs updates to the used wording. It's been settled in #5947 so it's just a matter of making it consistent with what we use in error messages there.

2023-01-02 19:23 UTC, Jackenmen requested changes

2023-01-02 19:23 UTC, Jackenmen commented on docs/guide_trivia_list_creation.rst
> +        delay: 20
I suggest adding a couple more numeric examples to show what can be passed (hopefully better shows the difference between an integer and a number):
```suggestion
        delay: 20
        payout_multiplier: 0.5
        max_score: 20
```

2023-01-02 19:23 UTC, Jackenmen commented on redbot/cogs/trivia/data/lists/sports.yaml
>  - $25,000
If you want to correct answers in this PR, you should update answers here as well.

2023-01-02 19:23 UTC, Jackenmen commented on docs/guide_trivia_list_creation.rst
> +    How much money is a US Olympic gold medallist awarded?:
`medalist` is a correct US spelling:
https://dictionary.cambridge.org/us/dictionary/english/medalist

2023-01-02 19:23 UTC, Jackenmen commented on redbot/cogs/trivia/data/lists/sports.yaml
> +How much money is a US Olympic gold medallist awarded?:
`medalist` is a correct US spelling:
https://dictionary.cambridge.org/us/dictionary/english/medalist

2023-03-02 14:54 UTC, Jackenmen approved these changes
Looks good to me, thanks for writing this new section.

![](https://i.fluffy.cc/MKjDMmwXxZlqRTwnn070gVqZ8Rwh6d3p.gif)

2023-03-02 14:54 UTC, merged