Add plural forms to the responses of `[p]leave` command
Cog-Creators/Red-DiscordBot pull request #5391
Opened 2021-10-14 20:03 UTC by the-krak3n

### Description of the changes
This PR will improve the response of the `[p]leave` command. Before the response was a little bit messed up but now it will give a better response(idk how to word it).
Before
![leave0](https://user-images.githubusercontent.com/84792368/137387269-4f927586-6365-47d4-aeab-ee5442c75724.PNG)

After: 
![deku](https://user-images.githubusercontent.com/84792368/137385185-40f9bc16-e98a-48eb-8d78-45f37ce80543.PNG)

2021-10-14 20:06 UTC, Jackenmen requested changes
This does not work well with non-English locales.
You should instead have entirely separate strings for singular and plural forms.
Here's an example of what I mean (
```py
if len(guilds) > 1:
    _("Are you sure you want me to leave these servers?")
else:
    _("Are you sure you want me to leave this server?")
```

2021-10-15 07:13 UTC, the-krak3n commented
so is this alright?

2021-10-15 23:04 UTC, Jackenmen requested changes

2021-10-15 23:04 UTC, Jackenmen commented on redbot/core/core_commands.py
>              )
This changes the logic of this code - this should all be inside an `else` block of the `if leaving_local_guild`. As it is right now, it completely disregards that the bot will be leaving the *current* server.

2021-10-15 23:04 UTC, Jackenmen commented on redbot/core/core_commands.py
> +                    await ctx.send(_(f"Alright. Leaving {number} server..."))
This changes the logic of this code - this should all be inside an `else` block of the `if leaving_local_guild is True`. As it is right now, it results in two messages getting sent when leaving the current server.

2021-10-15 23:04 UTC, Jackenmen commented on redbot/core/core_commands.py
> +                _("Are you sure you want me to leave this server")
Missing question mark.
```suggestion
                _("Are you sure you want me to leave this server?")
```

2021-10-15 23:04 UTC, Jackenmen commented on redbot/core/core_commands.py
> +                    await ctx.send(_(f"Alright. Leaving {number} server..."))
No need to use a replacement field in here. Also, f-strings cannot be used for translatable strings.
```suggestion
                    await ctx.send(_("Alright. Leaving one server..."))
```

2021-10-15 23:04 UTC, Jackenmen commented on redbot/core/core_commands.py
> +                    await ctx.send(_(f"Alright. Leaving {number} servers..."))
F-strings cannot be used for translatable strings.
```suggestion
                    await ctx.send(
                        _("Alright. Leaving {number} servers...").format(number=number)
                    )
```

2021-10-15 23:04 UTC, Jackenmen commented on redbot/core/core_commands.py
>                  + "\n".join(f"- {guild.name} (`{guild.id}`)" for guild in guilds)
This can be simplified considering we're only dealing with a single guild:
```suggestion
                + f"- {guilds[0].name} (`{guilds[0].id}`)"
```

2021-10-16 05:49 UTC, the-krak3n commented on redbot/core/core_commands.py
>              )
oh my bad , also i just tried to fix it like this but it didnt work for me 
```python
       if leaving_local_guild:
            guilds = (ctx.guild,)
            msg = (
                _("You haven't passed any server ID. Do you want me to leave this server?")
                + " (y/n)"
            )
        else:
            if number > 1:
                msg = (
                    _(f"Are you sure you want me to leave these servers?")
                    + " (y/n):\n"
                    + "\n".join(f"- {guild.name} (`{guild.id}`)" for guild in guilds)
                )
            else:                
                msg = (
                    _("Are you sure you want me to leave this server?")
                    + " (y/n):\n"
                    + f"- {guilds[0].name} (`{guilds[0].id}`)"
                )
```

2021-10-16 19:00 UTC, Jackenmen commented on redbot/core/core_commands.py
>              )
What exactly didn't work?

2021-10-16 19:12 UTC, the-krak3n commented on redbot/core/core_commands.py
>              )
The expected outcome from the bot when the command is run without passing any guild id was "You haven't passed any server ID. Do you want me to leave this server?" but it sent "Are you sure you want me to leave this server?". Well should i commit the changes?

2021-10-16 19:13 UTC, Jackenmen commented on redbot/core/core_commands.py
>              )
Yeah, if you commit the changes, I can try to see what's wrong.

2021-10-17 06:33 UTC, the-krak3n commented on redbot/core/core_commands.py
>              )
Well nvm its working well 👍 I just forgot to update my core path of bot so was facing some issues sorry for that.

2021-12-24 23:50 UTC, jack1142 approved these changes
LGTM!
![](https://i.fluffy.cc/VKWgLLbr8ZGc8Gs0b6Hm8wb5xQGmlbwR.gif)

2021-12-24 23:51 UTC, merged