Prevent unexpected timedelta matches
Cog-Creators/Red-DiscordBot pull request #5393
Opened 2021-10-15 17:22 UTC by Flame442

Requires groups to end with whitespace or eof before accepting them as valid.

Fixes #5385.

2021-10-16 14:11 UTC, Vexed01 requested changes
This will break the matching of single letters when there are multiple together, for example `1d6h` would only parse the 6h part.

This format is used in the docstring examples of quite a few commands that use the timedelta converter in core (such as [tempban](https://github.com/Cog-Creators/Red-DiscordBot/blob/ad92110f0e3b79bff99267ed51ec1cd4a00deb27/redbot/cogs/mod/kickban.py#L599)), and I would also imagine so in 3rd party cogs.

2021-10-16 18:13 UTC, Flame442 commented
That commit should fix the issue you were having (and seems to make the regex more efficient according to regex101 :P)

2021-10-16 18:46 UTC, Vexed01 submitted a review, later dismissed
LGTM

2021-12-26 00:24 UTC, jack1142 commented
Hmm, would there be any harm in doing a fullmatch instead of a match in `_parse_and_match()`?
This would additionally prevent us from matching something like "1 year 2 quarters" as 1 year even though technically that wasn't the user's entire input.

It would be a tiny change in behavior for `parse_timedelta`/`parse_relativedelta` so we would have to delay this to 3.5.0 but I'm more wondering if I'm missing some **big** issue that could be really problematic for someone's usage if we were to change this?

2021-12-26 00:25 UTC, jack1142 submitted a review, later dismissed
Functionally, this is sound. Depending on the response to my comment, this PR might still need changes though.

2021-12-29 23:46 UTC, jack1142 approved these changes
LGTM!

![](https://i.fluffy.cc/2VN5sRNLH0hds4wglBHfnstJlJXC4mgJ.gif)

2021-12-29 23:46 UTC, merged