Make `emptydisconnect` disconnect when all vc members are bots
Cog-Creators/Red-DiscordBot pull request #5421
Opened 2021-10-24 17:02 UTC by Parnassius

If two Red instances, both with `audioset emptydisconnect` enabled and `audioset dc` disabled, are for whatever reason in the same voice chat they keep each other from disconnecting. Now the bot disconnects when every user in the voice chat is a bot.

2021-10-24 17:05 UTC, Kowlin commented
Nice catch, thanks for the PR.

2021-12-26 01:00 UTC, jack1142 requested changes

2021-12-26 01:00 UTC, Jackenmen commented on redbot/cogs/audio/core/tasks/player.py
> +                if not any(m for m in p.channel.members if not m.bot):
I think this is easier to comprehend when reading the code:
```suggestion
                if p.channel.members and all(m.bot for m in p.channel.members):
```
It also fixes an issue with an empty sequence triggering this `if` (though it's probably a case that wouldn't be hit anyway and even if so, it would just be ignored later on).

2021-12-26 10:21 UTC, Parnassius commented on redbot/cogs/audio/core/tasks/player.py
> +                if not any(m for m in p.channel.members if not m.bot):
Fair point, I've committed the change

2021-12-26 17:56 UTC, jack1142 approved these changes
LGTM, thank you!

![](https://i.gifer.com/ZZhp.gif)

2021-12-26 18:09 UTC, merged