isolate direction of username within modlog
Cog-Creators/Red-DiscordBot pull request #5422
Opened 2021-10-25 18:54 UTC by Jan200101

Came up on the Discord as something that could possibly be implemented

Before this PR:
![image](https://user-images.githubusercontent.com/15076013/138753456-d8950bdf-3cab-406f-b2fb-a19d2429992a.png)

After this PR:
![image](https://user-images.githubusercontent.com/15076013/138753483-0c9a13eb-57fe-4ab4-9a96-ece428738e24.png)

2021-10-25 19:09 UTC, Jan200101 commented
Force pushed first time to correct the styling checks

Force pushed the second time after I was asked if the second LEFT-TO-RIGHT was really needed, which I had some hours ago concluded it was but came to realize it really isn't

2021-10-25 19:09 UTC, mathstrains21 submitted a review, later dismissed

2021-12-25 01:30 UTC, jack1142 requested changes
This doesn't work in embeds:
![image](https://user-images.githubusercontent.com/6032823/147375468-680a383a-3317-4af6-bcce-d58a78cd6b3f.png)
![image](https://user-images.githubusercontent.com/6032823/147375467-0108c7c4-86e9-43f4-b1ab-4da511bef1f1.png)

From my testing, putting LTR override at the beginning of the text instead works just fine so I think this should be a good solution:
![image](https://user-images.githubusercontent.com/6032823/147375474-3f0f30cb-4b2a-438b-80a0-9794516e8882.png)

It *could* make sense to also add this LTR override for the moderator though, it is way less likely to be an issue for a moderator's name.

2021-12-25 01:30 UTC, jack1142 commented on redbot/core/modlog.py
>                  user = f"{self.last_known_username} ({self.user})"
This needs to be updated as well.

2021-12-25 15:26 UTC, jack1142 commented
Sorry, I did not realize my screenshot contained an example with two LTR overrides rather than just one at the beginning (which works fine as well). I just removed the second LTR override myself in the commit I just pushed.

2021-12-25 16:17 UTC, Jan200101 commented
![image](https://user-images.githubusercontent.com/15076013/147389160-832942f6-5220-4c46-aa57-d20f5535806d.png)
Talked about this on Discord

Isolating the name should keep its direction intact while allowing the format of name#discrim (id) to stay intact

2021-12-25 16:30 UTC, jack1142 approved these changes
Works great now, thanks for the PR!

![cat-xmas](https://user-images.githubusercontent.com/6032823/147389441-baba55fe-7335-4cfb-846b-c652108b4757.gif)

2021-12-25 16:34 UTC, merged