Add typechecking to config from_id methods
Cog-Creators/Red-DiscordBot pull request #5564
Opened 2022-02-03 20:10 UTC by i-am-zaidali

### Description of the changes

This PR is a redo for #5462

2022-02-03 20:20 UTC, jack1142 requested changes, later dismissed
Considering that this is a performance-critical section *and* that there could be subclasses of `int` that we don't intend to accept (e.g. `bool`), checking for the exact `int` type is preferred here.

2022-02-03 20:20 UTC, jack1142 commented on redbot/core/config.py
> +        if not isinstance(guild_id, int):
```suggestion
        if type(guild_id) is not int:
```

2022-02-03 20:20 UTC, Jackenmen commented on redbot/core/config.py
> +        if not isinstance(channel_id, int):
```suggestion
        if type(channel_id) is not int:
```

2022-02-03 20:20 UTC, Jackenmen commented on redbot/core/config.py
> +        if not isinstance(role_id, int):
```suggestion
        if type(role_id) is not int:
```

2022-02-03 20:20 UTC, jack1142 commented on redbot/core/config.py
> +        if not isinstance(user_id, int):
```suggestion
        if type(user_id) is not int:
```

2022-02-03 20:20 UTC, Jackenmen commented on redbot/core/config.py
> +        if not isinstance(guild_id, int):
```suggestion
        if type(guild_id) is not int:
```

2022-02-03 20:20 UTC, jack1142 commented on redbot/core/config.py
> +        if not isinstance(member_id, int):
```suggestion
        if type(member_id) is not int:
```

2022-02-03 20:21 UTC, i-am-zaidali commented on redbot/core/config.py
> +        if not isinstance(member_id, int):
lemme do that real quick. brb

2022-02-03 21:00 UTC, Flame442 requested changes
Almost ready...

2022-02-03 21:00 UTC, Flame442 commented on redbot/core/config.py
> +                f"`guild_id` should be of type `int`, not {guild_id.__class__.__name__}"
```suggestion
                f"guild_id should be of type int, not {guild_id.__class__.__name__}"
```
The backticks should either be there for all "code" items or for none of them. I personally vote they should not be there.

2022-02-03 21:14 UTC, i-am-zaidali commented
i committed from phone so checks failed. Gonna run them in the morning sorry for the delay

2022-02-06 07:27 UTC, Flame442 approved these changes
Thanks for the PR!

2022-02-20 20:50 UTC, merged