Add JSON Schema for Trivia Lists
Cog-Creators/Red-DiscordBot pull request #5565
Opened 2022-02-03 20:30 UTC by Kreusada

### Description of the changes

Closes #5301. May be altered pending comments on #5390.

Adds JSON schema for Trivia list author and configuration keys, still a work in progress.

2022-02-03 20:35 UTC, jack1142 commented
Once this is approved and merged, you or I should make a PR against https://github.com/SchemaStore/schemastore as well (see SchemaStore/schemastore#1226)

2022-02-03 20:45 UTC, Kreusada commented
> Once this is approved and merged, you or I should make a PR against https://github.com/SchemaStore/schemastore as well (see [SchemaStore/schemastore#1226](https://github.com/SchemaStore/schemastore/pull/1226))

I'd be happy doing this 👍

2022-12-29 04:24 UTC, Jackenmen requested changes
In addition to the review comments:
- the JSON file should be formatted with 2 space indentation to be consistent with existing schema files
- it would be great if the trivia cog ignored `$schema` key instead of treating it as a question
- schema should specify that all other keys should be lists of strings
    - this should be achievable with `additionalProperties`: https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.3.2.3

2022-12-29 04:24 UTC, Jackenmen commented on schema/trivia.schema.json
> +    "title": "Red-DiscordBot Trivia metadata file",
```suggestion
    "title": "Red-DiscordBot Trivia List file",
```

2022-12-29 04:24 UTC, Jackenmen commented on schema/trivia.schema.json
> +            "required": [],
This is the default value so it should not need to be specified:
```suggestion
```

2022-12-29 04:24 UTC, Jackenmen commented on schema/trivia.schema.json
> +            }
The only valid keys are specified in the schema so we can disallow names not listed here:
```suggestion
            },
            "additionalProperties": false
```

2022-12-29 04:49 UTC, Jackenmen requested changes
I sent the first review a bit too soon - I forgot to review properties in `CONFIG` key...
Aside from review comments, you should probably also remove the default values from everything as they're not actually accurate since they depend on whatever the server set those values to. All of the keys simply have no default value, if they're not specified in the YAML file then they're simply not being overridden.

2022-12-29 04:49 UTC, Jackenmen commented on schema/trivia.schema.json
> +                    "description": "Answer time limit in seconds, must be positive number greater than 0.0. Defaults to 15.0.",
```suggestion
                    "description": "The maximum number of seconds permitted to answer a question, must be a positive number greater than or equal to 4.0. Defaults to 15.0.",
                    "minimum": 4.0,
```

2022-12-29 04:49 UTC, Jackenmen commented on schema/trivia.schema.json
> +                    "description": "Number of points required in order win the trivia, must be positive integer. Defaults to 10.",
```suggestion
                    "description": "Number of points required in order to win the trivia, must be a positive integer. Defaults to 10.",
                    "exclusiveMinimum": 0,
```

2022-12-29 04:49 UTC, Jackenmen commented on schema/trivia.schema.json
> +                    "description": "Timeout per question in seconds, must be positive number greater than 0.0. Defaults to 120.0.",
```suggestion
                    "description": "Number of seconds that need to pass until trivia stops due to no response, must be a positive number greater than 0.0. Defaults to 120.0.",
                    "exclusiveMinimum": 0
```

2022-12-29 04:49 UTC, Jackenmen commented on schema/trivia.schema.json
> +                    "description": "The payout multiplier, must be positive number. Defaults to 0.0.",
```suggestion
                    "description": "The payout multiplier, must be a positive number or zero. Defaults to 0.0.",
                    "minimum": 0
```

2022-12-29 04:49 UTC, Jackenmen commented on schema/trivia.schema.json
> +                    "description": "Whether to use spoiler markdown when revealing question answers. Defaults to false.",
```suggestion
                    "description": "Whether to hide the answers in spoilers when revealing the question's answers. Defaults to false.",
```

2022-12-29 10:55 UTC, Kreusada commented
> it would be great if the trivia cog ignored `$schema` key instead of treating it as a question

What do you mean by this?

2022-12-29 15:06 UTC, Jackenmen commented
JSON schema url can be specified with a top-level `$schema` key (to be explicit rather than rely on editor's auto-detection). However, Trivia cog will currently reject this as it expects all keys except AUTHOR and CONFIG to be questions.

2023-01-02 04:46 UTC, Jackenmen commented
This should probably just require adding this line to the `TRIVIA_LIST_SCHEMA` dictionary:
```
Optional("$schema"): And(str, error=_("{key} key must be a text value.")),
```

2023-01-03 21:58 UTC, Jackenmen requested changes
In addition to the review comments, it seems that the default values are still in the property descriptions, they should be removed from there as well.

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +  }
This remains to be unaddressed:
> - schema should specify that all other keys should be lists of strings
>     - this should be achievable with `additionalProperties`: https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.3.2.3

This should work:
```suggestion
  },
  "additionalProperties": {
    "type": "array",
    "items": {
      "type": "string"
    }
  }
```

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +  "properties": {
I'm unsure this is required but some schema validators seem to reject `$schema` field as having an invalid type when `additionalProperties` is set to an array of strings so it's probably better to define it:
```suggestion
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
```

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +      "description": "Author of the Trivia quiz."
```suggestion
      "description": "Author of the Trivia list."
```

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +          "default": true
Missed the removal of default in this one:
```suggestion
          "description": "Whether or not to reveal the answer when the question times out. Defaults to true."
```

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +          "type": ["integer", "number"],
`number` already supports integers:
```suggestion
          "type": "number",
```

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +          "type": ["integer", "number"],
`number` already supports integers:
```suggestion
          "type": "number",
```

2023-01-03 21:58 UTC, Jackenmen commented on schema/trivia.schema.json
> +          "type": ["integer", "number"],
`number` already supports integers:
```suggestion
          "type": "number",
```

2023-02-23 14:59 UTC, Jackenmen commented
> In addition to the review comments, it seems that the default values are still in the property descriptions, they should be removed from there as well.

Unsure if you know but above remains unaddressed.

It also seems that this PR isn't really blocked by the PR mentioned in the description, it would just need changes *if* the other one gets merged first. Am I missing something?

2023-02-23 16:16 UTC, Kreusada commented
> In addition to the review comments, it seems that the default values are still in the property descriptions, they should be removed from there as well. Unsure if you know but above remains unaddressed.

Ah I had missed this, I had addressed these changes now.

2023-03-02 14:43 UTC, Jackenmen approved these changes
LGTM, sorry for the delay. As mentioned before, this should now be added to schemastore repository.

![](https://i.fluffy.cc/4HrdmGw7MHL3rcH3J0lCBBG7xhlxnWs7.gif)

2023-03-02 14:43 UTC, merged

2023-03-02 20:55 UTC, Kreusada commented
https://github.com/SchemaStore/schemastore/pull/2810