[Audio] Update play message
Cog-Creators/Red-DiscordBot pull request #5569
Opened 2022-02-08 20:46 UTC by aleclol

### Description of the changes
Pretty small change, all it does is check for if it's an album or playlist (the Query object was already providing this data) and display the correct type instead of always defaulting to saying a playlist was enqueued.

Also, while doing this I noticed playlist_url was set to None at the top of the function, but it was never changed to be the playlist url later, so I 'fixed' (was that intentional?) that as well.

2022-03-20 13:38 UTC, Drapersniper reviewed
LGTM, yeah no the playlist_url was a bug

2022-03-20 14:38 UTC, Drapersniper commented
![image](https://user-images.githubusercontent.com/27962761/159167694-7a25d265-4523-440e-b217-42c6424217b8.png)


LGTM - I see you changed the album/playlist title from bold to normal - I'm not against it and rather like the contrast caused on the embed.

@aikaterna  if you are okay with the change in Bold -> Not bold then this can be merged

2022-12-29 00:20 UTC, Jackenmen requested changes

2022-12-29 00:20 UTC, Jackenmen commented on redbot/cogs/audio/core/utilities/player.py
> +                description=f"[{playlist_name}]({playlist_url})"
```suggestion
                description=bold(f"[{playlist_name}]({playlist_url})")
```

2022-12-30 03:45 UTC, Jackenmen approved these changes
Thanks for the PR!

![](https://i.fluffy.cc/4pzS922wdxxZ5qdZCFwLRs2pqg46hPnc.gif)

2022-12-30 03:48 UTC, merged