Improve topography trivia
Cog-Creators/Red-DiscordBot pull request #5572
Opened 2022-02-12 20:08 UTC by Visne

### Description of the changes
What prompted me to do this was that "Swaziland" was the only correct answer to the worldmap question, even though that's wrong. While I was there I cleaned up some other things. I tried to mostly add answers but removed some wrong ones as well:

- Using island names as country names (except Ireland, as it is extremely common)
- Inconsistencies
- Native language names of countries (Deutschland, eSwatini, Palaos Bandera)
- Names no longer in use (Swaziland)

2022-03-30 23:27 UTC, Kreusada reviewed
I've just looked through these changes and double checked them, they all look good to me.

2022-09-05 19:05 UTC, Flame442 requested changes

2022-09-05 19:05 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldflags.yaml
> -- Republic of the Philippines
Not sure why you removed this option, when another official name `Republic of Maldives` was added. Can you explain your reasoning for this?

2022-09-05 19:05 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldflags.yaml
>  - Republic of Congo
A previous answer for this country uses 
```
Democratic Republic of the Congo
Dem. Rep. of Congo
Democratic Republic of Congo
DRC
```
as the answers. Bare minimum, the same country should have the same answers across the board.

2022-09-05 19:05 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldflags.yaml
> -- Republic of South Africa
Again, not sure why this was removed, when this is the official name.

2022-09-05 19:05 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldmap.yaml
>  - Germany
Officially `Federal Republic of Germany`, since those are being added

2022-09-09 15:59 UTC, Visne commented
@Flame442 I'm think I originally added the `Republic of Maldives` because I thought "Maldives" referred to a geoghrapic island, which is not the case. Therefore I will remove the change.

The reasoning is as follows:
1. Don't use an official country name, because this isn't really done for most of the answers.
2. However, if the informal name would be incorrect, use the official country name.

Example: people use "Ireland" to refer to the Republic of Ireland. However, Ireland is a geographic island, and the Republic of Ireland is only a part of that island.

2022-09-09 15:59 UTC, Visne commented on redbot/cogs/trivia/data/lists/worldflags.yaml
> -- Republic of the Philippines
Will be removed.

2022-09-09 16:00 UTC, Visne commented on redbot/cogs/trivia/data/lists/worldflags.yaml
>  - Republic of Congo
I'm not sure what you mean, the Democratic Republic of the Congo and the Republic of the Congo are two different countries.

2022-11-12 23:49 UTC, Flame442 approved these changes

2022-11-12 23:49 UTC, merged