Add support for set api Modals
Cog-Creators/Red-DiscordBot pull request #5637
Opened 2022-03-26 02:54 UTC by Kowlin

### Description of the changes
* Changes ``set api`` to have the default options to spawn as a modal
* Allowed developers to call an ``SetApiView`` and ``SetApiModal`` to set API keys in a secure manner.
* These modals and views are hard coded to only accept bot owners.

### Have the changes in this PR been tested?
Yes

2022-03-26 03:59 UTC, MeatyChunks commented on redbot/core/utils/views.py
> +        _placeholder_token = "client_id YOUR_CLIENT_ID"
Maybe client_secret can go here too? Clearing up any confusion of there being only one modal to fill in.

2022-03-26 04:00 UTC, MeatyChunks commented on redbot/core/utils/views.py
> +    async def auth_button(self, button: discord.Button, interaction: discord.Interaction):
Just your luck - interaction parameter order changed requiring the interaction before the button now, lol.

2022-04-13 16:30 UTC, TrustyJAID requested changes

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        bot: Red,
Turns out, you don't need to pass the bot into this. `interaction.client` is the bot.

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        ):  # Prevent non-bot owners from somehow aquiring and saving the modal.
```suggestion
        if (
            not await interaction.client.is_owner(interaction.user)
        ):  # Prevent non-bot owners from somehow aquiring and saving the modal.
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        bot: Red,
```suggestion
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +            await self.bot.set_shared_api_tokens(self.default_service, **tokens)
```suggestion
            await interaction.client.set_shared_api_tokens(self.default_service, **tokens)
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +            await self.bot.set_shared_api_tokens(service, **tokens)
```suggestion
            await interaction.client.set_shared_api_tokens(service, **tokens)
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        bot: Red,
```suggestion
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        self.bot: Red = bot
```suggestion
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        if await self.bot.is_owner(interaction.user) is False:
```suggestion
        if not await interaction.client.is_owner(interaction.user):
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        self.bot: Red = bot
```suggestion
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/core_commands.py
> +                view=SetApiView(self.bot, default_service=service),
```suggestion
                view=SetApiView(default_service=service),
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +    from redbot.core.bot import Red
```suggestion
```

2022-04-13 16:30 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +from typing import TYPE_CHECKING, List, Dict, Union, Optional
```suggestion
from typing import List, Dict, Union, Optional
```

2022-05-08 19:25 UTC, TrustyJAID requested changes
One minor change

2022-05-08 19:25 UTC, TrustyJAID commented on redbot/core/utils/views.py
> +        default_keys: Optional[Union[str, List[str]]] = None,
```suggestion
        default_keys: Optional[Dict[str, str]] = None,
```

2022-05-08 19:35 UTC, TrustyJAID commented on redbot/core/core_commands.py
> +from redbot.core.utils.menus import menu, DEFAULT_CONTROLS
Also DEFAULT_CONTROLS is not imported in master anymore
```suggestion
from redbot.core.utils.menus import menu
```

2022-05-08 20:29 UTC, TrustyJAID approved these changes
Looks good to me!

2022-05-20 19:58 UTC, merged