[General] show stage channels in `[p]serverinfo 1`
Cog-Creators/Red-DiscordBot pull request #5785
Opened 2022-06-26 12:15 UTC by japandotorg

### Description of the changes
Show the number of stage channels inside the Channel field in `[p]serverinfo 1`

### Have the changes in this PR been tested?
No

2022-06-30 02:34 UTC, Flame442 commented
This PR is currently failing the style check. This repo uses the Black autoformatter, and your changes need to be modified to comply with its specifications. Instructions on how to use it can be found in our [contributing.md file](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md#43-style).

2022-07-06 19:05 UTC, japandotorg commented
Oof looks like the style check failed again, i'll properly format it in 2-3 days, my exams are going on atm bc of which i'm kinda busy rn, i'll get back to this pr in a few days.

2022-08-03 18:28 UTC, japandotorg commented
> This PR is currently failing the style check. This repo uses the Black autoformatter, and your changes need to be modified to comply with its specifications. Instructions on how to use it can be found in our [contributing.md file](https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/CONTRIBUTING.md#43-style).

All done now, passed all the checks as well, ty ty

2022-08-08 23:04 UTC, Flame442 requested changes
One little formatting issue, otherwise good to go! Thanks for contributing.

2022-08-08 23:04 UTC, Flame442 commented on redbot/cogs/general/general.py
>                      "\N{SPEAKER WITH THREE SOUND WAVES} Voice: {voice}"
```suggestion
                    "\N{SPEAKER WITH THREE SOUND WAVES} Voice: {voice}\n"
```
Missing a newline here, to match the current formatting

2022-08-08 23:44 UTC, japandotorg commented
Whoops, guess I'm done now. Ty ty!

2022-08-08 23:55 UTC, Flame442 approved these changes

2022-08-08 23:55 UTC, merged