Add heists and a slight modification to payday
Cog-Creators/Red-DiscordBot pull request #582
Opened 2017-01-20 05:44 UTC by Nalexa-1124

Credit to BlueMageX for the code (I got his permission to pr it)

2017-01-20 09:13 UTC, Kowlin commented
Thanks for putting in the effort to make a PR. However as this change includes files from a 3rd party and include changes that remove other fixes and changes from Economy. And there for I don't think we can accept this PR. However, I'll leave it open for @Twentysix26 to decide. I'll add more conflicting stuff in a review.

2017-01-20 09:16 UTC, Kowlin requested changes

2017-01-20 09:16 UTC, Kowlin commented on cogs/economy.py
> -    @_bank.command(pass_context=True, no_pm=True)
Deleting a new command.

2017-01-20 09:16 UTC, Kowlin commented on cogs/economy.py
> +    """Economy - Blue variant
"Blue variant" has to be removed in order to get this mainstreamed for other bots

2017-01-20 09:16 UTC, Kowlin commented on cogs/economy.py
> +    async def paydaycredits(self, ctx, creds: int):
Unneeded variable rename(?)

2017-01-20 09:16 UTC, Kowlin commented on cogs/economy.py
> -        intervals = (  # Source: http://stackoverflow.com/a/24542445
Removing comments and source kills off readability

2017-01-20 13:16 UTC, Twentysix26 commented
I suggest turning it into a separate cog if you want to share it with the community

2017-01-20 13:16 UTC, closed without merging

2017-01-21 15:44 UTC, Nalexa-1124 commented on cogs/economy.py
> +    """Economy - Blue variant
Ah yes I forgot about that