Traceback prompt
Cog-Creators/Red-DiscordBot pull request #5851
Opened 2022-09-18 09:12 UTC by yuansheng1549

### Description of the changes
Allowing `traceback` command to have prompts if there's a lot of error messages 

### Have the changes in this PR been tested?

Yes

Closes #5621

2022-12-28 00:48 UTC, Jackenmen commented on redbot/core/core_commands.py
> +        )
I get the purpose of this but this is extremely hacky for what it's used for... If we *have to* override a context's channel I think we could do away without a copy but I feel like we shouldn't have to. Maybe it's time to have a `send_interactive` utility that isn't tied to a Context object :thinking:

2022-12-28 17:09 UTC, Jackenmen requested changes
A couple of things:
- I'm currently unsure if `send_interactive()` should be part of `redbot.core.utils` (and whether `prompt` is the right name for the submodule it should sit in) or if perhaps it should be a part of the bot object (`Red` class) as are some other send methods such as `send_to_owners()` and `send_filtered()`
    - Since I'm unsure, I suggest not making any changes related to that yet. However, if you do have any opinion on this, I'd be happy to hear it.
- It seems that you've copied an older version of `send_interactive()`, e.g. it doesn't have a `join_character` parameter
- You've changed the behavior of the utility to accept a message with *any* author - you should instead have an argument for specifying the user that the message needs to be authored by
- Ideally, we should support passing pretty much any messageable, that is: `discord.TextChannel`, `discord.VoiceChannel`, `discord.DMChannel`, `discord.User`, `discord.Member`, `commands.Context`, and `discord.Thread`
    - I realize that this is currently impossible due to what `MessagePredicate` supports. I've made a PR (#5942) to rectify this issue, you can assume that it will be merged before your change and change the PR accordingly (which should mean modifying type hints and simplifying the change to `[p]traceback` command).

2023-01-18 07:44 UTC, yuansheng1549 commented
I think it should be part of the bot object

2023-01-18 17:09 UTC, Jackenmen approved these changes, later dismissed
When used in combination with #5942, this works as expected. I'll merge this once #5942 gets approved and merged.

![](https://i.fluffy.cc/TNRR0PklwSCMZlZHQkvpQPNl8h50SpgP.gif)

2023-04-14 16:50 UTC, Jackenmen approved these changes

2023-04-14 16:50 UTC, merged