Harrypotter questions
Cog-Creators/Red-DiscordBot pull request #5887
Opened 2022-10-21 12:23 UTC by Ankur391

### Description of the changes

Added questions in the trivia list of harrypotter as in changed in harrypotter.yaml

### Have the changes in this PR been tested?
Yes

2022-10-22 22:31 UTC, japandotorg commented on redbot/cogs/trivia/data/lists/harrypotter.yaml
> +- Barty Crouch Jr.
```suggestion
- Barty Crouch Jr.
- Barty Crouch Jr
```

2022-11-01 19:19 UTC, Flame442 requested changes

2022-11-01 19:19 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/harrypotter.yaml
> +What quill does Umbridge gives to harry potter during detention?:
```suggestion
What quill does Umbridge give to Harry Potter during detention?:
```

2022-11-01 19:19 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/harrypotter.yaml
> +- Twelve feet
```suggestion
- 12 feet
- Twelve feet
- 12ft
```

2022-11-01 19:19 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/harrypotter.yaml
> +When the Weasley’s won the Daily Prophet Grand Prize Galleon Draw, where do they travel?:
```suggestion
After the Weasleys won the Daily Prophet Grand Prize Galleon Draw, where did they travel?:
```

2022-11-12 23:42 UTC, Flame442 approved these changes

2022-11-12 23:44 UTC, merged