Core - Add invoke error message customisation
Cog-Creators/Red-DiscordBot pull request #5894
Opened 2022-10-29 00:40 UTC by PredaaA

### Description of the changes

Closes #5622.

### Have the changes in this PR been tested?

Yes

2022-10-29 00:53 UTC, PredaaA commented
Trivia cog also had a "Check your console or logs for details." message, it's only displaying if the context author was the bot owner now, to follow what's being done on Audio cog.

2022-10-29 09:02 UTC, Kreusada commented on redbot/core/events.py
>              await ctx.send(inline(message))
```suggestion
            message = await bot._config.invoke_error_msg()
            message = message.replace("{command}", ctx.command.qualified_name)
            await ctx.send(inline(message))
```

`str.replace` returns a copy of the string like many other `str` methods, it doesn't update the actual string. You'd need to reassign this copy to the same variable or pass the copy straight to the function below.

2022-12-29 06:10 UTC, Jackenmen requested changes

2022-12-29 06:10 UTC, Jackenmen commented on redbot/core/bot.py
> +            invoke_error_msg="`Error in command {command}. Check your console or logs for details.`",
I think we should have `None` as the default and use the default message if config value is `None`. This way, we can continue to support translations in the default message *and* we can even only show the "Check your console or logs for details" if the command invoker was a bot owner, with the same check as in trivia cog.
```suggestion
            invoke_error_msg=None,
```

2022-12-29 06:10 UTC, Jackenmen commented on redbot/core/core_commands.py
> +            content = _("Successfully updated the error message back to the default one.")
```suggestion
            content = _("Successfully reset the error message back to the default one.")
```

2022-12-30 02:30 UTC, PredaaA commented
Done both requests.

2022-12-30 02:54 UTC, Jackenmen requested changes

2022-12-30 02:54 UTC, Jackenmen commented on redbot/core/events.py
> +            )
You didn't actually mark the string as translatable. I would also suggest to make the default message consistent with the one in Trivia cog:
```suggestion
            message = await bot._config.invoke_error_msg()
            if not message:
                if ctx.author.id in bot.owner_ids:
                    message = inline(_("Error in command {command}. Check your console or logs for details."))
                else:
                    message = inline(_("Error in command {command}."))
```

2022-12-30 03:10 UTC, Jackenmen commented on redbot/core/core_commands.py
> +    async def _set_errormsg(self, ctx: commands.Context, msg: Optional[str] = None):
```suggestion
    async def _set_errormsg(self, ctx: commands.Context, *, msg: str = None):
```

2022-12-30 03:15 UTC, Jackenmen requested changes

2022-12-30 03:15 UTC, Jackenmen commented on redbot/core/core_commands.py
> +        Use `{command}` to pass the command name in the message.
```suggestion
        Use `{command}` to pass the command name in the message.
        If you omit the `msg` argument, the message will be reset to the default one.
```

2022-12-30 03:15 UTC, Jackenmen commented on redbot/core/core_commands.py
> +    async def _set_errormsg(self, ctx: commands.Context, *, msg: str = None):
This command needs to be added to the core commands guide.

2022-12-30 03:43 UTC, Jackenmen approved these changes
Let's goooo.

![](https://i.fluffy.cc/zVmg9csn3pdFq4S6hQKHKzdCl3B7cRvG.gif)

2022-12-30 03:43 UTC, merged