Trivia files: fix typos
Cog-Creators/Red-DiscordBot pull request #5900
Opened 2022-11-09 14:28 UTC by NCombarieu

### Description of the changes

Fix multiple Typos in trivia questions/answers

### Have the changes in this PR been tested?
Yes

2022-11-09 14:35 UTC, japandotorg commented on redbot/cogs/trivia/data/lists/michaeljackson.yaml
> +- I Just Can't Stop Loving You
this is not a typo.

2022-11-09 14:35 UTC, japandotorg commented on redbot/cogs/trivia/data/lists/finalfantasy.yaml
> +- doesn't have one
not a typo as well

2022-11-09 14:38 UTC, yamikaitou commented on redbot/cogs/trivia/data/lists/entertainment.yaml
> -With which period in music do we associate with composers such as Bach, Handel and Vivaldi?:
Original is correct

2022-11-09 14:38 UTC, yamikaitou commented on redbot/cogs/trivia/data/lists/general.yaml
> -The classical composers Bach, Brahms, Handel, Strauss, and Schumann are all what nationality?:
Original is correct

2022-11-09 17:11 UTC, Flame442 requested changes
Trivia files are stored in a particular format,
```yaml
Question?
- Answer 1
- Answer 2
```
The answers often contain differences in formatting (including some slight grammatical inaccuracies, like "dont") in order to make the bot more responsive for players. 

It looks like you did this automatically, given the that and number of `TwoW ord`s that are incorrectly fixed. In the future, please manually go through you automatically generated output to make sure the sentences still make sense.

Changes requested by other members up to this point also look fine, and are required to satisfy this review.

2022-11-09 17:11 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/entertainment.yaml
> +This film starring Julie Andrews and Christopher Plummer won't he best picture Oscar for 1965?:
```suggestion
This film starring Julie Andrews and Christopher Plummer won the best picture Oscar for 1965?:
```

2022-11-09 17:11 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/michaeljackson.yaml
> +- I Just Can't Stop Loving You
Ditto, not a typo.

2022-11-09 17:11 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/overwatch.yaml
> +Originally when Overwatch was released players could choose to stack multiples of any hero on any team,it was later limited to 1 of each hero per team, and an arcade mode where heroes tacking was aga
```suggestion
Originally when Overwatch was released players could choose to stack multiples of any hero on any team, it was later limited to 1 of each hero per team, and an arcade mode where hero stacking was again possible was added, what is this mode called?:
```

2022-11-09 21:31 UTC, NCombarieu commented
Indeed I used an automatic tool (codespell) to find potential mistakes in these Trivia files.
I am a beginner and would like to learn how to use github and make a contribution to your project to improve myself.
I'll start again from the beginning and try to modify my PR with more attention and let you know very soon.
Thanks for your answer and advice :)

2023-11-06 21:57 UTC, Flame442 commented
All of the requested changes were never addressed, I believe this has been superseded by #5977, and there's a ton of conflicting files at this point, so I am going to close this PR. Feel free to re-make this PR if there are any remaining typos that were not addressed in that PR.

2023-11-06 21:57 UTC, closed without merging