Update FIFA World Cup trivia list with changes from 2022 tournament
Cog-Creators/Red-DiscordBot pull request #5931
Opened 2022-12-19 22:57 UTC by Kreusada

### Description of the changes

Updates the FIFA World Cup trivia list to include outcomes of the 2022 tournament as well as other changes to questions. I have removed 3rd place and 4th place questions, as well as hosting venue questions, as they are too specific and difficult to answer. I've added questions about player rewards, shock results, all-time nation stats, appearances, and more general questions.

If anyone has additional questions worthy of being added, leave a comment or let me know on Discord.

### Have the changes in this PR been tested?

Yes

2023-11-10 19:49 UTC, Flame442 requested changes

2023-11-10 19:49 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldcup.yaml
> +Which country were the hosts of the 2022 World Cup?:
`were the hosts of` -> `was the host of`
`were the champions of` -> `was the champion of`
`were the runner ups of` -> `was the runner up of`
For all questions of these formats

2023-11-10 19:49 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldcup.yaml
>  In 2002, Netherlands failed to qualify after losing to Republic of Ireland. What was the goal difference in this qualification decider?:
```suggestion
In 2002, Netherlands failed to qualify after losing to the Republic of Ireland. What was the goal difference in this qualification decider?:
```
While you're touching this

2023-11-10 19:49 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/worldcup.yaml
> +Iceland have 1 FIFA World Cup appearance, but in which year?:
This structure is a little wordy, maybe
`<Country> has had only 1 FIFA World Cup appearance. In what year did they appear?`

2023-11-12 21:21 UTC, Kreusada commented
Thanks! The necessary changes have been addressed.

2023-11-12 21:23 UTC, Flame442 approved these changes

2023-11-12 21:23 UTC, merged