Fix typos issues
Cog-Creators/Red-DiscordBot pull request #5977
Opened 2023-02-01 15:16 UTC by BigPeep0doo

### Description of the changes

Fix trivia typos

### Have the changes in this PR been tested?

Yes

2023-02-01 15:25 UTC, BigPeep0doo commented
I've find out that Issue #5900 (Trivia files: fix typos) is outdated so i've created a new one.

2023-02-01 20:50 UTC, Flame442 requested changes
While most of the review comments in the original PR were addressed, a few were not. I've moved those here as well.

Otherwise, this PR looks good, but is missing some of the things that were correctly fixed in the other PR. If you want to add those in this PR as well, I can review them here as well.

2023-02-01 20:50 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/entertainment.yaml
> +This film starring Julie Andrews and Christopher Plummer won't he best picture Oscar for 1965?:
```suggestion
This film starring Julie Andrews and Christopher Plummer won the best picture Oscar for 1965?:
```

2023-02-01 20:50 UTC, Flame442 commented on redbot/cogs/trivia/data/lists/overwatch.yaml
> +Originally when Overwatch was released players could choose to stack multiples of any hero on any team,it was later limited to 1 of each hero per team, and an arcade mode where heroes tacking was aga
```suggestion
Originally when Overwatch was released players could choose to stack multiples of any hero on any team, it was later limited to 1 of each hero per team, and an arcade mode where hero stacking was again possible was added, what is this mode called?:
```

2023-02-08 13:00 UTC, BigPeep0doo commented
I've added your suggestions to the PR, is it ok?

2023-02-14 04:35 UTC, Flame442 approved these changes
Thanks!

2023-02-14 04:36 UTC, merged