Allow tempban by ID and ban downgrade
Cog-Creators/Red-DiscordBot pull request #5978
Opened 2023-02-02 09:51 UTC by raidensakura

### Description of the changes

- tempban will allow banning user by ID
- If using the command would cause a downgrade from permanent ban to temporary ban, a prompt will appear asking if command invoker wants to proceed
- If the user is already tempbanned, a prompt will appear asking if command invoker wants to update the duration of the current tempban.
- Prompt will be skipped if `ctx.assume_yes` evaluates to `True`

### Have the changes in this PR been tested?
Yes.

### Additional Notes
This is my first PR to this repo and I'm quite new to Python. Suggestions for improvement to my PR are very welcome.

2023-02-02 19:25 UTC, Zephyrkul commented
> - Prompt will be skipped if `ctx.assume_yes` evaluates to `True`

I don't think allowing tempban to be run on a schedule would be best here.

2023-02-03 05:32 UTC, raidensakura commented
> I don't think allowing tempban to be run on a schedule would be best here.

I'm only implementing this based on Jack's last statement in the issue discussion, it can be raised for discussion again if needed.

I personally think it's okay to include it since prompt only appear if user is already banned anyway, my concern is that whether it should be the default choice to downgrade instead of skipping it completely.

2023-02-03 09:34 UTC, Jackenmen commented
> > * Prompt will be skipped if `ctx.assume_yes` evaluates to `True`
> 
> I don't think allowing tempban to be run on a schedule would be best here.

It's not for scheduling, it's to allow for implementing a command that skips the prompt if someone prefers it that way.

2026-05-28 12:26 UTC, Jackenmen requested changes

2026-05-28 12:26 UTC, Jackenmen commented on redbot/cogs/mod/kickban.py
> +                return False
This can be vastly simplified by using the `ConfirmView`:
```suggestion
            content = (
                _(
                    "User is already tempbanned (ban expires {relative_time}), do you want to proceed?"
                ).format(relative_time=f"<t:{banned_until}:R>")
                if banned_until
                else _("This will downgrade the ban to a tempban, do you want to proceed?")
            )
            view = ConfirmView(ctx.author)
            view.message = await ctx.send(content)
            await view.wait()
            return view.result
```
Also, you weren't using i18n for the strings (i.e. they weren't wrapped in `_()`), the above suggestion fixes that as well.
Bu the way, considering this inner function is only used once, it may make more sense to just put this code directly where the function is used.

2026-05-28 12:26 UTC, Jackenmen commented on redbot/cogs/mod/kickban.py
> +                    (
Use i18n
```suggestion
                    _(
```

2026-05-28 12:26 UTC, Jackenmen commented on redbot/cogs/mod/kickban.py
> +                    ).banned_until()
No need to use the context manager when we're only reading the value:
```suggestion
            current_tempbans = await self.config.guild(guild).current_tempbans()
            banned_until = False
            if member.id in current_tempbans:
                banned_until = await self.config.member_from_ids(
                    guild.id, member.id
                ).banned_until()
```

2026-05-28 12:26 UTC, Jackenmen commented on redbot/cogs/mod/kickban.py
> +            if not member.id in current_tempbans:
The `not in` operator is more readable when testing whether something is not in a collection:
```suggestion
            if member.id not in current_tempbans:
```

2026-05-28 15:35 UTC, Jackenmen submitted a review, later dismissed
Looks good, thanks!

2026-05-28 15:38 UTC, Jackenmen commented on redbot/cogs/mod/kickban.py
> +                    return
```suggestion
                    await ctx.send(_("Okay, I will not be doing that then."))
                    return
```

2026-05-28 15:43 UTC, Jackenmen approved these changes

2026-05-28 15:43 UTC, merged