Fix `set serverprefix` docstring and update its docs
Cog-Creators/Red-DiscordBot pull request #6004
Opened 2023-03-25 11:33 UTC by karlsbjorn

### Description of the changes

Adds a missing backtick so the docstring is properly formatted and updates the docs for the other changes made in #5918.

### Have the changes in this PR been tested?

Yes

2023-03-26 08:56 UTC, Kreusada requested changes, later dismissed

2023-03-26 08:56 UTC, Kreusada commented on docs/cog_guides/core.rst
```suggestion
Show the current settings for Red.

**Examples:**
    - ``[p]set showsettings``
    - ``[p]set showsettings "Red - Discord Bot"``

**Arguments:**
    - ``[server]`` - Optional server to get information for. Leave blank to get the information from the current server.

```

Could you apply this change to the `[p]set showsettings` docstring aswell?

2023-05-12 19:32 UTC, Jackenmen approved these changes
Thanks!

![](https://i.fluffy.cc/qHzfcB6BZ9ZD7K3wFknqLsrHqsq56bPM.gif)

2023-05-12 19:32 UTC, Jackenmen approved these changes
Thanks!

![](https://i.fluffy.cc/qHzfcB6BZ9ZD7K3wFknqLsrHqsq56bPM.gif)

2023-05-12 19:33 UTC, merged