[Core] Added on_error logging
Cog-Creators/Red-DiscordBot pull request #615
Opened 2017-02-12 18:35 UTC by Kowlin

Added on_error logging to handle errors that don't occur in commands. What this does it logging them to the logging module, that redirects them to the handlers (By default ``data/red/red.log`` and stdout)

One thing that I'm not very clear on is the ``ctx`` argument in the ``on_error`` function though. Could not find any information on it.

2017-02-12 21:28 UTC, tekulvw commented
I don't think that `on_error(error, ctx)` is the correct definition, see [here](https://discordpy.readthedocs.io/en/latest/api.html#discord.on_error)

2017-02-13 04:48 UTC, Aareon commented
`ctx` is the context of a given message. Was that was what was in question?

2017-02-13 13:20 UTC, tekulvw requested changes

2017-02-13 13:20 UTC, tekulvw commented on red.py
> +    async def on_error(error, ctx):
Needs to be changed to `on_error(event_name, *args, **kwargs):`

2017-02-13 13:20 UTC, tekulvw commented on red.py
> +        bot.logger.exception(type(error).__name__, exc_info=error)
Needs to be changed to `bot.logger.error("Error in event: {}".format(event_name), exc_info=sys.exc_info())

2017-02-13 13:21 UTC, tekulvw commented
@Aareon nope, see above and linked doc page in the previous post

2017-02-13 15:49 UTC, Aareon commented
@tekulvw I see now, thank you. Changes look good.

2017-02-15 18:01 UTC, tekulvw approved these changes

2017-02-20 03:51 UTC, calebj requested changes
`event_name` should be `error_event`, or vice-versa.

2017-06-20 14:40 UTC, tekulvw commented
@Twentysix26 thoughts?

2017-06-21 14:49 UTC, Kowlin commented
I have some thoughts, this will work in the same way we had on the logging on the v3 branch, thus. this will see everything across the bot.

2017-08-10 00:29 UTC, closed without merging