Add custom status support
Cog-Creators/Red-DiscordBot pull request #6226
Opened 2023-08-09 23:49 UTC by PredaaA

### Description of the changes

This PR adds support for custom status in `[p]set status` command group.
Custom status for bots are now supported since August 8th 2023 https://github.com/discord/discord-api-docs/pull/6345.

### Have the changes in this PR been tested?

Yes.

2023-08-10 00:00 UTC, Jackenmen requested changes
Can we make the argument name something like `text` instead of `name`? Also, the argument name in the Arguments section of the docstring is wrong.

2023-08-10 00:00 UTC, Jackenmen commented on redbot/core/core_commands.py
> +
This is unnecessary, it's already in our codebase looking exactly the same.
```suggestion
```

2023-08-10 00:08 UTC, Jackenmen requested changes
You also need to update `docs/cog_guides/core.rst`.

2023-08-10 00:27 UTC, PredaaA commented
> You also need to update `docs/cog_guides/core.rst`.

Done

2023-08-10 00:29 UTC, Jackenmen commented on docs/cog_guides/core.rst
> +""""""""""""""""""""
nit, we keep the header's over/underline of the same length as the header text
```suggestion
"""""""""""""""""
set status custom
"""""""""""""""""
```

2023-08-10 00:45 UTC, Jackenmen approved these changes
LGTM.

![](https://i.fluffy.cc/3X84Bq2RR182XcPr0NTKKCp7wvNT8MhD.gif)

2023-08-10 00:45 UTC, merged

2023-08-10 10:25 UTC, Rapptz commented
I think this got merged too quick cause the API is still subject to change due to the awkwardness of it.

2023-08-10 11:13 UTC, Jackenmen commented
I saw approval on the dapi docs PR so I assumed it's good to go 😬

2023-08-24 01:32 UTC, DJTOMATO commented
Not sure if should be reported as a "bug"
but the latest red update allows us to set a custom status without a "activity as playing/listening, etc"

``!set status custom Invite me with !invitar | !help`` 

I have noticed that when music is being played by the bot, this command get resetted or cleared, having to set the status manually again.
https://bae.lena.moe/7wDTNa7VBjjo.png