Fix permissions fetching for User Installable Bots
Cog-Creators/Red-DiscordBot pull request #6457
Opened 2024-09-24 12:02 UTC by Kowlin

### Description of the changes

This change fixes permissions regarding discord.Interactions and fetching permissions. Where this would fail where a bot isn't in the server (Yep, that's a thing now!) or doesn't have the channels cached in memory with interactions on User Installable Bots (UIBs) This fix pulls the permissions directly from the interaction, and gives the allowed permissions the interaction can use directly.

This will however sucks for bots trying to see if a person can ignore the ignore list. As its unclear to the bot if the author has manage_guild or similar permissions. But I see no other viable method of solving this.

### Have the changes in this PR been tested?
Partially? (Lmao)

2024-12-24 00:45 UTC, Jackenmen requested changes

2024-12-24 00:45 UTC, Jackenmen commented on redbot/core/bot.py
> +            perms = ctx.channel.permissions_for(author)
`Context` can also be based on an interaction:
```suggestion
        if isinstance(ctx, discord.Message):
            perms = ctx.channel.permissions_for(author)
        else:
            # `permissions` attribute will use permissions from the interaction when possible,
            # or `ctx.channel.permissions_for(author)` for non-interaction contexts.
        	perms = ctx.permissions
```

2024-12-24 03:10 UTC, Jackenmen approved these changes, later dismissed
![](https://i.fluffy.cc/MKjDMmwXxZlqRTwnn070gVqZ8Rwh6d3p.gif)

2024-12-24 14:14 UTC, Jackenmen approved these changes

2024-12-24 14:16 UTC, merged

2024-12-25 05:11 UTC, SomewhatDamaged commented
Huge thanks for this and all the work you do. Upgraded and my slash commands now work in threads (where the bot isn't).

\o/

🎉