[v3] rewrite general
Cog-Creators/Red-DiscordBot pull request #757
Opened 2017-05-13 22:59 UTC by palmtree5

Rewrite of general.py for v3. Probably not completely done depending on what 26 wants to change in general (if anything) but it's a start

2017-05-13 23:19 UTC, Rapptz requested changes
This is no good.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/__init__.py
> +    bot.add_listener(n.check_poll_votes, "on_message")
You can have `on_message` directly in the cog.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +                               "".format(red_choice.value, author.mention))
What is with the disgusting newline here?

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        roles = [x.name for x in user.roles if x.name != "@everyone"]
`roles = [x.name for x in user.roles if not x.is_everyone()]`

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        since_created = (ctx.message.timestamp - user.created_at).days
`Message.timestamp` no longer exists, use `Message.created_at`.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        author = ctx.message.author
There is `Context.author`.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        guild = ctx.message.guild
There is `Context.guild`

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +            pass
This statement is meaningless. Why are you even checking it?

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        elif user.game.url is None:
I think you meant `if user.game and user.game.name`

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +            roles = sorted(roles, key=[x.name for x in guild.role_hierarchy
The first role in the hierarchy is the everyone role. You can remove it by doing something as basic as `guild.role_hierarchy[1:]`. I also don't know what this is supposed to be doing.

If you want to sort the user's roles by hierarchy the only thing you have to do is `sorted(member.roles)`.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        if user.avatar_url:
`User.avatar_url` now returns the default avatar URL if one is not found. You might want to change this to `if user.avatar` instead.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +                             if x.type == discord.ChannelType.text])
`type` attribute no longer exists. You might have meant `isinstance`.

You can do e.g. `len(guild.text_channels)` to get the text channel count.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        voice_channels = len(guild.channels) - text_channels
`len(guild.voice_channels)` or `len(guild.channels) - len(guild.text_channels)` from earlier.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        data.set_footer(text="Guild ID: " + guild.id)
Can't add `int` and `str`.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        colour = int(colour, 16)
Just use `random.randint` here. e.g. `random.randint(0, 0xFFFFFF)`.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        search_terms = "+".join([encode(s) for s in search_terms])
Honestly this entire function is fucked.

`aiohttp` supports `params` as a keyword argument and will automatically do this for you. I don't even know what's going on here.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +            async with aiohttp.request("GET", url) as r:
This was removed in aiohttp v2.0. Create a session and use it instead.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +            if result["list"]:
Store this in a temporary variable instead of calling `__getitem__` repeatedly.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        if not self.getPollByChannel(message):
Missing PEP-8.

2017-05-13 23:19 UTC, Rapptz commented on cogs/general/general.py
> +        for answer in msg: # {id : {answer, votes}}
You probably meant `for i, answer in enumerate(msg, 1)`.

2017-05-13 23:54 UTC, palmtree5 commented on cogs/general/general.py
> +        if not self.getPollByChannel(message):
Not completely clear on this one

2017-05-14 00:08 UTC, palmtree5 commented
Changes done

2017-05-14 00:11 UTC, Rapptz commented on cogs/general/general.py
> +            roles = sorted(user.roles)
You probably want to just move this line to the top a bit.

First initialise:

`roles = sorted(user.roles)[1:]`

Then check if it exists and transform it:

```py
if roles:
  roles = ', '.join(x.name for x in roles)
```

2017-05-14 15:12 UTC, merged