Rewrite Image
Cog-Creators/Red-DiscordBot pull request #768
Opened 2017-05-20 19:17 UTC by palmtree5

This PR provides a rewrite of the Image cog. In addition to the minor changes, this migrates the imgur-related commands from imgurpython (and thus requests) to aiohttp. `[p]imgur random` has also been removed as the part of it with no args (getting a random set of gallery images) is deprecated according to Imgur's API docs and the part with a term may as well have been invoking `[p]imgur search`

2017-06-09 17:02 UTC, tekulvw commented
@palmtree5 are you done developing this/is it ready for testing?

2017-06-09 17:06 UTC, Twentysix26 submitted a review, later dismissed
This needs to be converted from JsonDB to config

2017-06-09 17:53 UTC, palmtree5 commented
@tekulvw not ready given it's still on JsonDB

2017-08-13 01:09 UTC, palmtree5 commented
This is ready now that I've switched it to `Config`

2017-08-13 01:11 UTC, atiwiex commented
Real config*

2017-08-13 18:15 UTC, tekulvw requested changes

2017-08-13 18:15 UTC, tekulvw commented on cogs/image/image.py
> +        self.settings = Config.get_conf(self, identifier=2652104208, force_registration=True)
Didn't register defaults

2017-08-13 20:13 UTC, tekulvw approved these changes

2017-08-13 20:14 UTC, merged