[Alias] V3 Rewrite
Cog-Creators/Red-DiscordBot pull request #780
Opened 2017-05-28 02:51 UTC by tekulvw

2017-06-19 21:24 UTC, Kowlin commented
I only found one thing from my testing, and that is that it pops up a double error message when you're trying to delete a alias that doesn't exist and when their no aliases, either global and on the server.

2017-06-20 17:38 UTC, Twentysix26 requested changes
Tests are failing

2017-06-20 20:21 UTC, tekulvw commented
So I also fixed this nagging issue of the bot's http session hanging around and exiting without closing

2017-06-20 23:05 UTC, Twentysix26 approved these changes

2017-06-21 20:59 UTC, merged