Added subcommand "list"
Cog-Creators/Red-DiscordBot pull request #821
Opened 2017-06-20 11:33 UTC by The-Tasty-Jaffa

This is a temporary thing to allow for users to list all the current stream names in the server the command was called in.

-Requested by 'Freud' to make a pull request

2017-06-20 21:26 UTC, tekulvw requested changes

2017-06-20 21:26 UTC, tekulvw commented on cogs/streams.py
> +        streams = (self.twitch_streams, self.hitbox_streams, self.mixer_streams, self.picarto_streams)
`streams = self.twitch_streams + self.hitbox_streams + self.mixer_streams + self.picarto_streams`

2017-06-20 21:26 UTC, tekulvw commented on cogs/streams.py
> +        for channel in set(ctx.message.server.channels):#..
This whole block should just get changed. With the above changes in place:

```py
in_chan_streams = filter(lambda s: ctx.channel.id in s["CHANNELS"], streams)
stream_names = [s["NAME"] for s in in_chan_streams]
```

2017-06-29 10:16 UTC, The-Tasty-Jaffa reviewed
Updated with suggested changes

2017-08-11 13:37 UTC, RSNFreud commented
1 month and no update?

2017-08-11 13:44 UTC, Kowlin commented
Red v2 (on which this PR is based) is feature locked. I don't know how we will approach old v2 PR's, but please hold on while we get trough the work load in the following weeks.

2017-10-20 03:39 UTC, tekulvw commented
Gonna say no because of the feature lock, feel free to comment on/contribute to #782

2017-10-20 03:39 UTC, closed without merging