[Admin V3] Rewrite of Squid-Plugins Admin cog
Cog-Creators/Red-DiscordBot pull request #825
Opened 2017-06-23 22:57 UTC by tekulvw

Still need to implement:
- [ ] Server lock
- [ ] tests

2017-06-24 18:10 UTC, Twentysix26 commented
Something like ServerTools would be a better name for such a cog, as "admin" implies they're all admin related commands.

This also still lacks *user* hierarchy checks, a person with manage roles shouldn't be able to add all the roles they want at will but strictly the ones they are entitled to (which means any role below their highest  one).

2017-06-24 19:26 UTC, tekulvw commented
It's not strictly server tools though. I feel like Admin is as fitting a name as any seeing as how all of these commands have something to do with server/bot administration.

I will add an optional ability to enable that user hierarchy check. I am sure that some users will want to be able to override discord hierarchy.

2017-06-24 20:48 UTC, Kowlin commented
I don't feel like renaming the cog would have any effect, its simply just a name. Might as well keep it as it currently is. Let alone the people who are familiar with the name and its current toolset, I feel that this will just cause confusion.

2017-10-04 20:02 UTC, palmtree5 requested changes
"GUILD_MEMBER_REMOVE referencing an unknown guild ID:"
Getting that when adding a bot that's been serverlocked

Adding roles to be available via `[p]selfrole` works but actually doing `[p]selfrole rolename` doesn't

2017-10-04 20:02 UTC, palmtree5 commented on redbot/cogs/admin/announcer.py
> +            if self.config.guild(g).announce_ignore():
needs to be awaited

2017-10-14 21:38 UTC, tekulvw commented
Fixed selfrole not working. No repro on the serverlock issue, can you provide a traceback?

2017-10-14 22:03 UTC, palmtree5 approved these changes

2017-10-14 22:05 UTC, merged