Audio cog playlist_extend implementation
Cog-Creators/Red-DiscordBot pull request #829
Opened 2017-06-27 01:44 UTC by frrleone

Implemented playlist_extend in audio cog

Changed _parse_yt_playlist and _parse_sc_playlist to return error messages when the playlist they are passed is invalid

2017-06-27 01:48 UTC, tekulvw requested changes

2017-06-27 01:48 UTC, tekulvw commented on cogs/audio.py
> +        except:
Don't have catch all exception handlers here. Also try to minimize the amount of code inside of a `try/except` and explicitly catch exceptions.

2017-06-27 01:48 UTC, tekulvw commented on cogs/audio.py
> +        except:
Same thing down here.

2017-12-03 21:38 UTC, Kowlin commented
Changes & merge issue has to be resolved before merging.

2018-01-24 00:50 UTC, Tobotimus commented
Closing due to staleness and lack of response.

2018-01-24 00:50 UTC, closed without merging