[CustomCom] [WIP] V3 Rewrite
Cog-Creators/Red-DiscordBot pull request #830
Opened 2017-06-29 21:57 UTC by QingyuChai

Hello.

I'll be trying to rewrite this. 

Maybe I'll try adding argument supports such as {user.name} and stuff.

2017-07-04 17:47 UTC, QingyuChai commented
It will probably be similar to tags.py and trigger cog

2017-07-05 05:27 UTC, tekulvw commented on cogs/customcom/customcom.py
> +        self.c_commands = dataIO.load_json(self.file_path)
Please use the Config object instead of dataIO in V3

2017-07-23 13:06 UTC, QingyuChai commented
Sorry there hasn't been much activity here. I'll try to work on it more.

2017-07-30 18:13 UTC, rttncraft commented
Copied from Cog-Board: Something that will allow for customization on both the creators side and the users side. A combination of Custom Command & Choose; I would like to be able to create a sample list for a command and allow the user to be able to pick a number of results to be given on output.
I got the idea from this site: http://pynewbs.com/5a/a/

2017-07-31 02:23 UTC, tekulvw commented
Can I make some changes to this? Things like...not deleting alias or general lol?

2017-07-31 07:48 UTC, QingyuChai commented
Wait a second... Did I actually do that. I'll fix that lol

2017-08-01 07:46 UTC, QingyuChai commented
Hello! Sorry to bother. It seems that aside from putting it into .gitignore, I also accidentally _deleted_ general.py. Is there anyway to undo this? Sorry for so many problems, first time making Pull Requests :p

2017-08-11 17:20 UTC, tekulvw commented
What's the status on this?

2017-08-12 10:20 UTC, QingyuChai commented
Sorry for the lack of activity, still working on it. I'll try updating more frequently.

2017-08-21 21:27 UTC, QingyuChai commented
I'll be working on this next weekend. School started again so my timetable is a bit hectic.

2017-10-03 22:03 UTC, palmtree5 requested changes
Probably don't need the zip file that's in here. Also should move customcom into `redbot/cogs`

2017-10-06 07:58 UTC, palmtree5 commented
Closing in favor of #1003

2017-10-06 07:58 UTC, closed without merging