Updated Travis batch
Cog-Creators/Red-DiscordBot pull request #897
Opened 2017-08-10 11:08 UTC by Jan200101

2017-08-11 05:36 UTC, palmtree5 requested changes
`https://travis-ci.org/Cog-Creators/Red-DiscordBot.svg?branch=master` branch should be develop

2017-08-11 09:06 UTC, Jan200101 commented
You are right, I didnt look if the url linked to master as Travis normaly links to the default branch
![image](https://user-images.githubusercontent.com/15076013/29207097-231a3e10-7e85-11e7-9002-25ff7a1b2d05.png)

2017-08-11 22:35 UTC, tekulvw commented
Please explicitly use develop, we don't want anything screwing up in the future if/when the default branch gets changed again.

2017-08-12 21:51 UTC, tekulvw approved these changes

2017-08-13 23:12 UTC, Kowlin approved these changes

2017-08-14 19:51 UTC, palmtree5 approved these changes

2017-08-14 19:51 UTC, merged