[Trivia] [WIP] V3 Rewrite
Cog-Creators/Red-DiscordBot pull request #915
Opened 2017-08-14 08:30 UTC by Tobotimus

So far the cog works with V3 (albeit fairly untested), but much is unchanged in terms of functionality and design. Some of the cog's design seems a bit dated and could do with a... _ahem_... rewrite.

This PR supersedes #789 and as such many of the following feature suggestions came from there.

### Goals
- [x] Get cog working in V3
- [ ] Rewrite `TriviaSession`
- [ ] Consolidate how the trivia lists are stored and read
- [ ] Add a payout option for winning

### Possible enhancements
- [ ] Implement some sort of leaderboard system
- [ ] Use of embeds
- [ ] MCQ trivia

One thing I don't plan on changing with this rewrite is the trivia list parser, so anyone who writes trivia lists can rest easy; the `.txt` files need not change.

2017-08-15 08:15 UTC, Tobotimus commented
Alright, `TriviaSession` has just undergone some major changes, and I'm interested to see what you guys think. The back-end of this cog is now fairly complete, so please... try to break it :smile:

2017-08-16 15:38 UTC, Twentysix26 commented
I think you can safely remove the trivia lists from your PR in the meantime. It's unlikely they'll be kept in this branch and they can eventually be added with a different pull request if needed

2017-08-17 00:41 UTC, Tobotimus commented
That's fair enough, they were only there for testing purposes, so no real reason for them to be in the repository, considering they would only be there temporarily.

But on that note, if anyone is testing this PR, trivia lists must be located in the `cogs/trivia/lists` folder in order to be found (until further notice).

2017-10-30 00:22 UTC, calebj requested changes

2017-10-30 00:22 UTC, calebj commented on redbot/cogs/trivia/session.py
> +                await self.stop()
`self.stop()` isn't an async function.

2017-10-30 00:22 UTC, calebj commented on redbot/cogs/trivia/session.py
> +            message = await self.ctx.bot.wait_for(
I don't see anything here that would cause the issue you described. Try to debug and isolate it.

2017-10-30 08:23 UTC, Tobotimus commented
I think this PR is ready for proper testing. Any extra features should probably be added in separate PRs.

To test right now, I recommend doing the following in a clean virtual environment:
```
pip install --process-dependency-links git+https://github.com/Tobotimus/Red-DiscordBot.git@V3/trivia_rewrite
pip install aiohttp==2.2.5
pip install git+https://github.com/Cog-Creators/Red-Trivia.git
```
Then run redbot as usual with `redbot <instance_name>`

2017-10-30 12:33 UTC, tekulvw requested changes
Can you add `Red-Trivia` to the requirements for the bot? I'll get it uploaded to pypi soon.

2017-11-05 18:25 UTC, tekulvw submitted a review, later dismissed

2017-11-06 00:53 UTC, palmtree5 approved these changes

2017-11-06 00:56 UTC, merged